package com.alpdroid.huGen10.obdUtil

enum class DtcBody (val dtc:String) {

    B0000("ISO/SAE Reserved / Vehicle speed information circuit malfunction (Chevy, GM)"),
    B0001("Driver Frontal Stage 1 Deployment Control (Subfault)"),
    B0002("Driver Frontal Stage 2 Deployment Control (Subfault)"),
    B0003("Driver Frontal Stage 3 Deployment Control (Subfault)"),
    B0004("Driver Knee Bolster Deployment Control (Subfault)"),
    B0005("Collapsible Steering Column Deployment Control (Subfault)"),
    B0006("ISO/SAE Reserved"),
    B0007("ISO/SAE Reserved"),
    B0008("ISO/SAE Reserved"),
    B0009("ISO/SAE Reserved"),
    B000A("ISO/SAE Reserved"),
    B000B("ISO/SAE Reserved"),
    B000C("ISO/SAE Reserved"),
    B000D("ISO/SAE Reserved"),
    B000E("ISO/SAE Reserved"),
    B000F("ISO/SAE Reserved"),
    B0010("Passenger Frontal Stage 1 Deployment Control (Subfault)"),
    B0011("Passenger Frontal Stage 2 Deployment Control (Subfault)"),
    B0012("Passenger Frontal Stage 3 Deployment Control (Subfault)"),
    B0013("Passenger Knee Bolster Deployment Control (Subfault)"),
    B0014("ISO/SAE Reserved"),
    B0015("ISO/SAE Reserved"),
    B0016("ISO/SAE Reserved"),
    B0017("ISO/SAE Reserved"),
    B0018("ISO/SAE Reserved"),
    B0019("ISO/SAE Reserved"),
    B001A("ISO/SAE Reserved"),
    B001B("ISO/SAE Reserved"),
    B001C("ISO/SAE Reserved"),
    B001D("ISO/SAE Reserved"),
    B001E("ISO/SAE Reserved"),
    B001F("ISO/SAE Reserved"),
    B0020("Left Side Airbag Deployment Control (Subfault)"),
    B0021("Left Curtain Deployment Control 1 (Subfault)"),
    B0022("Left Curtain Deployment Control 2 (Subfault)"),
    B0023("ISO/SAE Reserved"),
    B0024("ISO/SAE Reserved"),
    B0025("ISO/SAE Reserved"),
    B0026("ISO/SAE Reserved"),
    B0027("ISO/SAE Reserved"),
    B0028("Right Side Airbag Deployment Control (Subfault)"),
    B0029("Right Curtain Deployment Control 1 (Subfault)"),
    B002A("Right Curtain Deployment Control 2 (Subfault)"),
    B002B("ISO/SAE Reserved"),
    B002C("ISO/SAE Reserved"),
    B002D("ISO/SAE Reserved"),
    B002E("ISO/SAE Reserved"),
    B002F("ISO/SAE Reserved"),
    B0030("Second Row Left Side Airbag Deployment Control (Subfault)"),
    B0031("Second Row Left Frontal Stage 1 Deployment Control (Subfault)"),
    B0032("Second Row Left Frontal Stage 2 Deployment Control (Subfault)"),
    B0033("Second Row Left Frontal Stage 3 Deployment Control (Subfault)"),
    B0034("ISO/SAE Reserved"),
    B0035("ISO/SAE Reserved"),
    B0036("ISO/SAE Reserved"),
    B0037("ISO/SAE Reserved"),
    B0038("Second Row Right Side Airbag Deployment Control (Subfault)"),
    B0039("Second Row Right Frontal Stage 1 Deployment Control (Subfault)"),
    B003A("Second Row Right Frontal Stage 2 Deployment Control (Subfault)"),
    B003B("Second Row Right Frontal Stage 3 Deployment Control (Subfault)"),
    B003C("ISO/SAE Reserved"),
    B003D("ISO/SAE Reserved"),
    B003E("ISO/SAE Reserved"),
    B003F("ISO/SAE Reserved"),
    B0040("Third Row Left Side Airbag Deployment Control (Subfault)"),
    B0041("Third Row Left Frontal Stage 1 Deployment Control (Subfault)"),
    B0042("Third Row Left Frontal Stage 2 Deployment Control (Subfault)"),
    B0043("Third Row Left Frontal Stage 3 Deployment Control (Subfault)"),
    B0044("ISO/SAE Reserved"),
    B0045("ISO/SAE Reserved"),
    B0046("ISO/SAE Reserved"),
    B0047("ISO/SAE Reserved"),
    B0048("Third Row Right Side Airbag Deployment Control (Subfault)"),
    B0049("Third Row Right Frontal Stage 1 Deployment Control (Subfault)"),
    B004A("Third Row Right Frontal Stage 2 Deployment Control (Subfault)"),
    B004B("Third Row Right Frontal Stage 3 Deployment Control (Subfault)"),
    B004C("ISO/SAE Reserved"),
    B004D("ISO/SAE Reserved"),
    B004E("ISO/SAE Reserved"),
    B004F("ISO/SAE Reserved"),
    B0050("Driver Seatbelt Sensor (Subfault)"),
    B0051("First Row Center Seatbelt Sensor (Subfault)"),
    B0052("Passenger Seatbelt Sensor (Subfault)"),
    B0053("Second Row Left Seatbelt Sensor (Subfault)"),
    B0054("Second Row Center Seatbelt Sensor (Subfault)"),
    B0055("Second Row Right Seatbelt Sensor (Subfault)"),
    B0056("Third Row Left Seatbelt Sensor (Subfault)"),
    B0057("Third Row Center Seatbelt Sensor (Subfault)"),
    B0058("Third Row Right Seatbelt Sensor (Subfault)"),
    B0059("ISO/SAE Reserved"),
    B005A("ISO/SAE Reserved"),
    B005B("ISO/SAE Reserved"),
    B005C("ISO/SAE Reserved"),
    B005D("ISO/SAE Reserved"),
    B005E("ISO/SAE Reserved"),
    B005F("ISO/SAE Reserved"),
    B0060("Driver Seatbelt Tension Sensor (Subfault)"),
    B0061("Passenger Seatbelt Tension Sensor (Subfault)"),
    B0062("ISO/SAE Reserved"),
    B0063("ISO/SAE Reserved"),
    B0064("ISO/SAE Reserved"),
    B0065("ISO/SAE Reserved"),
    B0066("ISO/SAE Reserved"),
    B0067("ISO/SAE Reserved"),
    B0068("ISO/SAE Reserved"),
    B0069("ISO/SAE Reserved"),
    B006A("ISO/SAE Reserved"),
    B006B("ISO/SAE Reserved"),
    B006C("ISO/SAE Reserved"),
    B006D("ISO/SAE Reserved"),
    B006E("ISO/SAE Reserved"),
    B006F("ISO/SAE Reserved"),
    B0070("Driver Seatbelt Pretensioner \"A\" Deployment Control (Subfault)"),
    B0071("First Row Center Seatbelt Pretensioner Deployment Control (Subfault)"),
    B0072("Passenger Seatbelt Pretensioner \"A\" Deployment Control (Subfault)"),
    B0073("Second Row Left Seatbelt Pretensioner Deployment Control (Subfault)"),
    B0074("Second Row Center Seatbelt Pretensioner Deployment Control (Subfault)"),
    B0075("Second Row Right Seatbelt Pretensioner Deployment Control (Subfault)"),
    B0076("Third Row Left Seatbelt Pretensioner Deployment Control (Subfault)"),
    B0077("Third Row Center Seatbelt Pretensioner Deployment Control (Subfault)"),
    B0078("Third Row Right Seatbelt Pretensioner Deployment Control (Subfault)"),
    B0079("Driver Seatbelt Pretensioner \"B\" Deployment Control (Subfault)"),
    B007A("Passenger Seatbelt Pretensioner \"B\" Deployment Control (Subfault)"),
    B007B("Second Row Left Seatbelt Pretensioner \"B\" Deployment Control (Subfault)"),
    B007C("Second Row Right Seatbelt Pretensioner \"B\" Deployment Control (Subfault)"),
    B007D("Second Row Center Seatbelt Pretensioner \"B\" Deployment Control (Subfault)"),
    B007E("Driver Seatbelt Pretensioner \"C\" Deployment Control (Subfault)"),
    B007F("Passenger Seatbelt Pretensioner \"C\" Deployment Control (Subfault)"),
    B0080("Driver Seatbelt Load Limiter Deployment Control (Subfault)"),
    B0081("First Row Center Seatbelt Load Limiter Deployment Control (Subfault)"),
    B0082("Passenger Seatbelt Load Limiter Deployment Control (Subfault)"),
    B0083("Second Row Left Seatbelt Load Limiter Deployment Control (Subfault)"),
    B0084("Second Row Center Seatbelt Load Limiter Deployment Control (Subfault)"),
    B0085("Second Row Right Seatbelt Load Limiter Deployment Control (Subfault)"),
    B0086("Third Row Left Seatbelt Load Limiter Deployment Control (Subfault)"),
    B0087("Third Row Center Seatbelt Load Limiter Deployment Control (Subfault)"),
    B0088("Third Row Right Seatbelt Load Limiter Deployment Control (Subfault)"),
    B0089("ISO/SAE Reserved"),
    B008A("ISO/SAE Reserved"),
    B008B("ISO/SAE Reserved"),
    B008C("ISO/SAE Reserved"),
    B008D("ISO/SAE Reserved"),
    B008E("ISO/SAE Reserved"),
    B008F("ISO/SAE Reserved"),
    B0090("Left Frontal Restraints Sensor (Subfault)"),
    B0091("Left Side Restraints Sensor 1 (Subfault)"),
    B0092("Left Side Restraints Sensor 2 (Subfault)"),
    B0093("Left Side Restraints Sensor 3 (Subfault)"),
    B0094("Center Frontal Restraints Sensor (Subfault)"),
    B0095("Right Frontal Restraints Sensor (Subfault)"),
    B0096("Right Side Restraints Sensor 1 (Subfault)"),
    B0097("Right Side Restraints Sensor 2 (Subfault)"),
    B0098("Right Side Restraints Sensor 3 (Subfault)"),
    B0099("Roll Over Sensor (Subfault)"),
    B009A("Left Side Restraints Sensor 4 (Subfault)"),
    B009B("Left Side Restraints Sensor 5 (Subfault)"),
    B009C("Left Side Restraints Sensor 6 (Subfault)"),
    B009D("Right Side Restraints Sensor 4 (Subfault)"),
    B009E("Right Side Restraints Sensor 5 (Subfault)"),
    B009F("Right Side Restraints Sensor 6 (Subfault)"),
    B00A0("Occupant Classification System (Subfault)"),
    B00A1("Occupant Position System (Subfault)"),
    B00A2("ISO/SAE Reserved"),
    B00A3("ISO/SAE Reserved"),
    B00A4("ISO/SAE Reserved"),
    B00A5("ISO/SAE Reserved"),
    B00A6("ISO/SAE Reserved"),
    B00A7("ISO/SAE Reserved"),
    B00A8("ISO/SAE Reserved"),
    B00A9("ISO/SAE Reserved"),
    B00AA("ISO/SAE Reserved"),
    B00AB("ISO/SAE Reserved"),
    B00AC("ISO/SAE Reserved"),
    B00AD("ISO/SAE Reserved"),
    B00AE("ISO/SAE Reserved"),
    B00AF("ISO/SAE Reserved"),
    B00B0("Driver Seat Occupant Classification Sensor \"A\" (Subfault)"),
    B00B1("Driver Seat Occupant Classification Sensor \"B\" (Subfault)"),
    B00B2("Driver Seat Occupant Classification Sensor \"C\" (Subfault)"),
    B00B3("Driver Seat Occupant Classification Sensor \"D\" (Subfault)"),
    B00B4("Driver Seat Occupant Classification Sensor \"E\" (Subfault)"),
    B00B5("Driver Seat Track Position Restraints Sensor (Subfault)"),
    B00B6("Driver Seat Recline Position Restraints Sensor (Subfault)"),
    B00B7("Driver Seat Occupant Position Sensor \"A\" (Subfault)"),
    B00B8("Driver Seat Occupant Position Sensor \"B\" (Subfault)"),
    B00B9("Driver Seat Occupant Position Sensor \"C\" (Subfault)"),
    B00BA("Driver Seat Occupant Position Sensor \"D\" (Subfault)"),
    B00BB("Driver Seat Occupant Position Sensor \"E\" (Subfault)"),
    B00BC("ISO/SAE Reserved"),
    B00BD("ISO/SAE Reserved"),
    B00BE("ISO/SAE Reserved"),
    B00BF("ISO/SAE Reserved"),
    B00C0("Passenger Seat Occupant Classification Sensor \"A\" (Subfault)"),
    B00C1("Passenger Seat Occupant Classification Sensor \"B\" (Subfault)"),
    B00C2("Passenger Seat Occupant Classification Sensor \"C\" (Subfault)"),
    B00C3("Passenger Seat Occupant Classification Sensor \"D\" (Subfault)"),
    B00C4("Passenger Seat Occupant Classification Sensor \"E\" (Subfault)"),
    B00C5("Passenger Seat Track Position Restraints Sensor (Subfault)"),
    B00C6("Passenger Seat Recline Position Restraints Sensor (Subfault)"),
    B00C7("Passenger Seat Occupant Position Sensor \"A\" (Subfault)"),
    B00C8("Passenger Seat Occupant Position Sensor \"B\" (Subfault)"),
    B00C9("Passenger Seat Occupant Position Sensor \"C\" (Subfault)"),
    B00CA("Passenger Seat Occupant Position Sensor \"D\" (Subfault)"),
    B00CB("Passenger Seat Occupant Position Sensor \"E\" (Subfault)"),
    B00CC("ISO/SAE Reserved"),
    B00CD("ISO/SAE Reserved"),
    B00CE("ISO/SAE Reserved"),
    B00CF("ISO/SAE Reserved"),
    B00D0("Driver Seatbelt Indicator (Subfault)"),
    B00D1("Passenger Seatbelt Indicator (Subfault)"),
    B00D2("Restraint System Malfunction Indicator 1 (Subfault)"),
    B00D3("Restraint System Malfunction Indicator 2 (Subfault)"),
    B00D4("Restraint System Malfunction Audible Indicator (Subfault)"),
    B00D5("Restraint System Passenger Disable Indicator (Subfault)"),
    B00D6("ISO/SAE Reserved"),
    B00D7("ISO/SAE Reserved"),
    B00D8("ISO/SAE Reserved"),
    B00D9("ISO/SAE Reserved"),
    B00DA("ISO/SAE Reserved"),
    B00DB("ISO/SAE Reserved"),
    B00DC("ISO/SAE Reserved"),
    B00DD("ISO/SAE Reserved"),
    B00DE("ISO/SAE Reserved"),
    B00DF("Passenger Restraints Disable Switch (Subfault)"),
    B00E0("Third Row Left Seatbelt Pretensioner \"B\" Deployment Control (Subfault)"),
    B00E1("Third Row Right Seatbelt Pretensioner \"B\" Deployment Control (Subfault)"),
    B00E2("Third Row Center Seatbelt Pretensioner \"B\" Deployment Control (Subfault)"),
    B00E3("Second Row Left Seatbelt Pretensioner \"C\" Deployment Control (Subfault)"),
    B00E4("Second Row Right Seatbelt Pretensioner \"C\" Deployment Control (Subfault)"),
    B00E5("Second Row Center Seatbelt Pretensioner \"C\" Deployment Control (Subfault)"),
    B00E6("Third Row Right Seatbelt Pretensioner \"C\" Deployment Control (Subfault)"),
    B00E7("Third Row Left Seatbelt Pretensioner \"C\" Deployment Control (Subfault)"),
    B00E8("Third Row Center Seatbelt Pretensioner \"C\" Deployment Control (Subfault)"),
    B00E9("ISO/SAE Reserved"),
    B0101("Left Front Impact Sensor"),
    B0500("Passenger Temperature Control \"Warmer\" Switch - Circuit Range/Performance"),
    B1000("Manufacturer Controlled DTC"),
    B1039("Audio [+] output #2 (RF) circuit open"),
    B1200("Climate Control Pushbutton Circuit Failure"),
    B1201("Fuel Sender Circuit Failure"),
    B1202("Fuel Sender Circuit Open"),
    B1203("Fuel Sender Circuit Short To Battery"),
    B1204("Fuel Sender Circuit Short To Ground"),
    B1205("EIC Switch-1 Assembly Circuit Failure"),
    B1206("EIC Switch-1 Assembly Circuit Open"),
    B1207("EIC Switch-1 Assembly Circuit Short To Battery"),
    B1208("EIC Switch-1 Assembly Circuit Short To Ground"),
    B1209("EIC Switch-2 Assembly Circuit Failure"),
    B1210("EIC Switch-2 Assembly Circuit Open"),
    B1211("EIC Switch-2 Assembly Circuit Short To Battery"),
    B1212("EIC Switch-2 Assembly Circuit Short To Ground"),
    B1213("Anti-Theft Number of Programmed Keys Is Below Minimum"),
    B1214("Running Board Lamp Circuit Failure"),
    B1215("Running Board Lamp Circuit Short to Battery"),
    B1216("Emergency & Road Side Assistance Switch Circuit Short to Ground"),
    B1217("Horn Relay Coil Circuit Failure"),
    B1218("Horn Relay Coil Circuit Short to Vbatt"),
    B1219("Fuel Tank Pressure Sensor Circuit Failure"),
    B1220("Fuel Tank Pressure Sensor Circuit Open"),
    B1222("Fuel Temperature Sensor #1 Circuit Failure"),
    B1223("Fuel Temperature Sensor #1 Circuit Open"),
    B1224("Fuel Temperature Sensor #1 Circuit Short to Battery"),
    B1225("Fuel Temperature Sensor #1 Circuit Short to Ground"),
    B1226("Fuel Temperature Sensor #2 Circuit Failure"),
    B1227("Fuel Temperature Sensor #2 Circuit Open"),
    B1228("Fuel Temperature Sensor #2 Circuit Short to Battery"),
    B1229("Fuel Temperature Sensor #2 Circuit Short to Ground"),
    B1231("Longitudinal Acceleration Threshold Exceeded"),
    B1232("See Manufacturer"),
    B1233("Glass Break Sensor Failure"),
    B1234("Mirror Switch Invalid Code"),
    B1235("Window Feedback Failure"),
    B1236("Window Feedback Loss of Signal"),
    B1237("Window Feedback Out of Range"),
    B1238("Over Temperature Fault"),
    B1239("Air Flow Blend Door Driver Circuit Failure"),
    B1240("Wiper Washer Rear Pump Relay Circuit Failure"),
    B1241("Wiper Washer Rear Pump Relay Circuit Short to Battery"),
    B1242("Air Flow Recirculation Door Driver Circuit Failure"),
    B1243("Express Window Down Switch Circuit Short to Battery"),
    B1244("Wiper Rear Motor Run Relay Circuit Failure"),
    B1245("Wiper Rear Motor Run Relay Circuit Short to Battery"),
    B1246("Dim Panel Potentiometer Switch Circuit Failure"),
    B1247("Panel Dim Switch Circuit Open"),
    B1249("Blend Door Failure"),
    B1250("Air Temperature Internal Sensor Circuit Failure"),
    B1251("Air Temperature Internal Sensor Circuit Open"),
    B1252("Air Temperature Internal Sensor Circuit Short To Battery"),
    B1253("Air Temperature Internal Sensor Circuit Short To Ground"),
    B1254("Air Temperature External Sensor Circuit Failure"),
    B1255("Air Temperature External Sensor Circuit Open"),
    B1256("Air Temperature External Sensor Circuit Short To Battery"),
    B1257("Air Temperature External Sensor Circuit Short To Ground"),
    B1258("Solar Radiation Sensor Circuit Failure"),
    B1259("Solar Radiation Sensor Circuit Open"),
    B1260("Solar Radiation Sensor Circuit Short To Battery"),
    B1261("Solar Radiation Sensor Circuit Short To Ground"),
    B1262("Servo Motor Defrost Circuit Failure"),
    B1263("Servo Motor Vent Circuit Failure"),
    B1264("Servo Motor Foot Circuit Failure"),
    B1265("Servo Motor Coolair Bypass Circuit Failure"),
    B1266("Servo Motor Airintake Left Circuit Failure"),
    B1267("Servo Motor Airintake Right Circuit Failure"),
    B1268("Servo Motor Potentiometer Defrost Circuit Failure"),
    B1269("Servo Motor Potentiometer Defrost Circuit Open"),
    B1270("Servo Motor Potentiometer Defrost Circuit Short To Battery"),
    B1271("Servo Motor Potentiometer Defrost Circuit Short To Ground"),
    B1272("Servo Motor Potentiometer Vent Circuit Failure"),
    B1273("Servo Motor Potentiometer Vent Circuit Open"),
    B1274("Servo Motor Potentiometer Vent Circuit Short To Battery"),
    B1275("Servo Motor Potentiometer Vent Circuit Short To Ground"),
    B1276("Servo Motor Potentiometer Foot Circuit Failure"),
    B1277("Servo Motor Potentiometer Foot Circuit Open"),
    B1278("Servo Motor Potentiometer Foot Circuit Short To Battery"),
    B1279("Servo Motor Potentiometer Foot Circuit Short To Ground"),
    B1280("Servo Motor Potentiometer Coolair Circuit Failure"),
    B1281("Servo Motor Potentiometer Coolair Circuit Open"),
    B1282("Servo Motor Potentiometer Coolair Circuit Short To Battery"),
    B1283("Servo Motor Potentiometer Coolair Circuit Short To Ground"),
    B1284("Servo Motor Potentiometer Airintake Left Circuit Failure"),
    B1285("Servo Motor Potentiometer Airintake Left Circuit Open"),
    B1286("Servo Motor Potentiometer Airintake Left Circuit Short To Battery"),
    B1287("Servo Motor Potentiometer Airintake Left Circuit Short To Ground"),
    B1288("Servo Motor Potentiometer Airintake Right Circuit Failure"),
    B1289("Servo Motor Potentiometer Airintake Right Circuit Open"),
    B1290("Servo Motor Potentiometer Airintake Right Circuit Short To Battery"),
    B1291("Servo Motor Potentiometer Airintake Right Circuit Short To Ground"),
    B1292("Battery Power Relay Circuit Failure"),
    B1293("Battery Power Relay Circuit Open"),
    B1294("Battery Power Relay Circuit Short To Battery"),
    B1295("Battery Power Relay Circuit Short To Ground"),
    B1296("Power Supply Sensor Circuit Failure"),
    B1297("Power Supply Sensor Circuit Open"),
    B1298("Power Supply Sensor Circuit Short To Battery"),
    B1299("Power Supply Sensor Circuit Short To Ground"),
    B1300("Power Door Lock Circuit Failure"),
    B1301("Power Door Lock Circuit Open"),
    B1302("Accessory Delay Relay Coil Circuit Failure"),
    B1303("Accessory Delay Relay Coil Circuit Open"),
    B1304("Accessory Delay Relay Coil Circuit Short To Battery"),
    B1305("Accessory Delay Relay Coil Circuit Short To Ground"),
    B1306("Oil Level Switch Circuit Open"),
    B1307("Oil Level Switch Circuit Short To Battery"),
    B1308("Oil Level Switch Circuit Short To Ground"),
    B1309("Power Door Lock Circuit Short To Ground"),
    B1310("Power Door Unlock Circuit Failure"),
    B1311("Power Door Unlock Circuit Open"),
    B1312("Lamp Headlamp Input Circuit Short To Battery"),
    B1313("Battery Saver Relay Coil Circuit Failure"),
    B1314("Battery Saver Relay Coil Circuit Open"),
    B1315("Battery Saver Relay Coil Circuit Short To Battery"),
    B1316("Battery Saver Relay Coil Circuit Short To Ground"),
    B1317("Battery Voltage High"),
    B1318("Battery Voltage Low"),
    B1319("Driver Door Ajar Circuit Failure"),
    B1320("Driver Door Ajar Circuit Open"),
    B1321("Driver Door Ajar Circuit Short To Battery"),
    B1322("Driver Door Ajar Circuit Short To Ground"),
    B1323("Door Ajar Lamp Circuit Failure"),
    B1324("Door Ajar Lamp Circuit Open"),
    B1325("Door Ajar Lamp Circuit Short To Battery"),
    B1326("Door Ajar Lamp Circuit Short To Ground"),
    B1327("Passenger Door Ajar Circuit Failure"),
    B1328("Passenger Door Ajar Circuit Open"),
    B1329("Passenger Door Ajar Circuit Short To Battery"),
    B1330("Passenger Door Ajar Circuit Short To Ground"),
    B1331("Decklid Ajar Rear Door Circuit Failure"),
    B1332("Decklid Ajar Rear Door Circuit Open"),
    B1333("Decklid Ajar Rear Door Circuit Short To Battery"),
    B1334("Decklid Ajar Rear Door Circuit Short To Ground"),
    B1335("Door Ajar RR Circuit Failure"),
    B1336("Door Ajar RR Circuit Open"),
    B1337("Door Ajar RR Circuit Short To Battery"),
    B1338("Door Ajar RR Circuit Short To Ground"),
    B1339("Chime Input Request Circuit Short To Battery"),
    B1340("Chime Input Request Circuit Short To Ground"),
    B1341("Power Door Unlock Circuit Short To Ground"),
    B1342("ECU Is Defective"),
    B1343("Heated Backlite Input Circuit Failure"),
    B1344("Heated Backlite Input Circuit Open"),
    B1345("Heated Backlite Input Circuit Short To Ground"),
    B1346("Heated Backlite Input Circuit Short To Battery"),
    B1347("Heated Backlite Relay Circuit Failure"),
    B1348("Heated Backlite Relay Circuit Open"),
    B1349("Heated Backlite Relay Short To Battery"),
    B1350("Heated Backlite Relay Short To Ground"),
    B1351("Ignition Key-In Circuit Short To Battery"),
    B1352("Ignition Key-In Circuit Failure"),
    B1353("Ignition Key-In Circuit Open"),
    B1354("Ignition Key-In Circuit Short To Ground"),
    B1355("Ignition Run Circuit Failure"),
    B1356("Ignition Run Circuit Open"),
    B1357("Ignition Run Circuit Short To Battery"),
    B1358("Ignition Run Circuit Short To Ground"),
    B1359("Ignition Run/Acc Circuit Failure"),
    B1360("Ignition Run/Acc Circuit Open"),
    B1361("Ignition Run/Acc Circuit Short To Battery"),
    B1362("Ignition Run/Acc Circuit Short To Ground"),
    B1363("Ignition Start Circuit Failure"),
    B1364("Ignition Start Circuit Open"),
    B1365("Ignition Start Circuit Short To Battery"),
    B1366("Ignition Start Circuit Short To Ground"),
    B1367("Ignition Tach Circuit Failure"),
    B1368("Ignition Tach Circuit Open"),
    B1369("Ignition Tach Circuit Short To Battery"),
    B1370("Ignition Tach Circuit Short To Ground"),
    B1371("Illuminated Entry Relay Circuit Failure"),
    B1372("Illuminated Entry Relay Circuit Open"),
    B1373("Illuminated Entry Relay Short To Battery"),
    B1374("Illuminated Entry Relay Short To Ground"),
    B1375("Oil Change Lamp Circuit Open"),
    B1376("Oil Change Lamp Circuit Short To Battery"),
    B1377("Oil Change Lamp Circuit Failure"),
    B1378("Oil Change Lamp Circuit Short To Ground"),
    B1379("Oil Change Reset Button Circuit Short To Ground"),
    B1380("Oil Change Reset Button Circuit Failure"),
    B1381("Oil Change Reset Button Circuit Open"),
    B1382("Oil Change Reset Button Circuit Short To Battery"),
    B1383("Oil Level Lamp Circuit Short To Battery"),
    B1384("Oil Level Lamp Circuit Failure"),
    B1385("Oil Level Lamp Circuit Open"),
    B1386("Oil Level Lamp Circuit Short To Ground"),
    B1387("Oil Temperature Sensor Circuit Open"),
    B1388("Oil Temperature Sensor Circuit Short To Battery"),
    B1389("Oil Temperature Sensor Circuit Failure"),
    B1390("Oil Temperature Sensor Circuit Short To Ground"),
    B1391("Oil Level Switch Circuit Failure"),
    B1392("Power Door Memory Lock Relay Circuit Failure"),
    B1393("Power Door Memory Lock Relay Circuit Open"),
    B1394("Power Door Memory Lock Relay Circuit Short To Battery"),
    B1395("Power Door Memory Lock Relay Circuit Short To Ground"),
    B1396("Power Door Lock Circuit Short To Battery"),
    B1397("Power Door Unlock Circuit Short To Battery"),
    B1398("Driver Power Window One Touch Window Relay Circuit Failure"),
    B1399("Driver Power Window One Touch Window Relay Circuit Open"),
    B1400("Driver Power Window One Touch Window Relay Circuit Short To Battery"),
    B1401("Driver Power Window One Touch Window Relay Circuit Short To Ground"),
    B1402("Driver Power Window Down Switch Circuit Failure"),
    B1403("Driver Power Window Up Switch Circuit Failure"),
    B1404("Driver Power Window Down Circuit Open"),
    B1405("Driver Power Window Down Circuit Short To Battery"),
    B1406("Driver Power Window Down Circuit Short To Ground"),
    B1407("Driver Power Window Up Circuit Open"),
    B1408("Driver Power Window Up Circuit Short To Battery"),
    B1409("Driver Power Window Up Circuit Short To Ground"),
    B1410("Driver Power Window Motor Circuit Failure"),
    B1411("Driver Power Window Motor Circuit Open"),
    B1412("Driver Power Window Motor Circuit Short To Battery"),
    B1413("Driver Power Window Motor Circuit Short To Ground"),
    B1414("Power Window LR Motor Circuit Failure"),
    B1415("Power Window LR Motor Circuit Open"),
    B1416("Power Window LR Motor Circuit Short To Battery"),
    B1417("Power Window LR Motor Circuit Short To Ground"),
    B1418("Passenger Power Window Motor Circuit Failure"),
    B1419("Passenger Power Window Motor Circuit Open"),
    B1420("Passenger Power Window Motor Circuit Short To Battery"),
    B1421("Passenger Power Window Motor Circuit Short To Ground"),
    B1422("Power Window RR Motor Circuit Failure"),
    B1423("Power Window RR Motor Circuit Open"),
    B1424("Power Window RR Motor Circuit Short To Battery"),
    B1425("Power Window RR Motor Circuit Short To Ground"),
    B1426("Lamp Seat Belt Circuit Short To Battery"),
    B1427("Lamp Seat Belt Circuit Open"),
    B1428("Lamp Seat Belt Circuit Failure"),
    B1429("Lamp Seat Belt Circuit Short To Ground"),
    B1430("Seat Belt Switch Circuit Short To Ground"),
    B1431("Wiper Brake/Run Relay Circuit Failure"),
    B1432("Wiper Brake/Run Relay Circuit Short To Battery"),
    B1433("Wiper Brake/Run Relay Circuit Short To Ground"),
    B1434("Wiper Hi/Low Speed Relay Coil Circuit Failure"),
    B1435("Wiper Hi/Low Speed Relay Coil Circuit Open"),
    B1436("Wiper Hi/Low Speed Relay Coil Circuit Short To Battery"),
    B1437("Wiper Hi/Low Speed Relay Coil Circuit Short To Ground"),
    B1438("Wiper Mode Select Switch Circuit Failure"),
    B1439("Wiper Mode Select Switch Circuit Open"),
    B1440("Wiper Mode Select Switch Circuit Short To Battery"),
    B1441("Wiper Mode Select Switch Circuit Short To Ground"),
    B1442("Door Handle Switch Circuit Failure"),
    B1443("Door Handle Switch Circuit Open"),
    B1444("Door Handle Switch Circuit Short To Battery"),
    B1445("Door Handle Switch Circuit Short To Ground"),
    B1446("Wiper Park Sense Circuit Failure"),
    B1447("Wiper Park Sense Circuit Open"),
    B1448("Wiper Park Sense Circuit Short To Battery"),
    B1449("Wiper Park Sense Circuit Short To Ground"),
    B1450("Wiper Wash/Delay Switch Circuit Failure"),
    B1451("Wiper Wash/Delay Switch Circuit Open"),
    B1452("Wiper Wash/Delay Switch Circuit Short To Battery"),
    B1453("Wiper Wash/Delay Switch Circuit Short To Ground"),
    B1454("Wiper Washer Fluid Lamp Circuit Failure"),
    B1455("Wiper Washer Fluid Lamp Circuit Open"),
    B1456("Wiper Washer Fluid Lamp Circuit Short To Battery"),
    B1457("Wiper Washer Fluid Lamp Circuit Short To Ground"),
    B1458("Wiper Washer Pump Motor Relay Circuit Failure"),
    B1459("Wiper Washer Pump Motor Relay Coil Circuit Open"),
    B1460("Wiper Washer Pump Motor Relay Coil Circuit Short To Battery"),
    B1461("Wiper Washer Pump Motor Relay Coil Circuit Short To Ground"),
    B1462("Seat Belt Switch Circuit Failure"),
    B1463("Seat Belt Switch Circuit Open"),
    B1464("Seat Belt Switch Circuit Short To Battery"),
    B1465("Wiper Brake/Run Relay Circuit Open"),
    B1466("Wiper Hi/Low Speed Not Switching"),
    B1467("Wiper Hi/Low Speed Circuit Motor Short To Battery"),
    B1468("Chime Input Request Circuit Failure"),
    B1469("Chime Input Request Circuit Open"),
    B1470("Lamp Headlamp Input Circuit Failure"),
    B1471("Lamp Headlamp Input Circuit Open"),
    B1472("Lamp Headlamp Input Circuit Short To Ground"),
    B1473("Wiper Low Speed Circuit Motor Failure"),
    B1474("Battery Saver Power Relay Circuit Short To Battery"),
    B1475("Accessory Delay Relay Contact Short To Battery"),
    B1476("Wiper High Speed Circuit Motor Failure"),
    B1477("Wiper Hi/Low Circuit Motor Short To Ground"),
    B1478("Power Window One Touch Up/Down Activated Simultaneously"),
    B1479("Wiper Washer Fluid Level Sensor Circuit Failure"),
    B1480("Wiper Washer Fluid Level Sensor Circuit Open"),
    B1481("Wiper Washer Fluid Level Sensor Circuit Short To Battery"),
    B1482("Wiper Washer Fluid Level Sensor Circuit Short To Ground"),
    B1483("Brake Pedal Input Circuit Failure"),
    B1484("Brake Pedal Input Open Circuit"),
    B1485("Brake Pedal Input Circuit Battery Short"),
    B1486("Brake Pedal Input Circuit Ground Short"),
    B1487("Door Handle Right Front Circuit Failure"),
    B1488("Door Handle Right Front Circuit Open"),
    B1489("Door Handle Right Front Short To Battery"),
    B1490("Door Handle Right Front Short To Ground"),
    B1491("Ignition Cylinder Sensor Circuit Failure"),
    B1492("Ignition Cylinder Sensor Open Circuit"),
    B1493("Ignition Cylinder Sensor Battery Short"),
    B1494("Ignition Cylinder Sensor Ground Short"),
    B1495("Decklid Punch-Out Sensor Circuit Failure"),
    B1496("Decklid Punch-Out Sensor Open Circuit"),
    B1497("Decklid Punch-Out Sensor Battery Short"),
    B1498("Decklid Punch-Out Sensor Ground Short"),
    B1499("Lamp Turn Signal Left Circuit Failure"),
    B1500("Lamp Turn Signal Left Circuit Open"),
    B1501("Lamp Turn Signal Left Circuit Short To Battery"),
    B1502("Lamp Turn Signal Left Circuit Short To Ground"),
    B1503("Lamp Turn Signal Right Circuit Failure"),
    B1504("Lamp Turn Signal Right Circuit Open"),
    B1505("Lamp Turn Signal Right Circuit Short To Battery"),
    B1506("Lamp Turn Signal Right Circuit Short To Ground"),
    B1507("Flash To Pass Switch Circuit Failure"),
    B1508("Flash To Pass Switch Circuit Open"),
    B1509("Flash To Pass Switch Circuit Short To Battery"),
    B1510("Flash To Pass Switch Circuit Short To Ground"),
    B1511("Driver Door Handle Circuit Failure"),
    B1512("Driver Door Handle Circuit Open"),
    B1513("Driver Door Handle Circuit Short To Battery"),
    B1514("Driver Door Handle Circuit Short To Ground"),
    B1515("Seat Driver Occupied Switch Circuit Failure"),
    B1516("Seat Driver Occupied Switch Circuit Open"),
    B1517("Seat Driver Occupied Switch Circuit Short To Battery"),
    B1518("Seat Driver Occupied Switch Circuit Short To Ground"),
    B1519("Hood Switch Circuit Failure"),
    B1520("Hood Switch Circuit Open"),
    B1521("Hood Switch Circuit Short To Battery"),
    B1522("Hood Switch Circuit Short To Ground"),
    B1523("Keyless Entry Circuit Failure"),
    B1524("Keyless Entry Circuit Open"),
    B1525("Keyless Entry Circuit Short To Battery"),
    B1526("Keyless Entry Circuit Short To Ground"),
    B1527("Memory Set Switch Circuit Failure"),
    B1528("Memory Set Switch Circuit Open"),
    B1529("Memory Set Switch Circuit Short To Battery"),
    B1530("Memory Set Switch Circuit Short To Ground"),
    B1531("Memory 1 Switch Circuit Failure"),
    B1532("Memory 1 Switch Circuit Open"),
    B1533("Memory 1 Switch Circuit Short To Battery"),
    B1534("Memory 1 Switch Circuit Short To Ground"),
    B1535("Memory 2 Switch Circuit Failure"),
    B1536("Memory 2 Switch Circuit Open"),
    B1537("Memory 2 Switch Circuit Short To Battery"),
    B1538("Memory 2 Switch Circuit Short To Ground"),
    B1539("Mirror Driver Switch Assembly Circuit Failure"),
    B1540("Mirror Driver Switch Assembly Circuit Open"),
    B1541("Mirror Driver Switch Assembly Circuit Short To Battery"),
    B1542("Mirror Driver Switch Assembly Circuit Short To Ground"),
    B1543("Seat Direction Switch Assembly Circuit Failure"),
    B1544("Seat Direction Switch Assembly Circuit Open"),
    B1545("Seat Direction Switch Assembly Circuit Short To Battery"),
    B1546("Seat Direction Switch Assembly Circuit Short To Ground"),
    B1547("Power Window Master Circuit Failure"),
    B1548("Power Window Master Circuit Open"),
    B1549("Power Window Master Circuit Short To Battery"),
    B1550("Power Window Master Circuit Short To Ground"),
    B1551("Decklid Release Circuit Failure"),
    B1552("Decklid Release Circuit Open"),
    B1553("Decklid Release Circuit Short To Battery"),
    B1554("Decklid Release Circuit Short To Ground"),
    B1555("Ignition Run/Start Circuit Failure"),
    B1556("Ignition Run/Start Circuit Open"),
    B1557("Ignition Run/Start Circuit Short To Battery"),
    B1558("Ignition Run/Start Circuit Short To Ground"),
    B1559("Door Lock Cylinder Circuit Failure"),
    B1560("Door Lock Cylinder Circuit Open"),
    B1561("Door Lock Cylinder Circuit Short To Battery"),
    B1562("Door Lock Cylinder Circuit Short To Ground"),
    B1563("Door Ajar Circuit Failure"),
    B1564("Door Ajar Circuit Open"),
    B1565("Door Ajar Circuit Short To Battery"),
    B1566("Door Ajar Circuit Short To Ground"),
    B1567("Lamp Headlamp High-Beam Circuit Failure"),
    B1568("Lamp Headlamp High-Beam Circuit Open"),
    B1569("Lamp Headlamp High-Beam Circuit Short To Battery"),
    B1570("Lamp Headlamp High-Beam Circuit Short To Ground"),
    B1571("Door Ajar LR Circuit Failure"),
    B1572("Door Ajar LR Circuit Open"),
    B1573("Door Ajar LR Circuit Short To Battery"),
    B1574("Door Ajar LR Circuit Short To Ground"),
    B1575("Lamp Park Input Circuit Failure"),
    B1576("Lamp Park Input Circuit Open"),
    B1577("Lamp Park Input Circuit Short To Battery"),
    B1578("Lamp Park Input Circuit Short To Ground"),
    B1579("Dim Panel Increase Input Circuit Failure"),
    B1580("Dim Panel Increase Input Circuit Open"),
    B1581("Dim Panel Increase Input Circuit Short To Battery"),
    B1582("Dim Panel Increase Input Circuit Short To Ground"),
    B1583("Dim Panel Decrease Input Circuit Failure"),
    B1584("Dim Panel Decrease Input Circuit Open"),
    B1585("Dim Panel Decrease Input Circuit Short To Battery"),
    B1586("Dim Panel Decrease Input Circuit Short To Ground"),
    B1587("Autolamp Delay Increase Circuit Failure"),
    B1588("Autolamp Delay Increase Circuit Open"),
    B1589("Autolamp Delay Increase Circuit Short To Battery"),
    B1590("Autolamp Delay Increase Circuit Short To Ground"),
    B1591("Autolamp Delay Decrease Circuit Failure"),
    B1592("Autolamp Delay Decrease Circuit Open"),
    B1593("Autolamp Delay Decrease Circuit Short To Battery"),
    B1594("Autolamp Delay Decrease Circuit Short To Ground"),
    B1595("Ignition Switch Illegal Input Code"),
    B1596("Service Continuous Codes"),
    B1600("PATS Ignition Key Transponder Signal Is Not Received"),
    B1601("PATS Received Incorrect Key-Code From Ignition Key Transponder"),
    B1602("PATS Received Invalid Format Of Key-Code From Ignition Key Transponder"),
    B1603("Lamp Anti-Theft Indicator Circuit Failure"),
    B1604("Lamp Anti-Theft Indicator Circuit Open"),
    B1605("Lamp Anti-Theft Indicator Circuit Short To Battery"),
    B1606("Lamp Anti-Theft Indicator Circuit Short To Ground"),
    B1607("Illuminated Entry Input Circuit Failure"),
    B1608("Illuminated Entry Input Open Circuit"),
    B1609("Illuminated Entry Input Short Circuit To Battery"),
    B1610("Illuminated Entry Input Short Circuit To Ground"),
    B1611("Wiper Rear Mode Select Switch Circuit Failure"),
    B1612("Wiper Rear Mode Select Switch Circuit Open"),
    B1613("Wiper Rear Mode Select Switch Circuit Short To Battery"),
    B1614("Wiper Rear Mode Select Switch Circuit Short To Ground"),
    B1615("Wiper Rear Disable Switch Circuit Failure"),
    B1616("Wiper Rear Disable Switch Circuit Open"),
    B1617("Wiper Rear Disable Switch Circuit Short To Battery"),
    B1618("Wiper Rear Disable Switch Circuit Short To Ground"),
    B1619("Wiper Rear Low Limit Input Circuit Failure"),
    B1620("Wiper Rear Low Limit Input Circuit Open"),
    B1621("Wiper Rear Low Limit Input Circuit Short To Battery"),
    B1622("Wiper Rear Low Limit Input Circuit Short To Ground"),
    B1623("Lamp Keypad Output Circuit Failure"),
    B1624("Lamp Keypad Output Open Circuit"),
    B1625("Lamp Keypad Output Short Circuit To Battery"),
    B1626("Lamp Keypad Output Short Circuit To Ground"),
    B1627("PRNDL Reverse Input Circuit Failure"),
    B1628("PRNDL Reverse Input Open Circuit"),
    B1629("PRNDL Reverse Input Short To Battery"),
    B1630("PRNDL Reverse Input Short Circuit To Ground"),
    B1631("Mirror Driver Left Circuit Failure"),
    B1632("Mirror Driver Left Circuit Open"),
    B1633("Mirror Driver Left Circuit Short To Battery"),
    B1634("Mirror Driver Left Circuit Short To Ground"),
    B1635("Mirror Driver Right Circuit Failure"),
    B1636("Mirror Driver Right Circuit Open"),
    B1637("Mirror Driver Right Circuit Short To Battery"),
    B1638("Mirror Driver Right Short To Ground"),
    B1639("Mirror Passenger Left Circuit Failure"),
    B1640("Mirror Passenger Left Circuit Open"),
    B1641("Mirror Passenger Left Circuit Short To Battery"),
    B1642("Mirror Passenger Left Circuit Short To Ground"),
    B1643("Mirror Passenger Right Circuit Failure"),
    B1644("Mirror Passenger Right Circuit Open"),
    B1645("Mirror Passenger Right Circuit Short To Battery"),
    B1646("Mirror Passenger Right Circuit Short To Ground"),
    B1647("Seat Driver Recline Forward Circuit Failure"),
    B1648("Seat Driver Recline Forward Circuit Open"),
    B1649("Seat Driver Recline Forward Circuit Short To Battery"),
    B1650("Seat Driver Recline Forward Circuit Short To Ground"),
    B1651("Seat Driver Recline Backward Circuit Failure"),
    B1652("Seat Driver Recline Backward Circuit Open"),
    B1653("Seat Driver Recline Backward Circuit Short To Battery"),
    B1654("Seat Driver Recline Backward Circuit Short To Ground"),
    B1655("Seat Driver Rear Up Circuit Failure"),
    B1656("Seat Driver Rear Up Circuit Open"),
    B1657("Seat Driver Rear Up Circuit Short To Battery"),
    B1658("Seat Driver Rear Up Circuit Short To Ground"),
    B1659("Seat Driver Front Up Circuit Failure"),
    B1660("Seat Driver Front Up Circuit Open"),
    B1661("Seat Driver Front Up Circuit Short To Battery"),
    B1662("Seat Driver Front Up Circuit Short To Ground"),
    B1663("Seat Driver Front Up/Down Motor Stalled"),
    B1664("Seat Driver Rear Up/Down Motor Stalled"),
    B1665("Seat Driver Forward/Backward Motor Stalled"),
    B1666("Seat Driver Recline Motor Stalled"),
    B1667("Mirror Driver Up/Down Motor Stalled"),
    B1668("Mirror Driver Right/Left Motor Stalled"),
    B1669("Mirror Passenger Up/Down Motor Stalled"),
    B1670("Mirror Passenger Right/Left Motor Stalled"),
    B1671("Battery Module Voltage Out Of Range"),
    B1672("Seat Driver Occupied Input Circuit Failure"),
    B1673("Seat Driver Occupied Input Circuit Open"),
    B1674("Seat Driver Occupied Input Circuit Short To Battery"),
    B1675("Seat Driver Occupied Input Circuit Short To Ground"),
    B1676("Battery Pack Voltage Out Of Range"),
    B1677("Alarm Panic Input Circuit Failure"),
    B1678("Alarm Panic Input Circuit Open"),
    B1679("Alarm Panic Input Circuit Short To Battery"),
    B1680("Alarm Panic Input Circuit Short To Ground"),
    B1681("PATS Transceiver Module Signal Is Not Received"),
    B1682("PATS Is Disabled (Check Link Between PATS And Transponder)"),
    B1683("Mirror Driver/Passenger Switch Circuit Failure"),
    B1684("Mirror Driver/Passenger Switch Circuit Open"),
    B1685("Lamp Dome Input Circuit Failure"),
    B1686("Lamp Dome Input Circuit Open"),
    B1687("Lamp Dome Input Circuit Short To Battery"),
    B1688("Lamp Dome Input Circuit Short To Ground"),
    B1689("Autolamp Delay Circuit Failure"),
    B1690("Autolamp Delay Circuit Open"),
    B1691("Autolamp Delay Circuit Short To Battery"),
    B1692("Autolamp Delay Circuit Short To Ground"),
    B1693("Autolamp On Circuit Failure"),
    B1694("Autolamp On Circuit Open"),
    B1695("Autolamp On Circuit Short To Battery"),
    B1696("Autolamp On Circuit Short To Ground"),
    B1697("Mirror Driver/Passenger Switch Circuit Short To Battery"),
    B1698("Mirror Driver/Passenger Switch Circuit Short To Ground"),
    B1701("Seat Driver Recline Forward Switch Circuit Failure"),
    B1702("Seat Driver Recline Forward Switch Circuit Open"),
    B1703("Seat Driver Recline Forward Switch Circuit Short To Battery"),
    B1704("Seat Driver Recline Forward Switch Circuit Short To Ground"),
    B1705("Seat Driver Recline Rearward Switch Circuit Failure"),
    B1706("Seat Driver Recline Rearward Switch Circuit Open"),
    B1707("Seat Driver Recline Rearward Switch Circuit Short To Battery"),
    B1708("Seat Driver Recline Rearward Switch Circuit Short To Ground"),
    B1709("Seat Driver Front Up Switch Circuit Failure"),
    B1710("Seat Driver Front Up Switch Circuit Open"),
    B1711("Seat Driver Front Up Switch Circuit Short To Battery"),
    B1712("Seat Driver Front Up Switch Circuit Short To Ground"),
    B1713("Seat Driver Front Down Switch Circuit Failure"),
    B1714("Seat Driver Front Down Switch Circuit Open"),
    B1715("Seat Driver Front Down Switch Circuit Short To Battery"),
    B1716("Seat Driver Front Down Switch Circuit Short To Ground"),
    B1717("Seat Driver Forward Switch Circuit Failure"),
    B1718("Seat Driver Forward Switch Circuit Open"),
    B1719("Seat Driver Forward Switch Circuit Short To Battery"),
    B1720("Seat Driver Forward Switch Circuit Short To Ground"),
    B1721("Seat Driver Rearward Switch Circuit Failure"),
    B1722("Seat Driver Rearward Switch Circuit Open"),
    B1723("Seat Driver Rearward Switch Circuit Short To Battery"),
    B1724("Seat Driver Rearward Switch Circuit Short To Ground"),
    B1725("Seat Driver Rear Up Switch Circuit Failure"),
    B1726("Seat Driver Rear Up Switch Circuit Open"),
    B1727("Seat Driver Rear Up Switch Circuit Short To Battery"),
    B1728("Seat Driver Rear Up Switch Circuit Short To Ground"),
    B1729("Seat Driver Rear Down Switch Circuit Failure"),
    B1730("Seat Driver Rear Down Switch Circuit Open"),
    B1731("Seat Driver Rear Down Switch Circuit Short To Battery"),
    B1732("Seat Driver Rear Down Switch Circuit Short To Ground"),
    B1733("Mirror Driver Vertical Switch Circuit Failure"),
    B1734("Mirror Driver Vertical Switch Circuit Open"),
    B1735("Mirror Driver Vertical Switch Circuit Short To Battery"),
    B1736("Mirror Driver Vertical Switch Circuit Short To Ground"),
    B1737("Mirror Driver Horizontal Switch Circuit Failure"),
    B1738("Mirror Driver Horizontal Switch Circuit Open"),
    B1739("Mirror Driver Horizontal Switch Circuit Short To Battery"),
    B1740("Mirror Driver Horizontal Switch Circuit Short To Ground"),
    B1741("Mirror Passenger Vertical Switch Circuit Failure"),
    B1742("Mirror Passenger Vertical Switch Circuit Open"),
    B1743("Mirror Passenger Vertical Switch Circuit Short To Battery"),
    B1744("Mirror Passenger Vertical Switch Circuit Short To Ground"),
    B1745("Mirror Passenger Horizontal Switch Circuit Failure"),
    B1746("Mirror Passenger Horizontal Switch Circuit Open"),
    B1747("Mirror Passenger Horizontal Switch Circuit Short To Battery"),
    B1748("Mirror Passenger Horizontal Switch Circuit Short To Ground"),
    B1749("Park/Neutral Switch Circuit Failure"),
    B1750("Park/Neutral Switch Circuit Open"),
    B1751("Park/Neutral Switch Circuit Short To Battery"),
    B1752("Park/Neutral Switch Circuit Short To Ground"),
    B1753("Hazard Flash Output Circuit Failure"),
    B1754("Hazard Flash Output Circuit Open"),
    B1755("Hazard Flash Output Circuit Short Battery"),
    B1756("Hazard Flash Output Circuit Short To Ground"),
    B1757("Seat Driver Rear Down Circuit Failure"),
    B1758("Seat Driver Rear Down Circuit Open"),
    B1759("Seat Driver Rear Down Circuit Short To Battery"),
    B1760("Seat Driver Rear Down Circuit Short To Ground"),
    B1761("Seat Driver Front Down Circuit Failure"),
    B1762("Seat Driver Front Down Circuit Open"),
    B1763("Seat Driver Front Down Circuit Short To Battery"),
    B1764("Seat Driver Front Down Circuit Short To Ground"),
    B1765("Seat Driver Forward Circuit Failure"),
    B1766("Seat Driver Forward Circuit Open"),
    B1767("Seat Driver Forward Circuit Short To Battery"),
    B1768("Seat Driver Forward Circuit Short To Ground"),
    B1769("Seat Driver Backward Circuit Failure"),
    B1770("Seat Driver Backward Circuit Open"),
    B1771("Seat Driver Backward Circuit Short To Battery"),
    B1772("Seat Driver Backward Circuit Short To Ground"),
    B1773("Mirror Driver Up Circuit Failure"),
    B1774("Mirror Driver Up Circuit Open"),
    B1775("Mirror Driver Up Circuit Short To Battery"),
    B1776("Mirror Driver Up Circuit Short To Ground"),
    B1778("Mirror Driver Down Circuit Failure"),
    B1779("Mirror Driver Down Circuit Open"),
    B1780("Mirror Driver Down Circuit Short To Battery"),
    B1781("Mirror Driver Down Short To Ground"),
    B1782("Mirror Passenger Up Circuit Failure"),
    B1783("Mirror Passenger Up Circuit Open"),
    B1784("Mirror Passenger Up Circuit Short To Battery"),
    B1785("Mirror Passenger Up Circuit Short To Ground"),
    B1786("Mirror Passenger Down Circuit Failure"),
    B1787("Mirror Passenger Down Circuit Open"),
    B1788("Mirror Passenger Down Circuit Short To Battery"),
    B1789("Mirror Passenger Down Circuit Short To Ground"),
    B1790("Autolamp Sensor Input Circuit Failure"),
    B1791("Autolamp Sensor Input Circuit Open"),
    B1792("Autolamp Sensor Input Circuit Short To Battery"),
    B1793("Autolamp Sensor Input Circuit Short To Ground"),
    B1794("Lamp Headlamp Low-Beam Circuit Failure"),
    B1795("Lamp Headlamp Low-Beam Circuit Open"),
    B1796("Lamp Headlamp Low-Beam Circuit Short To Battery"),
    B1797("Lamp Headlamp Low-Beam Circuit Short To Ground"),
    B1798("Lamp Turn Signal Front Output Circuit Failure"),
    B1799("Lamp Turn Signal Front Output Circuit Open"),
    B1800("Lamp Turn Signal Front Output Circuit Short To Battery"),
    B1801("Lamp Turn Signal Front Output Circuit Short To Ground"),
    B1802("Lamp Turn Signal Rear Output Circuit Failure"),
    B1803("Lamp Turn Signal Rear Output Circuit Open"),
    B1804("Lamp Turn Signal Rear Output Circuit Short To Battery"),
    B1805("Lamp Turn Signal Rear Output Circuit Short To Ground"),
    B1806("Lamp Tail Output Circuit Failure"),
    B1807("Lamp Tail Output Circuit Open"),
    B1808("Lamp Tail Output Circuit Short To Battery"),
    B1809("Lamp Tail Output Circuit Short To Ground"),
    B1810("Lamp Backup Switch Input Circuit Failure"),
    B1811("Lamp Backup Switch Input Circuit Open"),
    B1812("Lamp Backup Switch Input Circuit Short To Battery"),
    B1813("Lamp Backup Switch Input Circuit Short To Ground"),
    B1814("Wiper Rear Motor Down Relay Coil Circuit Failure"),
    B1815("Wiper Rear Motor Down Relay Coil Circuit Open"),
    B1816("Wiper Rear Motor Down Relay Coil Circuit Short To Battery"),
    B1817("Wiper Rear Motor Down Relay Coil Circuit Short To Ground"),
    B1818("Wiper Rear Motor Up Relay Coil Circuit Failure"),
    B1819("Wiper Rear Motor Up Relay Coil Circuit Open"),
    B1820("Wiper Rear Motor Up Relay Coil Circuit Short To Battery"),
    B1821("Wiper Rear Motor Up Relay Coil Circuit Short To Ground"),
    B1822("Wiper Rear Park Sense Input Circuit Failure"),
    B1823("Wiper Rear Park Sense Input Circuit Open"),
    B1824("Wiper Rear Park Sense Input Circuit Short To Battery"),
    B1825("Wiper Rear Park Sense Input Circuit Short To Ground"),
    B1826("Wiper Rear High Limit Input Circuit Failure"),
    B1827("Wiper Rear High Limit Input Circuit Open"),
    B1828("Wiper Rear High Limit Input Circuit Short To Battery"),
    B1829("Wiper Rear High Limit Input Circuit Short To Ground"),
    B1830("Door Unlock Disarm Switch Circuit Failure"),
    B1831("Door Unlock Disarm Switch Circuit Open"),
    B1832("Door Unlock Disarm Switch Circuit Short To Battery"),
    B1833("Door Unlock Disarm Switch Circuit Short To Ground"),
    B1834("Door Unlock Disarm Output Circuit Failure"),
    B1835("Door Unlock Disarm Output Circuit Open"),
    B1836("Door Unlock Disarm Output Circuit Short To Battery"),
    B1837("Door Unlock Disarm Output Circuit Short To Ground"),
    B1838("Battery Saver Power Relay Circuit Failure"),
    B1839("Wiper Rear Motor Circuit Failure"),
    B1840("Wiper Front Power Circuit Failure"),
    B1841("Wiper Front Power Circuit Open"),
    B1842("Wiper Front Power Circuit Short To Battery"),
    B1843("Wiper Front Power Circuit Short To Ground"),
    B1844("Phone Handset Circuit Failure"),
    B1845("Ignition Tamper Circuit Failure"),
    B1846("Ignition Tamper Circuit Open"),
    B1847("Ignition Tamper Circuit Short To Battery"),
    B1848("Ignition Tamper Circuit Short To Ground"),
    B1849("Climate Control Temperature Differential Circuit Failure"),
    B1850("Climate Control Temperature Differential Circuit Open"),
    B1851("Climate Control Temperature Differential Circuit Short To Battery"),
    B1852("Climate Control Temperature Differential Circuit Short To Ground"),
    B1853("Climate Control Air Temperature Internal Sensor Motor Circuit Failure"),
    B1854("Climate Control Air Temperature Internal Sensor Motor Circuit Open"),
    B1855("Climate Control Air Temperature Internal Sensor Motor Circuit Short To Battery"),
    B1856("Climate Control Air Temperature Internal Sensor Motor Circuit Short To Ground"),
    B1857("Climate Control On/Off Switch Circuit Failure"),
    B1858("Climate Control A/C Pressure Switch Circuit Failure"),
    B1859("Climate Control A/C Pressure Switch Circuit Open"),
    B1860("Climate Control A/C Pressure Switch Circuit Short To Battery"),
    B1861("Climate Control A/C Pressure Switch Circuit Short To Ground"),
    B1862("Climate Control A/C Lock Sensor Failure"),
    B1863("Ground ECU Circuit Open"),
    B1864("Battery Power Supply ECU Circuit Failure"),
    B1865("Battery Power Supply ECU Circuit Open"),
    B1866("Battery Power Supply ECU Circuit Short To Battery"),
    B1867("Battery Power Supply ECU Circuit Short To Ground"),
    B1868("Lamp Air Bag Warning Indicator Circuit Failure"),
    B1869("Lamp Air Bag Warning Indicator Circuit Open"),
    B1870("Lamp Air Bag Warning Indicator Circuit Short To Battery"),
    B1871("Passenger Air Bag Disable Module Fault"),
    B1872("Turn Signal / Hazard Power Feed Circuit Short To Battery"),
    B1873("Turn Signal / Hazard Power Feed Circuit Short To Ground"),
    B1874("Cellular Phone Handset Not Present"),
    B1875("Turn Signal / Hazard Switch Signal Circuit Failure"),
    B1876("Seatbelt Driver Pretensioner Circuit Failure"),
    B1877("Seatbelt Driver Pretensioner Circuit Open"),
    B1878("Seatbelt Driver Pretensioner Circuit Short to Battery"),
    B1879("Seatbelt Driver Pretensioner Circuit Short to Ground"),
    B1880("Seatbelt Passenger Pretensioner Circuit Failure"),
    B1881("Seatbelt Passenger Pretensioner Circuit Open"),
    B1882("Seatbelt Passenger Pretensioner Circuit Short to Battery"),
    B1883("Seatbelt Passenger Pretensioner Circuit Short to Ground"),
    B1884("PAD Warning Lamp Inoperative"),
    B1885("Seatbelt Driver Pretensioner Circuit Resistance Low on Squib"),
    B1886("Seatbelt Passenger Pretensioner Circuit Resistance Low on Squib"),
    B1887("Air Bag Driver Circuit Resistance Low or Shorted Together"),
    B1888("Air Bag Passenger Circuit Resistance Low or Shorted Together"),
    B1889("Passenger Airbag Disable Module Sensor Obstructed"),
    B1890("PAD Warning Lamp Circuit Short to Battery"),
    B1891("Air Bag Tone Warning Indicator Circuit Short to Battery"),
    B1892("Air Bag Tone Warning Indicator Circuit Failure"),
    B1893("GPS Antenna Open Circuit"),
    B1894("Wiper Rear Motor Speed Sense Circuit Failure"),
    B1897("Horn Switch Circuit Failure"),
    B1898("Chime Input #2 Circuit Short to Ground"),
    B1899("Microphone Input Signal Circuit Open"),
    B1900("DC/DC CONVERTER"),
    B1901("DC/DC CONVERTER"),
    B1902("DC/DC CONVERTER"),
    B1903("DC/DC CONVERTER"),
    B1904("DC/DC CONVERTER"),
    B1905("Air Bag Crash Sensor #2 Feed/Return Circuit Short To Battery"),
    B1906("Air Bag Crash Sensor #2 Feed/Return Circuit Short To Ground"),
    B1907("Air Bag Crash Sensor #2 Ground Circuit Failure"),
    B1908("Air Bag Crash Sensor #2 Ground Circuit Short To Battery"),
    B1909("Air Bag Crash Sensor #2 Ground Circuit Short To Ground"),
    B1910("SUB BATTERY RELAY"),
    B1911("SUB BATTERY RELAY"),
    B1912("Air Bag Diagnostic Monitor Ground Circuit Short To Ground"),
    B1913("Air Bag Driver/Passenger Circuit Short To Ground"),
    B1914("Air Bag Crash Sensors #1 / #2 Circuit Short To Ground"),
    B1915("Air Bag Driver Circuit Failure"),
    B1916("Air Bag Driver Circuit Short To Battery"),
    B1917("Air Bag Memory Clear Circuit Failure"),
    B1918("Air Bag Memory Clear Circuit Open"),
    B1919("Air Bag Memory Clear Circuit Short To Battery"),
    B1920("Air Bag Passenger Circuit Failure"),
    B1921("Air Bag Diagnostic Monitor Ground Circuit Open"),
    B1922("Air Bag Safing Sensor Output Circuit Short To Battery"),
    B1923("Air Bag Memory Clear Circuit Short To Ground"),
    B1924("Air Bag Internal Diagnostic Monitor Fault or System Disarm Fault"),
    B1925("Air Bag Passenger Circuit Short To Battery"),
    B1926("Air Bag Passenger Pressure Switch Circuit Failure"),
    B1927("Passenger Side Airbag Fault"),
    B1928("Air Bag Safing Sensor Output Circuit Failure"),
    B1929("Air Bag Safing Sensor Output Circuit Open"),
    B1930("Air Bag Safing Sensor Output Circuit Short To Ground"),
    B1931("Air Bag Crash Sensor #1 Feed/Return Circuit Failure"),
    B1932("Air Bag Driver Circuit Open"),
    B1933("Air Bag Passenger Circuit Open"),
    B1934("Air Bag Driver Inflator Circuit Resistance Low on Squib"),
    B1935("Air Bag Passenger Inflator Circuit Resistance Low on Squib"),
    B1936("Air Bag Driver Circuit Short To Ground"),
    B1937("Air Bag Passenger Pressure Switch Circuit Open"),
    B1938("Air Bag Passenger Circuit Short To Ground"),
    B1939("Air Bag Passenger Pressure Switch Circuit Short To Ground"),
    B1941("Air Bag Crash Sensor #1 Feed/Return Circuit Open"),
    B1942("Air Bag Crash Sensor #2 Feed/Return Circuit Open"),
    B1943("Air Bag Crash Sensor #1 Ground Circuit Short To Ground"),
    B1944("Air Bag Crash Sensor #1 Ground Circuit Open"),
    B1945("Air Bag Crash Sensor #2 Ground Circuit Open"),
    B1946("Climate Control A/C Post Evaporator Sensor Circuit Failure"),
    B1947("Climate Control A/C Post Evaporator Sensor Circuit Short To Ground"),
    B1948("Climate Control Water Temperature Sensor Circuit Failure"),
    B1949("Climate Control Water Temperature Sensor Circuit Short To Ground"),
    B1950("Seat Rear Up/Down Potentiometer Feedback Circuit Failure"),
    B1951("Seat Rear Up/Down Potentiometer Feedback Circuit Open"),
    B1952("Seat Rear Up/Down Potentiometer Feedback Circuit Short To Battery"),
    B1953("Seat Rear Up/Down Potentiometer Feedback Circuit Short To Ground"),
    B1954("Seat Front Up/Down Potentiometer Feedback Circuit Failure"),
    B1955("Seat Front Up/Down Potentiometer Feedback Circuit Open"),
    B1956("Seat Front Up/Down Potentiometer Feedback Circuit Short To Battery"),
    B1957("Seat Front Up/Down Potentiometer Feedback Circuit Short To Ground"),
    B1958("Seat Recline Forward/Backward Potentiometer Feedback Circuit Failure"),
    B1959("Seat Recline Forward/Backward Potentiometer Feedback Circuit Open"),
    B1960("Seat Recline Forward/Backward Potentiometer Feedback Circuit Short To Battery"),
    B1961("Seat Recline Forward/Backward Potentiometer Feedback Circuit Short To Ground"),
    B1962("Seat Horizontal Forward/Rearward Potentiometer Feedback Circuit Failure"),
    B1963("Seat Horizontal Forward/Rearward Potentiometer Feedback Circuit Open"),
    B1964("Seat Horizontal Forward/Rearward Potentiometer Feedback Circuit Short To Battery"),
    B1965("Seat Horizontal Forward/Rearward Potentiometer Feedback Circuit Short To Ground"),
    B1966("A/C Post Heater Sensor Circuit Failure"),
    B1967("A/C Post Heater Sensor Circuit Short To Ground"),
    B1968("A/C Water Pump Detection Circuit Failure"),
    B1969("A/C Clutch Magnetic Control Circuit Failure"),
    B1970("Passenger Seatback Forward Switch Circuit Short to Ground"),
    B1971("Passenger Seatback Rearward Switch Circuit Short to Ground"),
    B1972("Passenger Rear Seat Up Switch Circuit Short to Battery"),
    B1973("Passenger Rear Seat Down Switch Circuit Short to Battery"),
    B1979("Passenger Seat Rearward Switch Circuit Short to Battery"),
    B1980("Bulb - Outage Condition Detected"),
    B1981("Memory Off Switch Circuit Short to Battery"),
    B1984("Seat Switch Lumbar Inflate Circuit Failure"),
    B1985("Seat Switch Lumbar Deflate Circuit Failure"),
    B1987("Pedal Forward / Rearward Motor Stalled"),
    B1988("Pedal Position Forward Switch Circuit Short to Battery"),
    B1989("Pedal Position Rearward Switch Circuit Short to Battery"),
    B1990("Pedal Forward / Rearward Potentiometer Feedback Circuit Failure"),
    B1991("Pedal Forward / Rearward Potentiometer Feedback Circuit Short to Battery"),
    B1992("Driver Side"),
    B1993("Driver Side"),
    B1994("Driver Side"),
    B1995("Driver Side"),
    B1996("Passenger Side"),
    B1997("Passenger Side"),
    B1998("Passenger Side"),
    B1999("Passenger Side"),
    B2100("Door Driver Key Cylinder Switch Failure"),
    B2101("Head Rest Switch Circuit Failure"),
    B2102("Antenna Circuit Short to Ground"),
    B2103("Antenna Not Connected"),
    B2104("Door Passenger Key Cylinder Switch Failure"),
    B2105("Throttle Position Input Out of Range Low"),
    B2106("Throttle Position Input Out of Range High"),
    B2107("Front Wiper Motor Relay Circuit Short to Vbatt"),
    B2108("Trunk Key Cylinder Switch Failure"),
    B2109("Heated Wind Shield Relay Short to Vbatt (changed from Failure 2/6/97)"),
    B2110("Front Wiper Motor Relay Circuit Open (changed from Failure 2/6/97)"),
    B2111("All Door Lock Input Short to Ground"),
    B2112("Door Driver Set Switch Stuck Failure"),
    B2113("Heated Windshield Input Short to Ground"),
    B2114("Front Washer Input Short to Ground"),
    B2115("Rear Washer Input Short to Ground"),
    B2116("Door Driver Reset Switch Stuck Failure"),
    B2117("Driver Side"),
    B2118("Passenger Side"),
    B2119("Compressor Failure"),
    B2120("Door Passenger Set Switch Stuck Failure"),
    B2122("Driver Side Satellite Communication Circuit Short to Ground"),
    B2123("Passenger Side Satellite Communication Circuit Short to Ground"),
    B2124("Door Passenger Reset Switch Stuck Failure"),
    B2128("Central Lock Motor Failure"),
    B2129("Central Lock Feedback Failure"),
    B2130("Double Lock Timeout Failure"),
    B2131("Double Lock Feedback Failure"),
    B2132("Dimmer switch Circuit Short to Gnd"),
    B2133("Brake Motor Warning lamp Circuit Failure"),
    B2134("Brake Motor Warning lamp Circuit Short to Vbatt"),
    B2135("Park Brake Applied Warning Lamp Circuit Failure"),
    B2136("Park Brake Applied Warning Lamp Circuit Short To Battery"),
    B2139("Data Mismatch (receive data does not match what was expected)"),
    B2141("NVM Configuration Failure"),
    B2142("NVM TIC Failure"),
    B2143("NVM Memory Failure"),
    B2144("NVM Alarm Data Failure"),
    B2145("NVM RF HR Failure"),
    B2146("Seat Recline Motor Position Out of Range"),
    B2148("PWM Input Circuit Failure"),
    B2149("Seat Front Vertical Motor Position Out of Range"),
    B2150("Power Supply #1 Circuit Short to Ground"),
    B2151("Power Supply #2 Circuit Short to Ground"),
    B2152("Seat Rear Vertical Motor Position Out of Range"),
    B2153("Rear Echo Sensor Circuit Failure"),
    B2154("Front Echo Sensor Circuit Failure"),
    B2155("Seat Horizontal Motor Position Out of Range"),
    B2156("Rear Doppler Sensor Circuit Failure"),
    B2157("Front Doppler Sensor Circuit Failure"),
    B2158("Seat Recline Motor Memory Position Out of Range"),
    B2159("Memory #1 output Short to Ground"),
    B2160("Memory #1 output Short to VBatt"),
    B2161("Seat Front Vertical Motor Memory Position Out of Range"),
    B2162("Data Mismatch #2 (receive data does not match what was expected)"),
    B2163("Clutch Position Fault"),
    B2164("Seat Rear Vertical Motor Memory Position Out of Range"),
    B2165("Gear shift position Fault"),
    B2166("Gear select position Fault"),
    B2167("Seat Horizontal Motor Memory Position Out of Range"),
    B2168("Unable to confirm Unlock Condition"),
    B2169("Unable to confirm lock Condition"),
    B2170("Steering Column Lock Switch Circuit Failure"),
    B2172("Inertia Switch input Circuit Open"),
    B2174("Window Driver Rear Remote Up Switch Short to Battery"),
    B2175("A/C Request Signal Circuit Short to Ground"),
    B2176("Overdrive switch circuit short to Vbatt"),
    B2177("Interior Scanning Sensor Circuit Failure"),
    B2178("Window Driver Rear Remote Down Switch Short to Battery"),
    B2179("Front Wiper Select Switch \"A\" Short to Ground"),
    B2180("Front Wiper Select Switch \"B\" Short to Ground"),
    B2181("Front Wiper Select Switch \"C\" Short to Ground"),
    B2182("Window Passenger Front Remote Up Switch Short to Battery"),
    B2183("Front Wiper Select Switch \"H\" Short to Ground"),
    B2184("Front Wiper Select Switch \"W\" Short to Ground"),
    B2185("Rear Wiper Select Switch \"D\" Short to Ground"),
    B2186("Window Passenger Front Remote Down Switch Short to Battery"),
    B2187("Rear Wiper Select Switch \"B\" Short to Ground"),
    B2188("Rear Wiper Select Switch \"E\" Short to Ground"),
    B2190("Window Passenger Rear Remote Up Switch Short to Battery"),
    B2194("Window Passenger Rear Remote Down Switch Short to Battery"),
    B2195("Driver Window Up / Down Power Circuit Short to Ground"),
    B2196("Passenger Window Up / Down Power Circuit Short to Ground"),
    B2197("TV Module Error"),
    B2198("TrafficMaster Module Error"),
    B2199("VICS Module Error"),
    B2200("No Communication to TV Module (No Fitting of TV)"),
    B2201("No Communication With Traffic MasterModule"),
    B2202("No Communication to VICS Module (No Fitting of VICS)"),
    B2203("CD-ROM Error"),
    B2204("GPS Antenna Connection Open or Short"),
    B2205("GPS Receiver Error"),
    B2206("Gyroscope Error"),
    B2207("ECU ROM Checksum Error"),
    B2208("Communication Link to Display and Switch Module Error"),
    B2209("Interior Lamp Override Switch Open Circuit"),
    B2210("Interior Lamp Override Switch Short to Ground"),
    B2211("Low Coolant Lamp Output Circuit Short to Battery"),
    B2214("Window Passenger Front Up Switch Short to Battery"),
    B2215("Window Passenger Front Down Switch Short to Battery"),
    B2219("Window Driver Front Current Feedback Exceeded"),
    B2220("Window Driver Rear Current Feedback Exceeded"),
    B2221("Window Passenger Front Current Feedback Exceeded"),
    B2222("Window Passenger Rear Current Feedback Exceeded"),
    B2223("Mirror Driver Drive Circuit Failure"),
    B2224("Mirror Passenger Drive Circuit Failure"),
    B2225("Front Crash Sensor Mount Fault"),
    B2226("Front Crash Sensor Internal Fault"),
    B2227("Front Crash Sensor Driver Communications Fault"),
    B2228("Air Bag Driver Circuit Short to Ground - Loop #2"),
    B2229("Air Bag Passenger Circuit Short to Ground - Loop #2"),
    B2230("Air Bag Driver Circuit Short to Battery - Loop #2"),
    B2231("Air Bag Passenger Circuit Short to Battery - Loop #2"),
    B2232("Air Bag Driver Circuit Open - Loop #2"),
    B2233("Air Bag passenger Circuit Open - Loop #2"),
    B2234("Air Bag Driver Inflator Circuit Resistance Low on Squib - Loop #2"),
    B2235("Air Bag Passenger Inflator Circuit"),
    B2236("Weak or Defected Electric Vehicle Battery Module Fault"),
    B2237("Vehicle Signal indicating Park While VSS Present"),
    B2238("Power Cable For Power Sliding Door Broken"),
    B2239("Rear Cargo Door Set Switch Stuck (Short to Ground)"),
    B2240("Rear Cargo Door Reset Switch Stuck (Short to Ground)"),
    B2241("Rear Cargo Door Lock Circuit Short to Ground"),
    B2242("Rear Cargo Door Unlock Circuit Open"),
    B2243("Driver Rear Door Ajar Circuit Open"),
    B2244("Driver Sliding Door Ajar Circuit Short to GND"),
    B2245("Passenger Rear Door Ajar Circuit Open"),
    B2246("Passenger Sliding Door Ajar Circuit Short to GND"),
    B2247("EV Battery Pack Temperature Fault"),
    B2248("Heated Windshield Relay Coil Circuit Failure"),
    B2249("Head Lamp Relay Coil Short to Battery"),
    B2250("All Doors Unlock Relay Circuit Failure"),
    B2251("Parklamp Output Relay Driver Circuit Failure"),
    B2252("Parklamp Output Relay Dirver Short to Battery"),
    B2300("Seat Driver Memory Position Error"),
    B2301("Seat Passenger Memory Position Error"),
    B2302("Seat Headrest Feedback Potentiometer Circuit Failure"),
    B2303("Seat Headrest Feedback Potentiometer Circuit Open"),
    B2304("Seat Headrest Feedback Potentiometer Circuit Short to Battery"),
    B2305("Seat Headrest Feedback Potentiometer Circuit Short to Ground"),
    B2306("Seat Headrest Motor Stalled"),
    B2310("Mirror Driver Memory Position Error"),
    B2311("Mirror Passenger Memory Position Error"),
    B2312("Mirror Passenger Horizontal Feedback Potentiometer Circuit Failure"),
    B2313("Mirror Passenger Horizontal Feedback Potentiometer Circuit Open"),
    B2314("Mirror Passenger Horizontal Feedback Potentiometer Circuit Short to Battery"),
    B2315("Mirror Passenger Horizontal Feedback Potentiometer Circuit Short to Ground"),
    B2316("Mirror Passenger Vertical Feedback Potentiometer Circuit Failure"),
    B2317("Mirror Passenger Vertical Feedback Potentiometer Circuit Open"),
    B2318("Mirror Passenger Vertical Feedback Potentiometer Circuit Short to Battery"),
    B2319("Mirror Passenger Vertical Feedback Potentiometer Circuit Short to Ground"),
    B2320("Mirror Driver Horizontal Feedback Potentiometer Circuit Failure"),
    B2321("Mirror Driver Horizontal Feedback Potentiometer Circuit Open"),
    B2322("Mirror Driver Horizontal Feedback Potentiometer Circuit Short to Battery"),
    B2323("Mirror Driver Horizontal Feedback Potentiometer Circuit Short to Ground"),
    B2324("Mirror Driver Vertical Feedback Potentiometer Circuit Failure"),
    B2325("Mirror Driver Vertical Feedback Potentiometer Circuit Open"),
    B2326("Mirror Driver Vertical Feedback Potentiometer Circuit Short to Battery"),
    B2327("Mirror Driver Vertical Feedback Potentiometer Circuit Short to Ground"),
    B2328("Column Reach Feedback Potentiometer Circuit Failure"),
    B2329("Column Reach Feedback Potentiometer Circuit Open"),
    B2330("Column Reach Feedback Potentiometer Circuit Short to Battery"),
    B2331("Column Reach Feedback Potentiometer Circuit Short to Ground"),
    B2332("Column Tilt Feedback Potentiometer Circuit Failure"),
    B2333("Column Tilt Feedback Potentiometer Circuit Open"),
    B2334("Column Tilt Feedback Potentiometer Circuit Short to Battery"),
    B2335("Column Tilt Feedback Potentiometer Circuit Short to Ground"),
    B2336("Mirror Switch Assembly Circuit Failure"),
    B2337("Mirror Switch Assembly Circuit Open"),
    B2338("Mirror Switch Assembly Circuit Short to Battery"),
    B2339("Mirror Switch Assembly Circuit Short to Ground"),
    B2340("Column Reach Motor Stalled"),
    B2341("Column Tilt Motor Stalled"),
    B2342("Seat Switch Reference Voltage Positive Common Open Circuit"),
    B2343("Seat Switch Reference Voltage Positive Common Supply Low Voltage"),
    B2344("Seat Switch Reference Voltage Positive Common Supply Voltage Fault"),
    B2345("Seat Switch Reference Voltage Negative Common Open Circuit"),
    B2346("Mirror Switch Reference Voltage Positive Common Open Circuit"),
    B2347("Mirror Switch Reference Voltage Positive Common Supply Low Voltage"),
    B2348("Mirror Switch Reference Voltage Positive Common Supply Voltage Fault"),
    B2349("Mirror Switch Reference Voltage Negative Common Open Circuit"),
    B2350("Steering Column Switch Circuit Short to Battery"),
    B2351("Steering Column Switch Circuit Failure"),
    B2352("Driver Memory Power Switch Indicator Circuit Short to Battery"),
    B2353("Driver Mirror Power Driver Circuit Short Ground"),
    B2354("Driver Mirror Horizontal / Vertical Feedback Potentiometer Circuit Open"),
    B2355("Passenger Mirror Horizontal / Vertical Feedback Potentiometer Circuit Open"),
    B2357("Driver Window Down Current Sense Low Circuit Failure"),
    B2362("Remote Open/Close signal Circuit Short to Ground"),
    B2363("Optical Sensor System Failure"),
    B2364("Fuel Filler Door Circuit Open"),
    B2365("B-pillar Power Sliding Door Open/Close Switch Input Ckt Short to Gnd"),
    B2366("IP Power Sliding Door Open/Close switch Ckt Short to Gnd"),
    B2367("Power Sliding Door Override Switch Input Ckt Short to Gnd"),
    B2368("Steering Column Switch Circuit Out of Range"),
    B2369("Chime OUTPUT Request Ckt Short to Ground"),
    B2373("LED #1 Circuit Short to Battery"),
    B2374("Power Sliding Detent (Latch) Circuit Failure"),
    B2380("Heater Coolant Temp sensor circuit Short to GND"),
    B2381("Heater Coolant Temp sensor circuit Open"),
    B2384("Audio Reverse Aid Mute Input Ckt Failure"),
    B2385("Audio Navigation Mute Input Ckt Failure"),
    B2401("Audio Tape Deck Mechanism Fault"),
    B2402("Audio CD/DJ Thermal Shutdown Fault"),
    B2403("Audio CD/DJ Internal Fault"),
    B2404("Audio Steering Wheel Switch Circuit Fault"),
    B2405("Audio Single-Disc CD Player Thermal Shutdown Fault"),
    B2406("Audio Single-Disc CD Player Internal Fault"),
    B2416("Climate Control Recirculation Actuator Out of Limits"),
    B2425("Remote Keyless Entry Out of Synchronization"),
    B2426("Passenger Solar Radiation Sensor Circuit Open"),
    B2427("Passenger Solar Radiation Sensor Circuit Short to Ground"),
    B2428("A/C Post Heater Sensor #2 Circuit Failure"),
    B2429("A/C Post Heater Sensor #2 Circuit Short to Ground"),
    B2431("Transponder Programming Failed"),
    B2432("Drivers Seat Belt Buckle Switch Circuit Open"),
    B2433("Drivers Seat Belt Buckle Switch Circuit Short to Battery"),
    B2434("Drivers Seat Belt Buckle Switch Circuit Short to Ground"),
    B2435("Drivers Seat Belt Buckle Switch Resistance out of Range"),
    B2436("Passengers Seat Belt Buckle Switch Circuit Open"),
    B2437("Passengers Seat Belt Buckle Switch Circuit Short to Battery"),
    B2438("Passengers Seat Belt Buckle Switch Circuit Short to Ground"),
    B2439("Passengers Seat Belt Buckle Switch Resistance out of Range"),
    B2440("Passenger Side"),
    B2441("Driver Side"),
    B2442("Intrusion Sensor Fault"),
    B2443("Powertrain Performance Mode Switch Circuit failure"),
    B2444("Driver Side Crash Sensor Internal Fault"),
    B2445("Passenger Side Crash Sensor Internal Fault"),
    B2446("RESCU/VEMS Input Circuit Open"),
    B2447("RESCU/VEMS Input Circuit Short to Battery"),
    B2448("RESCU/VEMS Input Circuit Short to Ground"),
    B2449("Aux Heater Glow Plug Circuit Short to Ground"),
    B2450("Aux Heater Glow Plug Circuit Open"),
    B2451("Aux Heater Fuel Pump Circuit Short to Ground"),
    B2452("Aux Heater Fuel Pump Circuit Open"),
    B2453("Aux Heater Blower Fan Circuit Short to Ground"),
    B2454("Aux Heater Blower Fan Circuit Open"),
    B2455("Aux Heater Blower Faulted"),
    B2456("Aux Heater Coolant Sensor Circuit Short to Ground"),
    B2457("Aux Heater Coolant Sensor Circuit Open"),
    B2458("Aux Heater Overheat Sensor Circuit Short to Ground"),
    B2459("Aux Heater Overheat Sensor Circuit Open"),
    B2460("Aux Heater Flame Sensor Circuit Short to Ground"),
    B2461("Aux Heater Flame Sensor Circuit Open"),
    B2462("Aux Heater Flame Out Fault"),
    B2463("Aux Heater Overheat Fault"),
    B2464("Aux Heater Start Time Exceeded"),
    B2465("Aux Heater Start Counter Overrun/System Locked (same as below ?)"),
    B2466("Aux Heater Overheat Counter Overrun/System Locked"),
    B2467("Aux Heater Cool Down Time Exceeded (may be con to a453-5 )"),
    B2468("Aux Heater Coolant Pump Circuit Short to Ground"),
    B2469("Aux Heater Coolant Pump Circuit Open"),
    B2470("Interior Fan Control Circuit Short to Ground"),
    B2471("Interior Fan Control Circuit Open"),
    B2472("Fog Lamp Switch Failure"),
    B2473("Passenger Door Disarm Switch ckt Short to Ground"),
    B2474("Passenger Door Lock Switch Circuit Shorted to Ground"),
    B2475("Passenger Door Unlock Switch Circuit Shorted to Ground"),
    B2476("RADIO PRESENT SWITCH Ckt Failure"),
    B2477("Module Configuration Failure"),
    B2478("ANTI THEFT INPUT SIGNAL SHORT TO GROUND"),
    B2479("BRAKE PARK SWITCH CIRCUIT SHORT TO GROUND"),
    B2480("LF CORNER LAMP OUTPUT Ckt Short to Battery"),
    B2481("Convertible Top Up/Down switch Fault"),
    B2482("RF CORNER LAMP OUTPUT Ckt Short to Battery"),
    B2483("Enable Signal Open Circuit"),
    B2484("Disable Signal Short to Ground"),
    B2485("LF SIDE REPEATER LAMP OUTPUT Ckt Short to Battery"),
    B2487("RF SIDE REPEATER LAMP OUTPUT Ckt Short to Battery"),
    B2489("UNDERHOOD LAMP OUTPUT CIRCUIT Failure"),
    B2490("UNDERHOOD LAMP OUTPUT CIRCUIT Short to Battery"),
    B2491("RF PARK LAMP OUTPUT CIRCUIT Short to Battery"),
    B2492("Already Programmed (Test Mode DTC Only !!!)"),
    B2493("LF PARK LAMP OUTPUT CIRCUIT Short to Battery"),
    B2494("ANTI THEFT HORN OUTPUT CIRCUIT Short to Batt"),
    B2495("ANTI THEFT HORN OUTPUT CIRCUIT Failure"),
    B2496("ANTI THEFT HORN OUTPUT CIRCUIT Short to Gnd"),
    B2499("COURTESY LAMP OUTPUT Failure"),
    B2500("COURTESY LAMP OUTPUT Ckt Short to Battery"),
    B2501("LF LAMP LOW BEAM CIRCUIT Failure"),
    B2502("LF LAMP LOW BEAM CIRCUIT Short to Battery"),
    B2503("RF LAMP LOW BEAM CIRCUIT Failure"),
    B2504("RF LAMP LOW BEAM CIRCUIT Short to Battery"),
    B2505("LF LAMP HIGH BEAM CIRCUIT Failure"),
    B2506("LF LAMP HIGH BEAM CIRCUIT Short to Battery"),
    B2507("RF LAMP HIGH BEAM CIRCUIT Failure"),
    B2508("RF LAMP HIGH BEAM CIRCUIT Short to Battery"),
    B2509("Rear Fog Lamp Switch Circuit Failure"),
    B2510("Main Blower Motor Relay Circuit Short to Battery"),
    B2511("Horn Output Relay Circuit Short to Battery"),
    B2512("Front Fog Lamp Relay Ckt Short to Battery"),
    B2513("Blower (Fan) Circuit Failure"),
    B2514("Blower (Fan) Circuit Short to Vbatt"),
    B2515("Heater Blower Relay Circuit Failure"),
    B2516("Blower Control Circuit Failure"),
    B2517("Emergency Power Off System Faulted"),
    B2518("Compressor Overtemp Fault"),
    B2519("High Mount Stop Lamp Circuit Failure"),
    B2520("High Mount Stop Lamp Circuit Short to Battery"),
    B2523("License Lamp Circuit Failure"),
    B2524("License Lamp Circuit Short to Battery"),
    B2525("Left Rear Backup Lamp Circuit Failure"),
    B2526("Left Rear Backup Lamp Circuit Short to Battery"),
    B2527("Left Rear Stop lamp Circuit Failure"),
    B2528("Left Rear Stop lamp Circuit Short to Battery"),
    B2529("Left Rear Turn Lamp Circuit Failure"),
    B2530("Left Rear Turn Lamp Circuit Short to Battery"),
    B2531("Right Rear Backup Lamp Circuit Failure"),
    B2532("Right Rear Backup Lamp Circuit Short to Battery"),
    B2533("Right Rear Stop lamp Circuit Failure"),
    B2534("Right Rear Stop lamp Circuit Short to Battery"),
    B2535("Right Rear Turn Lamp Circuit Failure"),
    B2536("Right Rear Turn Lamp Circuit Short to Battery"),
    B2539("Aux A/C Mode Position Reference Circuit Short to Ground"),
    B2540("Aux A/C Mode Position Reference Circuit Short to Battery"),
    B2543("Aux A/C Control Switch Reference Circuit Short to Ground"),
    B2544("Aux A/C Control Switch Reference Circuit Short to Battery"),
    B2545("System Power Relay Circuit Short to Battery"),
    B2546("System Power Relay Circuit Failure"),
    B2550("LAMP DOME OUTPUT Circuit Short to Ground"),
    B2553("Disable Signal Output Circuit Short to Battery"),
    B2554("LAMP DOME OUTPUT Circuit Failure"),
    B2555("LAMP DOME OUTPUT Circuit Short to Battery"),
    B2556("Enable Signal Circuit Short to Battery"),
    B2557("Left Power Sliding Door Open/Close Output Circuit Short to Battery"),
    B2558("Right Power Sliding Door Open/Close Output Circuit Short to Battery"),
    B2559("Aux A/C Blower Motor Relay Circuit Short to Battery"),
    B2560("Aux A/C Blower Motor Relay Circuit Short to Ground"),
    B2561("Aux A/C Blower Speed 1 Circuit Failure"),
    B2562("Aux A/C Blower Speed 1 Circuit Short to Ground"),
    B2563("Aux A/C Blower Speed 2 Circuit Failure"),
    B2564("Aux A/C Blower Speed 2 Circuit Short to Ground"),
    B2565("Right Tail Lamp Circuit Failure"),
    B2566("Right Tail Lamp Circuit Short to Ground"),
    B2567("Reverse Mirror Output Circuit Failure"),
    B2568("Reverse Mirror Output Circuit Short to Ground"),
    B2569("Liftgate Disarm Switch Circuit Short to Ground"),
    B2570("Right Lamp Outage Signal Circuit Short to Ground"),
    B2571("Left Lamp Outage Signal Circuit Short to Ground"),
    B2580("Aux Blower Sense Switch Circuit Failure"),
    B2581("Passenger Seat Occupant Detection Circuit Short To Ground"),
    B2582("Passenger Seat Occupant Detection Circuit Open"),
    B2583("Child Seat Detection Circuit Short to Ground"),
    B2584("Child Seat Detection Circuit Open"),
    B2585("Anti Theft Input Signal Circuit Short To Battery"),
    B2586("Headlamp Mode Select Circuit Failure"),
    B2587("Passenger Seat Occupant Detection Circuit Short To Battery"),
    B2588("Child Seat Detection Circuit Short To Battery"),
    B2589("Unexpected Door Reversal During Close"),
    B2590("Vehicle Park/Speed Signal Circuit Failure"),
    B2591("Detent Signal Missing During Unlatch"),
    B2592("PSD Not Fully Closed (Module Commanded Successfully)"),
    B2593("Power Sliding Door Opened During Module Close Command"),
    B2594("No Movement Detected After an Unlatch During Power Open"),
    B2595("Anti Theft Input Signal Circuit Failure"),
    B2596("Headlamp Aim Output Relay Circuit Short To Battery"),
    B2597("Headlamp Aim Output Relay Circuit Failure"),
    B2598("Headlamp Relay Circuit Failure"),
    B2599("Tailgate Release Open Circuit"),
    B2600("Double Locking Door Motor Frozen"),
    B2601("No Latch Signal Sensed on Closing and Door Reversed"),
    B2602("Missing Latch Signal During Power Sliding Door Unlatch"),
    B2603("PSD Not Fully Closed During Self-Test"),
    B2604("Power Sliding Door On/Off Switch Open Circuit"),
    B2605("Disable Signal Open Circuit"),
    B2606("A/C Temperature Sensor Out of Range")

}