package com.alpdroid.huGen10.obdUtil

enum class DtcChassis (val dtc:String) {

    C0000("ISO/SAE Reserved"),
    C0001("TCS Control Channel \"A\" Valve 1 (Subfault)"),
    C0002("TCS Control Channel \"A\" Valve 2 (Subfault)"),
    C0003("TCS Control Channel \"B\" Valve 1 (Subfault)"),
    C0004("TCS Control Channel \"B\" Valve 2 (Subfault)"),
    C0005("ISO/SAE Reserved"),
    C0006("ISO/SAE Reserved"),
    C0007("ISO/SAE Reserved"),
    C0008("ISO/SAE Reserved"),
    C0009("ISO/SAE Reserved"),
    C000A("ISO/SAE Reserved"),
    C000B("ISO/SAE Reserved"),
    C000C("ISO/SAE Reserved"),
    C000D("ISO/SAE Reserved"),
    C000E("ISO/SAE Reserved"),
    C000F("ISO/SAE Reserved"),
    C0010("Left Front Inlet Control (Subfault)"),
    C0011("Left Front Outlet Control (Subfault)"),
    C0012("Left Front Hydraulic Release Too Long (Subfault)"),
    C0013("ISO/SAE Reserved"),
    C0014("Right Front Inlet Control (Subfault)"),
    C0015("Right Front Outlet Control (Subfault)"),
    C0016("Right Front Hydraulic Release Too Long (Subfault)"),
    C0017("ISO/SAE Reserved"),
    C0018("Left Rear Inlet Control (Subfault)"),
    C0019("Left Rear Outlet Control (Subfault)"),
    C001A("Left Rear Hydraulic Release Too Long (Subfault)"),
    C001B("ISO/SAE Reserved"),
    C001C("Right Rear Inlet Control (Subfault)"),
    C001D("Right Rear Outlet Control (Subfault)"),
    C001E("Right Rear Hydraulic Release Too Long (Subfault)"),
    C001F("ISO/SAE Reserved"),
    C0020("ABS Pump Motor Control (Subfault)"),
    C0021("Brake Booster Performance (Subfault)"),
    C0022("Brake Booster Solenoid (Subfault)"),
    C0023("Stop Lamp Control (Subfault)"),
    C0024("ISO/SAE Reserved"),
    C0025("ISO/SAE Reserved"),
    C0026("ISO/SAE Reserved"),
    C0027("ISO/SAE Reserved"),
    C0028("ISO/SAE Reserved"),
    C0029("ISO/SAE Reserved"),
    C002A("ISO/SAE Reserved"),
    C002B("ISO/SAE Reserved"),
    C002C("ISO/SAE Reserved"),
    C002D("ISO/SAE Reserved"),
    C002E("ISO/SAE Reserved"),
    C002F("ISO/SAE Reserved"),
    C0030("Left Front Tone Wheel (Subfault)"),
    C0031("Left Front Wheel Speed Sensor (Subfault)"),
    C0032("Left Front Wheel Speed Sensor Supply (Subfault)"),
    C0033("Right Front Tone Wheel (Subfault)"),
    C0034("Right Front Wheel Speed Sensor (Subfault)"),
    C0035("Right Front Wheel Speed Sensor Supply (Subfault)"),
    C0036("Left Rear Tone Wheel (Subfault)"),
    C0037("Left Rear Wheel Speed Sensor (Subfault)"),
    C0038("Left Rear Wheel Speed Sensor Supply (Subfault)"),
    C0039("Right Rear Tone Wheel (Subfault)"),
    C003A("Right Rear Wheel Speed Sensor (Subfault)"),
    C003B("Right Rear Wheel Speed Sensor Supply (Subfault)"),
    C003C("Rear Tone Wheel (Subfault)"),
    C003D("Rear Wheel Speed Sensor (Subfault)"),
    C003E("Rear Wheel Speed Sensor Supply (Subfault)"),
    C003F("ISO/SAE Reserved"),
    C0040("Brake Pedal Switch \"A\" (Subfault)"),
    C0041("Brake Pedal Switch \"B\" (Subfault)"),
    C0042("Brake Pedal Position Sensor \"Circuit A\" (Subfault)"),
    C0043("Brake Pedal Position Sensor \"Circuit B\" (Subfault)"),
    C0044("Brake Pressure Sensor \"A\" (Subfault)"),
    C0045("Brake Pressure Sensor \"B\" (Subfault)"),
    C0046("Brake Pressure Sensor \"A\"/\"B\" (Subfault)"),
    C0047("Brake Booster Pressure Sensor (Subfault)"),
    C0048("Brake Booster Travel Sensor (Subfault)"),
    C0049("Brake Fluid (Subfault)"),
    C004A("Brake Lining Wear Sensor (Subfault)"),
    C004B("ISO/SAE Reserved"),
    C004C("ISO/SAE Reserved"),
    C004D("ISO/SAE Reserved"),
    C004E("ISO/SAE Reserved"),
    C004F("ISO/SAE Reserved"),
    C0050("ISO/SAE Reserved"),
    C0051("Steering Wheel Position Sensor (Subfault)"),
    C0052("Steering Wheel Position Sensor \"Signal A\" (Subfault)"),
    C0053("Steering Wheel Position Sensor \"Signal B\" (Subfault)"),
    C0054("Steering Wheel Position Sensor \"Signal C\" (Subfault)"),
    C0055("Steering Wheel Position Sensor \"Signal D\" (Subfault)"),
    C0056("ISO/SAE Reserved"),
    C0057("ISO/SAE Reserved"),
    C0058("ISO/SAE Reserved"),
    C0059("ISO/SAE Reserved"),
    C005A("ISO/SAE Reserved"),
    C005B("ISO/SAE Reserved"),
    C005C("ISO/SAE Reserved"),
    C005D("ISO/SAE Reserved"),
    C005E("ISO/SAE Reserved"),
    C005F("ISO/SAE Reserved"),
    C0060("ISO/SAE Reserved"),
    C0061("Lateral Acceleration Sensor (Subfault)"),
    C0062("Longitudinal Acceleration Sensor (Subfault)"),
    C0063("Yaw Rate Sensor (Subfault)"),
    C0064("Roll Rate Sensor"),
    C0065("ISO/SAE Reserved"),
    C0066("ISO/SAE Reserved"),
    C0067("ISO/SAE Reserved"),
    C0068("ISO/SAE Reserved"),
    C0069("Yaw Rate/Longitude Sensors (Subfault)"),
    C006A("Multi-axis Acceleration Sensor (Subfault)"),
    C006B("Stability System Active Too Long (Subfault)"),
    C006C("Stability System"),
    C006D("ISO/SAE Reserved"),
    C006E("ISO/SAE Reserved"),
    C006F("ISO/SAE Reserved"),
    C0070("ISO/SAE Reserved"),
    C0071("2/4 Wheel Drive Status Input (Subfault)"),
    C0072("Brake Temperature Too High (Subfault)"),
    C0073("Delivered Driving Torque (Subfault)"),
    C0074("Requested Driving Torque (Subfault)"),
    C0075("Extended Brake Pedal Travel, output to PCM (Subfault)"),
    C0076("PWM for Traction Control (Subfault)"),
    C0077("Low Tire Pressure (Subfault)"),
    C0078("Tire Diameter (Subfault)"),
    C0079("Variable Effort Steering (Subfault)"),
    C007A("ISO/SAE Reserved"),
    C007B("ISO/SAE Reserved"),
    C007C("ISO/SAE Reserved"),
    C007D("ISO/SAE Reserved"),
    C007E("ISO/SAE Reserved"),
    C007F("ISO/SAE Reserved"),
    C0080("ISO/SAE Reserved"),
    C0081("ABS Malfunction Indicator (Subfault)"),
    C0082("Brake System Malfunction Indicator (Subfault)"),
    C0083("Tire Pressure Monitor Malfunction Indicator (Subfault)"),
    C0084("Traction Active Indicator (Subfault)"),
    C0085("Traction Disable Indicator (Subfault)"),
    C0086("Vehicle Dynamics Indicator (Subfault)"),
    C0087("ISO/SAE Reserved"),
    C0088("ISO/SAE Reserved"),
    C0089("TCS Disable Switch (Subfault)"),
    C008A("TCS Mode Control (Subfault)"),
    C008B("ISO/SAE Reserved"),
    C0100("Rear ABS (both wheels) solenoid/motor #1 circuit malfunction"),
    C0300("Rear Propshaft Speed Sensor"),
    C1000("Brake Pedal Switch 1 Circuit Performance"),
    C1001("Vision System Camera General Electrical Failure"),
    C1091("Speed Wheel Sensor All Coherency Failure"),
    C1095("ABS Hydraulic Pump Motor Circuit Failure"),
    C1096("ABS Hydraulic Pump Motor Circuit Open"),
    C1097("ABS Hydraulic Pump Motor Circuit Short To Ground"),
    C1098("ABS Hydraulic Pump Motor Circuit Short To Battery"),
    C1100("ABS Pump Switch Circuit Failure"),
    C1101("ABS Hydraulic Valve Circuit Failure"),
    C1102("ABS Acceleration Switch Circuit Failure"),
    C1103("ABS Hydraulic Brake Switch Circuit Failure"),
    C1104("Traction Control Active Lamp - Circuit Short to Battery"),
    C1105("Traction Control Disable Lamp - Circuit Short to Battery"),
    C1106("Traction Control Disable Switch Circuit Short to Battery"),
    C1107("ABS Function Enabled Input Circuit Failure"),
    C1109("Speed Control Actuator Assembly Cable Release Failure"),
    C1110("ABS Power Relay Coil Circuit Failure"),
    C1111("ABS Power Relay Coil Open Circuit"),
    C1112("ABS Power Relay Coil Short Circuit To Ground"),
    C1113("ABS Power Relay Coil Short Circuit To Battery"),
    C1114("ABS Power Relay Output Short Circuit To Ground"),
    C1115("ABS Power Relay Output Short Circuit To Battery"),
    C1116("Starter Motor Circuit Failure"),
    C1117("RPM Input Circuit Failure"),
    C1123("Vehicle Speed Sensor Input Short to Battery"),
    C1124("Input shaft speed signal missing/faulted"),
    C1125("Brake Fluid Level Sensor Input Circuit Failure"),
    C1126("Cruise Control Command Switch Assembly Circuit Failure"),
    C1127("Cruise Control Deactivator Brake Switch Circuit Failure"),
    C1132("Clutch position ckt short to ground"),
    C1133("Clutch position ckt short to battery"),
    C1134("Gear Shift position short to ground"),
    C1135("Gear Shift position short to battery"),
    C1136("Gear Select position short to ground"),
    C1137("ECU is Defective"),
    C1138("Gear Select position short to Battery"),
    C1139("Wheel Speed Sensor Center Tone Ring Missing Tooth Fault"),
    C1140("Hydraulic Base Brake Failure"),
    C1141("Wheel Speed Sensor LF Tone Ring Tooth Missing Fault"),
    C1142("Wheel Speed Sensor RF Tone Ring Tooth Missing Fault"),
    C1143("Wheel Speed Sensor LR Tone Ring Tooth Missing Fault"),
    C1144("Wheel Speed Sensor RR Tone Ring Tooth Missing Fault"),
    C1145("Speed Wheel Sensor RF Input Circuit Failure"),
    C1146("Speed Wheel Sensor RF Circuit Open"),
    C1148("Speed Wheel Sensor RF Coherency Fault"),
    C1149("Hydraulic Fluid Pressure/ Flow Circuit Failure"),
    C1150("Two Speed Rear Axle Input Switch Circuit Short to Vbatt"),
    C1155("Speed Wheel Sensor LF Input Circuit Failure"),
    C1156("Speed Wheel Sensor LF Circuit Open"),
    C1157("Park Brake Actuator Assembly Switch Applied Circuit Failure"),
    C1158("Speed Wheel Sensor LF Coherency Fault"),
    C1159("Hydraulic Fluid Pressure/ Flow Circuit Short to Gnd"),
    C1161("Air Pressure Low Circuit Short to Gnd"),
    C1162("Park Brake Switch # 2 Released Circuit Failure"),
    C1163("Park Brake Switch # 2 Applied Circuit Short to Gnd"),
    C1164("Park Brake Actuator Assembly Switch Circuit Failure"),
    C1165("Speed Wheel Sensor RR Input Circuit Failure"),
    C1166("Speed Wheel Sensor RR Input Open Circuit"),
    C1167("Park Brake Actuator Assembly Switch Released Circuit Short to Gnd"),
    C1168("Speed Wheel Sensor RR Coherency Fault"),
    C1169("ABS Fluid Dumping Exceeds Maximum Timing"),
    C1170("PRNDL Switch Circuit Failure"),
    C1172("Park Brake Switch # 1 Applied Circuit Failure"),
    C1173("Park Brake Switch # 1 Released Circuit Short to Gnd"),
    C1174("Park Brake Switch # 2 Applied Circuit Failure"),
    C1175("Speed Wheel Sensor LR Input Circuit Failure"),
    C1176("Speed Wheel Sensor LR Circuit Open"),
    C1177("Park Brake Actuator Assembly Switch Released Circuit Failure"),
    C1178("Speed Wheel Sensor LR Coherency Fault"),
    C1179("Speed Control Actuator Assembly Cable Slack Failure"),
    C1180("Park Brake Valve Solenoid #1 Sense Input Circuit Failure"),
    C1181("Park Brake Valve Solenoid #1 Sense Input Circuit Short to Gound"),
    C1182("Park Lamp Flash Relay Circuit Failure"),
    C1183("Park Lamp Flash Relay Circuit Short to Battery"),
    C1184("ABS System Is Not Operational"),
    C1185("ABS Power Relay Output Circuit Failure"),
    C1186("ABS Power Relay Output Open Circuit"),
    C1187("Brake Fluid Level Sensor Input Open Circuit"),
    C1188("Brake Fluid Level Sensor Input Short Circuit To Battery"),
    C1189("Brake Fluid Level Sensor Input Short Circuit To Ground"),
    C1190("Speed Wheel Sensor LF Input Short Circuit To Battery"),
    C1191("Speed Wheel Sensor LF Input Short Circuit To Ground"),
    C1192("Speed Wheel Sensor RF Input Short Circuit To Battery"),
    C1193("Speed Wheel Sensor RF Input Short Circuit To Ground"),
    C1194("ABS Outlet Valve Coil LF Circuit Failure"),
    C1195("ABS Outlet Valve Coil LF Circuit Open"),
    C1196("ABS Outlet Valve Coil LF Circuit Short To Battery"),
    C1197("ABS Outlet Valve Coil LF Circuit Short To Ground"),
    C1198("ABS Inlet Valve Coil LF Circuit Failure"),
    C1199("ABS Inlet Valve Coil LF Circuit Open"),
    C1200("ABS Inlet Valve Coil LF Circuit Short To Battery"),
    C1201("ABS Inlet Valve Coil LF Circuit Short To Ground"),
    C1202("ABS Outlet Valve Coil Rear Circuit Failure"),
    C1203("ABS Outlet Valve Coil Rear Circuit Open"),
    C1204("ABS Outlet Valve Coil Rear Circuit Short To Battery"),
    C1205("ABS Outlet Valve Coil Rear Circuit Short To Ground"),
    C1206("ABS Inlet Valve Coil Rear Circuit Failure"),
    C1207("ABS Inlet Valve Coil Rear Circuit Open"),
    C1208("ABS Inlet Valve Coil Rear Circuit Short To Battery"),
    C1209("ABS Inlet Valve Coil Rear Circuit Short To Ground"),
    C1210("ABS Outlet Valve Coil RF Circuit Failure"),
    C1211("ABS Outlet Valve Coil RF Circuit Open"),
    C1212("ABS Outlet Valve Coil RF Circuit Short To Battery"),
    C1213("ABS Outlet Valve Coil RF Circuit Short To Ground"),
    C1214("ABS Inlet Valve Coil RF Circuit Failure"),
    C1215("ABS Inlet Valve Coil RF Circuit Open"),
    C1216("ABS Inlet Valve Coil RF Circuit Short To Battery"),
    C1217("ABS Inlet Valve Coil RF Circuit Short To Ground"),
    C1218("Lamp ABS Warning Output Circuit Failure"),
    C1219("Lamp ABS Warning Output Circuit Open"),
    C1220("Lamp ABS Warning Output Circuit Short To Battery"),
    C1221("Lamp ABS Warning Output Circuit Short To Ground"),
    C1222("Speed Wheel Mismatch"),
    C1223("Lamp Brake Warning Output Circuit Failure"),
    C1224("Lamp Brake Warning Output Circuit Open"),
    C1225("Lamp Brake Warning Output Circuit Short To Battery"),
    C1226("Lamp Brake Warning Output Circuit Short To Ground"),
    C1227("Speed Wheel Sensor LR Input Short Circuit To Battery"),
    C1228("Speed Wheel Sensor LR Input Short Circuit To Ground"),
    C1229("Speed Wheel Sensor Rear Center Coherency Fault"),
    C1230("Speed Wheel Sensor Rear Center Input Circuit Failure"),
    C1231("Speed Wheel Sensor Rear Center Circuit Open"),
    C1232("Speed Wheel Sensor Rear Center Input Short Circuit To Battery"),
    C1233("Speed Wheel LF Input Signal Missing"),
    C1234("Speed Wheel RF Input Signal Missing"),
    C1235("Speed Wheel RR Input Signal Missing"),
    C1236("Speed Wheel LR Input Signal Missing"),
    C1237("Speed Wheel Rear Input Signal Missing"),
    C1238("ABS Hydraulic Pressure Differential Switch Input Circuit Failure"),
    C1239("ABS Hydraulic Pressure Differential Switch Input Open Circuit"),
    C1240("ABS Hydraulic Pressure Differential Switch Input Short Circuit To Battery"),
    C1241("ABS Hydraulic Pressure Differential Switch Input Short Circuit To Ground"),
    C1242("ABS Outlet Valve Coil LR Circuit Failure"),
    C1243("ABS Outlet Valve Coil LR Circuit Open"),
    C1244("ABS Outlet Valve Coil LR Circuit Short To Battery"),
    C1245("ABS Outlet Valve Coil LR Circuit Short To Ground"),
    C1246("ABS Outlet Valve Coil RR Circuit Failure"),
    C1247("ABS Outlet Valve Coil RR Circuit Open"),
    C1248("ABS Outlet Valve Coil RR Circuit Short To Battery"),
    C1249("ABS Outlet Valve Coil RR Circuit Short To Ground"),
    C1250("ABS Inlet Valve Coil LR Circuit Failure"),
    C1251("ABS Inlet Valve Coil LR Circuit Open"),
    C1252("ABS Inlet Valve Coil LR Circuit Short To Battery"),
    C1253("ABS Inlet Valve Coil LR Circuit Short To Ground"),
    C1254("ABS Inlet Valve Coil RR Circuit Failure"),
    C1255("ABS Inlet Valve Coil RR Circuit Open"),
    C1256("ABS Inlet Valve Coil RR Circuit Short To Battery"),
    C1257("ABS Inlet Valve Coil RR Circuit Short To Ground"),
    C1258("Speed Wheel LF Comparison Failure"),
    C1259("Speed Wheel RF Comparison Failure"),
    C1260("Speed Wheel RR Comparison Failure"),
    C1261("Speed Wheel LR Comparison Failure"),
    C1262("Lamp Warning Relay Circuit Failure"),
    C1263("Lamp Warning Relay Circuit Open"),
    C1264("Lamp Warning Relay Circuit Short To Battery"),
    C1265("Lamp Warning Relay Circuit Short To Ground"),
    C1266("ABS Valve Power Relay Circuit Failure"),
    C1267("ABS Functions Temporarily Disabled"),
    C1268("Motor Relay # 1 Circuit Failure"),
    C1269("Motor Relay # 1 Circuit Short to Battery"),
    C1270("Motor # 1 Input Circuit Failure"),
    C1271("Motor # 1 Input Circuit Short to Gnd"),
    C1272("Motor # 2 Input Circuit Failure"),
    C1273("Motor # 2 Input Circuit Short to Vbat"),
    C1274("Solenoid Relay # 1 Circuit Failure"),
    C1275("Solenoid Relay # 1 Circuit Short to Vbatt"),
    C1276("Park Brake Actuator Assembly Switch Applied Circuit Short to Gnd"),
    C1277("STEERING Wheel Angle 1and 2 Circuit Failure"),
    C1278("STEERING Wheel Angle 1and 2 Signal Faulted"),
    C1279("Yaw Rate Sensor circuit Failure"),
    C1280("Yaw Rate Sensor Signal Fault"),
    C1281("Lateral Accelerometer circuit Failure"),
    C1282("Lateral Accelerometer Signal Fault"),
    C1283("Switch Test Signal Failure"),
    C1284("Oil Pressure Switch Failure"),
    C1285("Booster Solenoid circuit Failure"),
    C1286("Booster Mechanical Failure"),
    C1287("Booster Pedal Force switch circuit Failure"),
    C1288("Pressure Transducer Main / Primary Input Circuit Failure"),
    C1289("Pressure Transducer Redundant / Secondary Input Circuit Failure"),
    C1400("Traction Control Valve RF Circuit Failure"),
    C1401("Traction Control Valve RF Circuit Open"),
    C1402("Traction Control Valve RF Circuit Short To Ground"),
    C1403("Traction Control Valve RF Circuit Short To Battery"),
    C1404("Traction Control Valve Rear Circuit Failure"),
    C1405("Traction Control Valve Rear Circuit Open"),
    C1406("Traction Control Valve Rear Circuit Short To Ground"),
    C1407("Traction Control Valve Rear Circuit Short To Battery"),
    C1410("Traction Control Valve LF Circuit Failure"),
    C1411("Traction Control Valve LF Circuit Open"),
    C1412("Traction Control Valve LF Circuit Short To Ground"),
    C1413("Traction Control Valve LF Circuit Short To Battery"),
    C1414("Incorrect Module Design Level"),
    C1415("Incorrect Module Configuration"),
    C1416("Damper RF Circuit Short To Battery"),
    C1417("Damper RF Circuit Short to Ground"),
    C1418("Damper RF Circuit Failure"),
    C1419("Damper RF Circuit Open"),
    C1420("Hydraulic Fluid Pressure/ Flow Circuit Short to Vbatt"),
    C1421("Damper LF Circuit Short To Battery"),
    C1422("Damper LF Circuit Short to Ground"),
    C1423("Damper LF Circuit Failure"),
    C1424("Damper LF Circuit Open"),
    C1425("Damper RR Circuit Short to Ground"),
    C1426("Damper RR Circuit Short To Battery"),
    C1427("Damper RR Circuit Open"),
    C1428("Damper RR Circuit Failure"),
    C1429("Input-shaft-speed input circuit failure"),
    C1430("Damper LR Circuit Open"),
    C1431("Damper LR Circuit Short To Battery"),
    C1432("Damper LR Circuit Short to Ground"),
    C1433("Damper LR Circuit Failure"),
    C1435("Accelerometer Rear Circuit Failure"),
    C1436("Accelerometer Rear Circuit Signal Is Not Sensed"),
    C1437("Accelerometer Rear Circuit Short To Ground"),
    C1438("Accelerometer Rear Circuit Short To Battery"),
    C1439("Vehicle Acceleration EEC-IV Circuit Failure"),
    C1440("Pressure Transducer Main / Primary signal Faulted"),
    C1441("Steering Phase A Circuit Signal Is Not Sensed"),
    C1442("Steering Phase B Circuit Signal Is Not Sensed"),
    C1443("Steering Phase A Circuit Short To Ground"),
    C1444("Steering Phase B Circuit Short To Ground"),
    C1445("Speed Vehicle Signal Circuit Failure"),
    C1446("Brake Switch Circuit Failure"),
    C1447("Traction Control Module Request Circuit Failure"),
    C1448("Lamp Adaptive Damping Warning Circuit Failure"),
    C1449("Traction Control Motor Coherency Fault"),
    C1450("Traction Control Motor Circuit Failure"),
    C1451("Traction Control Motor Circuit Open"),
    C1452("Traction Control Motor Circuit Short to Battery"),
    C1453("Traction Control Motor Circuit Short to Ground"),
    C1454("Front Lateral Accelerometer Circuit Failure"),
    C1455("Accelerometer Front Circuit Failure"),
    C1456("Accelerometer Front Circuit Is Not Sensed"),
    C1457("Accelerometer Front Circuit Short To Ground"),
    C1458("Accelerometer Front Circuit Short To Battery"),
    C1459("Adaptive Mode Switch Circuit Failure"),
    C1460("Vehicle Accelerometer Power Circuit Failure"),
    C1461("Vehicle Accelerometer Power Circuit Short to Battery"),
    C1462("Left Front Vertical Accelerometer Circuit Failure"),
    C1463("Right Front Vertical Accelerometer Circuit Failure"),
    C1464("Pressure Transducer Redundant / Secondary Signal Faulted"),
    C1465("Damper High Side Front Circuit Short To Battery"),
    C1466("Damper Circuit Failure"),
    C1467("Damper High Side Rear Circuit Short To Battery"),
    C1468("Damper Low Side Front Circuit Failure"),
    C1469("Damper Low Side Rear Circuit Failure"),
    C1495("Traction Control Motor Potentiometer Circuit Failure"),
    C1496("Traction Control Motor Potentiometer Circuit Open"),
    C1497("Traction Control Motor Potentiometer Circuit Short to Battery"),
    C1498("Traction Control Motor Potentiometer Circuit Short to Ground"),
    C1499("Transfer Case Contact Plate \"A\" Encoder Circuit Failure"),
    C1500("Transfer Case Contact Plate \"B\" Encoder Circuit Failure"),
    C1501("Transfer Case Contact Plate \"C\" Encoder Circuit Failure"),
    C1502("Transfer Case Contact Plate \"D\" Encoder Circuit Failure"),
    C1503("Dynamic Stability Control Left Front Valve Malfunction"),
    C1504("Dynamic Stability Control Right Front Valve Malfunction"),
    C1505("Dynamic Stability Control Left Rear Valve Malfunction"),
    C1506("Dynamic Stability Control Right Rear Valve Malfunction"),
    C1507("Traction Control of Brake Exceeds Time-Out"),
    C1508("Traction Control of Engine Exceeds Time-Out"),
    C1510("Right Front Wheel Pressure Reduction Performance Problem"),
    C1511("Left Front Wheel Pressure Reduction Performance Problem"),
    C1512("Right Rear Wheel Pressure Reduction Performance Problem"),
    C1513("Left rear Wheel Pressure Reduction Performance Problem"),
    C1699("Left Rear Sensor Circuit Short to Vbat"),
    C1700("Left Rear Sensor Circuit Failure"),
    C1701("Left Rear Sensor Circuit Fault"),
    C1702("RightRear Sensor Circuit Short to Vbat"),
    C1703("Right Rear Sensor Circuit Failure"),
    C1704("Right Rear Sensor Circuit Fault"),
    C1705("Left Rear Center Sensor Circuit Short to Vbat"),
    C1706("Left Rear Center Sensor Circuit Failure"),
    C1707("Left Rear Center Sensor Circuit Fault"),
    C1708("Right Rear Center Sensor Circuit Short to Vbat"),
    C1709("Right Rear Center Sensor Circuit Failure"),
    C1710("Right Rear Center Sensor Circuit Fault"),
    C1711("Left Front Sensor Circuit Short to Vbat"),
    C1712("Left Front Sensor Circuit Failure"),
    C1713("Left Front Sensor Circuit Fault"),
    C1714("Right Front Sensor Circuit Short to Vbat"),
    C1715("Right Front Sensor Circuit Failure"),
    C1716("Right Front Sensor Circuit Fault"),
    C1717("Left Front Center Sensor Circuit Short to Vbat"),
    C1718("Left Front Center Sensor Circuit Failure"),
    C1719("Left Front Center Sensor Circuit Fault"),
    C1721("Air Suspension Height Sensor Power Circuit Open"),
    C1722("Air Suspension Height Sensor Power Circuit Short To Battery"),
    C1723("Air Suspension Height Sensor Power Circuit Short To Ground"),
    C1724("Air Suspension Height Sensor Power Circuit Failure"),
    C1725("Air Suspension Front Pneumatic Failure"),
    C1726("Air Suspension Rear Pneumatic Failure"),
    C1727("Air Suspension Reservoir Pneumatic Failure"),
    C1728("Transfer Case unable to transition between 2H and 4H"),
    C1729("Transfer Case unable to transition between 4H and 4L"),
    C1730("Reference Voltage Out of Range (+5 v)"),
    C1731("Air Suspension LF Corner Up Timeout"),
    C1732("Air Suspension LF Corner Down Timeout"),
    C1733("Air Suspension RF Corner Up Timeout"),
    C1734("Air Suspension RF Corner Down Timeout"),
    C1735("Air Suspension LR Corner Up Timeout"),
    C1736("Air Suspension LR Corner Down Timeout"),
    C1737("Air Suspension RR Corner Up Timeout"),
    C1738("Air Suspension RR Corner Down Timeout"),
    C1739("Right Front Center Sensor Circuit Short to Vbat"),
    C1740("Right Front Center Sensor Circuit Failure"),
    C1741("Right Front Center Sensor Circuit Fault"),
    C1742("Rear Sounder Circuit Failure"),
    C1743("Rear Sounder Circuit Short to Vbatt"),
    C1744("Front Sounder Circuit Failure"),
    C1745("Front Sounder Circuit Short to Vbatt"),
    C1748("Switch input Circuit Short to Gnd"),
    C1749("Trailer Input Circuit Failure"),
    C1750("Accelerator Position Sensor Out of Range"),
    C1751("Vehicle Speed Sensor # 1 Output Circuit Short to Vbatt"),
    C1752("Vehicle Speed Sensor # 1 Output Circuit Short to Gnd"),
    C1753("Hydraulic Clutch Actuator Valve Signal Fault"),
    C1754("Hydraulic Clutch Actuator Valve Circuit Failure"),
    C1755("Power Limit Shutdown Fault"),
    C1756("Air Suspension Front Height Sensor High (SE) Signal Circuit Failure"),
    C1757("Air Suspension Front Height Sensor High (SE) Signal Circuit Open"),
    C1758("Air Suspension Front Height Sensor High (SE) Signal Circuit Short To Battery"),
    C1759("Air Suspension Front Height Sensor High (SE) Signal Circuit Short To Ground"),
    C1760("Air Suspension Rear Height Sensor High (SE) Signal Circuit Failure"),
    C1761("Air Suspension Rear Height Sensor High (SE) Signal Circuit Open"),
    C1762("Air Suspension Rear Height Sensor High (SE) Signal Circuit Short To Battery"),
    C1763("Air Suspension Rear Height Sensor High (SE) Signal Circuit Short To Ground"),
    C1765("Air Suspension Rear Height Sensor Low Signal Circuit Failure"),
    C1766("Air Suspension Rear Height Sensor Low Signal Circuit Open"),
    C1767("Air Suspension Rear Height Sensor Low Signal Circuit Short To Battery"),
    C1768("Air Suspension Rear Height Sensor Low Signal Circuit Short To Ground"),
    C1770("Air Suspension Vent Solenoid Output Circuit Failure"),
    C1771("Air Suspension Vent Solenoid Output Circuit Open"),
    C1772("Air Suspension Vent Solenoid Output Circuit Short To Battery"),
    C1773("Air Suspension Vent Solenoid Output Circuit Short To Ground"),
    C1774("Coolant Temp Out of Range"),
    C1775("DC-DC Converter Failure"),
    C1776("Heater System Failure"),
    C1777("Vacuum Pressure Circuit Failure"),
    C1778("Power Steering Failure"),
    C1779("Blower Switch Failure"),
    C1780("Temperature Select Failure"),
    C1781("Engine Coolant Temperature Signal Missing/Fault"),
    C1790("Air Suspension LR Air Spring/Shock Solenoid Output Circuit Failure"),
    C1791("Air Suspension LR Air Spring/Shock Solenoid Output Circuit Open"),
    C1792("Air Suspension LR Air Spring/Shock Solenoid Output Circuit Short To Battery"),
    C1793("Air Suspension LR Air Spring/Shock Solenoid Output Circuit Short To Ground"),
    C1795("Air Suspension RR Air Spring/Shock Solenoid Output Circuit Failure"),
    C1796("Air Suspension RR Air Spring/Shock Solenoid Output Circuit Open"),
    C1797("Air Suspension RR Air Spring/Shock Solenoid Output Circuit Short To Battery"),
    C1798("Air Suspension RR Air Spring/Shock Solenoid Output Circuit Short To Ground"),
    C1800("Air Suspension Reservoir Solenoid Circuit Failure"),
    C1805("Mismatched PCM and/or ABS-TC Module"),
    C1813("Air Suspension LR Vent Request Exceeded Max Timing"),
    C1814("Air Suspension RR Vent Request Exceeded Max Timing"),
    C1818("Air Suspension LR Air Compress Request Exceeded Max Timing"),
    C1819("Air Suspension RR Air Compress Request Exceeded Max Timing"),
    C1820("Air Suspension RF Air Compress Request Exceeded Max Timing"),
    C1830("Air Suspension Compressor Relay Circuit Failure"),
    C1831("Air Suspension Compressor Relay Circuit Open"),
    C1832("Air Suspension Compressor Relay Circuit Short To Battery"),
    C1833("Air Suspension Compressor Relay Circuit Short To Ground"),
    C1834("Gauge Drive Current Fault"),
    C1835("Current Sense Circuit Failure"),
    C1836("Battery Temp out of Range"),
    C1837("Battery Heater Circuit Failure"),
    C1838("Charging System Fault"),
    C1839("Leakage Fault"),
    C1840("Air Suspension Disable Switch Circuit Failure"),
    C1841("Air Suspension Disable Switch Circuit Open"),
    C1842("Air Suspension Disable Switch Circuit Short To Battery"),
    C1843("Air Suspension Disable Switch Circuit Short To Ground"),
    C1844("Air Suspension Secondary Front Inflator Solenoid Output Circuit Failure"),
    C1845("Air Suspension Front Inflator Solenoid Output Circuit Failure"),
    C1846("Air Suspension Front Inflator Solenoid Output Circuit Open"),
    C1847("Air Suspension Front Inflator Solenoid Output Circuit Short To Battery"),
    C1848("Air Suspension Front Inflator Solenoid Output Circuit Short To Ground"),
    C1849("Master Cylinder Pressure Out of Range"),
    C1850("Air Suspension Warning Lamp Circuit Failure"),
    C1851("Air Suspension Warning Lamp Circuit Open"),
    C1852("Air Suspension Warning Lamp Circuit Short To Battery"),
    C1853("Air Suspension Warning Lamp Circuit Short To Ground"),
    C1854("Motor Temperature Out of Range"),
    C1855("Acceleration Position Sensor Conflict"),
    C1856("Traction Motor Encoder circuit Failure"),
    C1859("PRNDL Input #2 Circuit Failure"),
    C1860("PRNDL Input #3 Circuit Failure"),
    C1861("PRNDL Input #4 Circuit Failure"),
    C1862("Contactor Circuit Failure"),
    C1863("External Charging Fault"),
    C1864("Battery Module Fault"),
    C1865("Air Suspension Rear Inflator Solenoid Output Circuit Failure"),
    C1866("Air Suspension Rear Inflator Solenoid Output Circuit Open"),
    C1867("Air Suspension Rear Inflator Solenoid Output Circuit Short To Battery"),
    C1868("Air Suspension Rear Inflator Solenoid Output Circuit Short To Ground"),
    C1869("Air Suspension Gate Solenoid Output Circuit Failure"),
    C1870("Air Suspension Gate Solenoid Output Circuit Open"),
    C1871("Air Suspension Gate Solenoid Output Circuit Short To Battery"),
    C1872("Air Suspension Gate Solenoid Output Circuit Short To Ground"),
    C1873("Air Suspension RF Air Spring Solenoid Output Circuit Failure"),
    C1874("Air Suspension RF Air Spring Solenoid Output Circuit Open"),
    C1875("Air Suspension RF Air Spring Solenoid Output Circuit Short To Battery"),
    C1876("Air Suspension RF Air Spring Solenoid Output Circuit Short To Ground"),
    C1877("Air Suspension LF Air Spring Solenoid Output Circuit Failure"),
    C1878("Air Suspension LF Air Spring Solenoid Output Circuit Open"),
    C1879("Air Suspension LF Air Spring Solenoid Output Circuit Short To Battery"),
    C1880("Air Suspension LF Air Spring Solenoid Output Circuit Short To Ground"),
    C1881("Air Suspension RF Height Sensor Circuit Failure"),
    C1882("Air Suspension RF Height Sensor Circuit Open"),
    C1883("Air Suspension RF Height Sensor Circuit Short To Battery"),
    C1884("Air Suspension RF Height Sensor Circuit Short To Ground"),
    C1885("Air Suspension RR Height Sensor Circuit Failure"),
    C1886("Air Suspension RR Height Sensor Circuit Open"),
    C1887("Air Suspension RR Height Sensor Circuit Short To Battery"),
    C1888("Air Suspension RR Height Sensor Circuit Short To Ground"),
    C1889("Air Suspension LF Height Sensor Circuit Failure"),
    C1890("Air Suspension LF Height Sensor Circuit Open"),
    C1891("Air Suspension LF Height Sensor Circuit Short To Battery"),
    C1892("Air Suspension LF Height Sensor Circuit Short To Ground"),
    C1893("Air Suspension LR Height Sensor Circuit Failure"),
    C1894("Air Suspension LR Height Sensor Circuit Open"),
    C1895("Air Suspension LR Height Sensor Circuit Short To Battery"),
    C1896("Air Suspension LR Height Sensor Circuit Short To Ground"),
    C1897("Steering VAPS II Circuit Loop Failure"),
    C1898("Steering VAPS II Circuit Loop Open"),
    C1899("Steering VAPS II Circuit Loop Short To Battery"),
    C1900("Steering VAPS II Circuit Loop Short To Ground"),
    C1901("Ride Control RR Shock Actuator Circuit Failure"),
    C1902("Ride Control RR Shock Actuator Circuit Open"),
    C1903("Ride Control RR Shock Actuator Circuit Short To Battery"),
    C1904("Ride Control RR Shock Actuator Circuit Short To Ground"),
    C1905("Ride Control LR Shock Actuator Circuit Failure"),
    C1906("Ride Control LR Shock Actuator Circuit Open"),
    C1907("Ride Control LR Shock Actuator Circuit Short To Battery"),
    C1908("Ride Control LR Shock Actuator Circuit Short To Ground"),
    C1909("Ride Control RF Shock Actuator Circuit Failure"),
    C1910("Ride Control RF Shock Actuator Circuit Open"),
    C1911("Ride Control RF Shock Actuator Circuit Short To Battery"),
    C1912("Ride Control RF Shock Actuator Circuit Short To Ground"),
    C1913("Ride Control LF Shock Actuator Circuit Failure"),
    C1914("Ride Control LF Shock Actuator Circuit Open"),
    C1915("Ride Control LF Shock Actuator Circuit Short To Battery"),
    C1916("Ride Control LF Shock Actuator Circuit Short To Ground"),
    C1917("Steering EVO Out-of-Range Fault"),
    C1918("Air Suspension Ride Height Select Switch Circuit Failure"),
    C1920("Led #1 Circuit Failure"),
    C1921("VAPS Solenoid Actuator Output Circuit Failure"),
    C1922("VAPS Solenoid Actuator Output Circuit Open"),
    C1923("VAPS Solenoid Actuator Output Circuit Short To Battery"),
    C1924("VAPS Solenoid Actuator Output Circuit Short To Ground"),
    C1925("VAPS Solenoid Actuator Return Circuit Failure"),
    C1926("VAPS Solenoid Actuator Return Circuit Open"),
    C1927("VAPS Solenoid Actuator Return Circuit Short To Battery"),
    C1928("VAPS Solenoid Actuator Return Circuit Short To Ground"),
    C1929("Air Suspension Front Compressor Relay Circuit Failure"),
    C1930("Air Suspension Front Compressor Relay Circuit Open"),
    C1931("Air Suspension Front Compressor Relay Circuit Short To Battery"),
    C1932("Air Suspension Front Compressor Relay Circuit Short To Ground"),
    C1933("Solenoid Current Out Of Range"),
    C1934("HPU (Hydraulic Pump Unit) Pressurisation Failure"),
    C1935("Chime Circuit Failure"),
    C1936("Hydraulic Pump Relay Circuit Failure"),
    C1937("Steering Wheel Angle Sensor Offset Failure"),
    C1938("Invalid Steering Wheel Angle Sensor ID"),
    C1939("Brake Pressure Switch Input Circuit Failure"),
    C1940("Brake Pressure Switch Mechanical Failure"),
    C1942("Unrecognized Powertrain Configuration"),
    C1943("Airbag Deployment Indication Input Fault"),
    C1944("Gauge Driver Circuit Fault"),
    C1945("Park Switch Indicates Park with Vehicle Moving"),
    C1946("Seat Track Position Switch Circuit Open"),
    C1947("Seat Track Position Switch Circuit Short to Ground"),
    C1948("Seat Track Position Switch Circuit Resistance Out of Range"),
    C1949("Accelerometer Sensor Circuit Open"),
    C1950("Accelerometer Sensor Circuit Failure"),
    C1951("Lateral Accelerometer Sensor Circuit Open"),
    C1952("Yaw Rate Sensor Circuit Open"),
    C1953("Master Cylinder Pressure Sensor Circuit Open"),
    C1954("Master Cylinder Pressure Sensor Circuit Failure"),
    C1955("Steering Angle Sensor Circuit Open"),
    C1956("Steering Angle Sensor Circuit Failure"),
    C1957("Dynamic Stability Control Valve RF Circuit Failure"),
    C1958("Dynamic Stability Control Valve LF Circuit Failure"),
    C1959("Lateral Accelerometer Sensor Circuit Failure"),
    C1960("Driver Brake Apply Circuit Fault"),
    C1961("Park Lamp Relay Coil Circuit Failure"),
    C1962("Park Lamp Relay Coil Short to Battery"),
    C1963("Stability Control Inhibit Warning"),
    C2701("CAN SYSTEM"),
    C2702("CAN COMM CIRCUIT"),
    C2710("CAN HCM COMM"),
    C2713("CAN M/C B COMM"),
    C2767("Reserved - TBD")

}