package com.alpdroid.huGen10.obdUtil

enum class DtcNetwork (val dtc:String) {

    U0001("Controller area network (CAN) data bus: high speed bus/communication control module"),
    U0002("Controller area network (CAN) data bus: high speed bus - performance problem/ configuration error"),
    U0003("Controller area network (CAN) data bus: high speed bus(+)- open circuit"),
    U0004("Controller area network (CAN) data bus: high speed bus(+)- voltage low"),
    U0005("Controller area network (CAN) data bus: high speed bus(+)- voltage high"),
    U0006("Controller area network (CAN) data bus: high speed bus(-)- open circuit"),
    U0007("Controller area network (CAN) data bus: high speed bus (-)-voltage low"),
    U0008("Controller area network (CAN) data bus: high speed bus(-)- voltage high"),
    U0009("Controller area network (CAN) data bus: high speed bus (-)-shorted to data bus(+)"),
    U0010("Controller area network (CAN) data bus: medium speed bus"),
    U0011("Controller area network (CAN) data bus: medium speed bus - performance problem"),
    U0012("Controller area network (CAN) data bus: medium speed bus(+)- open circuit"),
    U0013("Controller area network (CAN) data bus: medium speed bus(+)- voltage low"),
    U0014("Controller area network (CAN) data bus: medium speed bus(+)- voltage high"),
    U0015("Controller area network (CAN) data bus: medium speed bus(-)"),
    U0016("Controller area network (CAN) data bus: medium speed bus(-)- voltage low"),
    U0017("Controller area network (CAN) data bus: medium speed bus(-)- voltage high"),
    U0018("Controller area network (CAN) data bus: medium speed bus (-)-shorted to data bus(+)"),
    U0019("Controller area network (CAN) data bus: low speed bus"),
    U0020("Controller area network (CAN) data bus: low speed bus - performance problem"),
    U0021("Controller area network (CAN) data bus: low speed bus (+) - open circuit"),
    U0022("Controller area network (CAN) data bus: low speed bus (+) - voltage low"),
    U0023("Controller area network (CAN) data bus: low speed bus (+) - voltage high"),
    U0024("Controller area network (CAN) data bus: low speed bus (-) - open circuit"),
    U0025("Controller area network (CAN) data bus: low speed bus (-) - voltage low"),
    U0026("Controller area network (CAN) data bus: low speed bus (-) - voltage high"),
    U0027("Controller area network (CAN) data bus: low speed bus (-) - shorted to data bus (+)"),
    U0028("Vehicle area network (VAN) data bus A"),
    U0029("Vehicle area network (VAN) data bus A - performance problem"),
    U0030("Vehicle area network (VAN) data bus A (+)- open circuit"),
    U0031("Vehicle area network (VAN) data bus A (+)- voltage low"),
    U0032("Vehicle area network (VAN) data bus A (+)- voltage high"),
    U0033("Vehicle area network (VAN) data bus A (-)- open circuit"),
    U0034("Vehicle area network (VAN) data bus A (-)- voltage low"),
    U0035("Vehicle area network (VAN) data bus A (-)- voltage high"),
    U0036("Vehicle area network (VAN) data bus A (-)- shorted to data bus A (+)"),
    U0037("Vehicle area network (VAN) data bus B"),
    U0038("Vehicle area network (VAN) data bus B - performance problem"),
    U0039("Vehicle area network (VAN) data bus B (+)- open circuit"),
    U0040("Vehicle area network (VAN) data bus B (+)- voltage low"),
    U0041("Vehicle area network (VAN) data bus B (+)- voltage high"),
    U0042("Vehicle area network (VAN) data bus B (-)- open circuit"),
    U0043("Vehicle area network (VAN) data bus B (-)- voltage low"),
    U0044("Vehicle area network (VAN) data bus B (-)- voltage high"),
    U0045("Vehicle area network (VAN) data bus B (-)- shorted to data bus B (+)"),
    U0046("Vehicle area network (VAN) data bus C"),
    U0047("Vehicle area network (VAN) data bus C - performance problem"),
    U0048("Vehicle area network (VAN) data bus C (+)- open circuit"),
    U0049("Vehicle area network (VAN) data bus C (+)- voltage low"),
    U0050("Vehicle area network (VAN) data bus C (+)- voltage high"),
    U0051("Vehicle area network (VAN) data bus C (-)- open circuit"),
    U0052("Vehicle area network (VAN) data bus C (-)- voltage low"),
    U0053("Vehicle area network (VAN) data bus C (-)- voltage high"),
    U0054("Vehicle area network (VAN) data bus C (-)- shorted to data bus C (+)"),
    U0055("Vehicle area network (VAN) data bus D"),
    U0056("Vehicle area network (VAN) data bus D- performance problem"),
    U0057("Vehicle area network (VAN) data bus D (+)- open circuit"),
    U0058("Vehicle area network (VAN) data bus D (+)- voltage low"),
    U0059("Vehicle area network (VAN) data bus D (+)- voltage high"),
    U0060("Vehicle area network (VAN) data bus D (-)- open circuit"),
    U0061("Vehicle area network (VAN) data bus D (-)- voltage low"),
    U0062("Vehicle area network (VAN) data bus D (-)- voltage high"),
    U0063("Vehicle area network (VAN) data bus D (-)- shorted to data bus D (+)"),
    U0064("Vehicle area network (VAN) data bus E"),
    U0065("Vehicle area network (VAN) data bus E - performance problem"),
    U0066("Vehicle area network (VAN) data bus E (+)- open circuit"),
    U0067("Vehicle area network (VAN) data bus E (+)- voltage low"),
    U0068("Vehicle area network (VAN) data bus E (+)- voltage high"),
    U0069("Vehicle area network (VAN) data bus E (-)- open circuit"),
    U0070("Vehicle area network (VAN) data bus E (-)- voltage low"),
    U0071("Vehicle area network (VAN) data bus E (-)- voltage high"),
    U0072("Vehicle area network (VAN) data bus E (-)- shorted to data bus E (+)"),
    U0073("Control module - data bus Off"),
    U0100("LOST COMM (ECM A)"),
    U0101("LOST COMM (TCM)"),
    U0111("Data bus: battery energy control module A - no communication"),
    U0112("Data bus: battery energy control module B - no communication"),
    U0113("CAN COMM CIRCUIT"),
    U0114("Data bus: four wheel drive clutch control module - no communication"),
    U0115("Data bus: engine control module (ECM) B - no communication"),
    U0120("STR/GEN C/M"),
    U0121("Data bus: anti-lock brake system (ABS) control module - no communication"),
    U0122("VDC MDL"),
    U0129("LOST COMM (BRAKE)"),
    U0140("LOST COMM (BCM)"),
    U0164("LOST COMM (HVAC)"),
    U0168("Data bus: alarm system control module - no communication"),
    U0284("LOST COMM (A/GRLL SHTTR MDL A)"),
    U0293("LOST COMM (HV ECU)"),
    U0298("DC/DC CNVRTR C/M A"),
    U0400("INVALID(HV ECU)"),
    U0418("INVALID (BRAKE)"),
    U0599("DC/DC CNVRTR C/M A"),
    U1000("CAN COMM CIRCUIT"),
    U1001("CAN COMM CIRCUIT"),
    U1002("SCP (J1850) Invalid or Missing Data for Primary Id"),
    U1003("CAN COMM CIRCUIT"),
    U1004("SCP (J1850) Invalid or Missing Data for EEC Programming"),
    U1005("AIRBAG SENSOR UNIT"),
    U1006("SCP (J1850) Invalid or Missing Data for Primary Id"),
    U1007("SCP (J1850) Invalid or Missing Data for Primary Id"),
    U1008("SCP (J1850) Invalid or Missing Data for Engine Torque"),
    U1009("SCP (J1850) Invalid or Missing Data for Engine Torque"),
    U1010("CONTROL UNIT(CAN)"),
    U1011("CONTROL UNIT(CAN)"),
    U1012("SCP (J1850) Invalid or Missing Data for Primary Id"),
    U1013("SCP (J1850) Invalid or Missing Data for Primary Id"),
    U1014("SCP (J1850) Invalid or Missing Data for Primary Id"),
    U1015("SCP (J1850) Invalid or Missing Data for Primary Id"),
    U1016("SCP (J1850) Invalid or Missing Data for Primary Id"),
    U1017("SCP (J1850) Invalid or Missing Data for Primary Id"),
    U1018("SCP (J1850) Invalid or Missing Data for Throttle"),
    U1019("SCP (J1850) Invalid or Missing Data for Throttle"),
    U1020("LOST COMM (HV ECU)"),
    U1021("INVALID (HV ECU)"),
    U1022("LOST COMM (BRAKE)"),
    U1023("INVALID (BRAKE)"),
    U1024("VVEL CAN COMM CIRCUIT"),
    U1025("SCP (J1850) Invalid or Missing Data for Primary Id"),
    U1026("SCP (J1850) Invalid or Missing Data for Engine RPM"),
    U1027("SCP (J1850) Invalid or Missing Data for Engine RPM"),
    U1028("SCP (J1850) Invalid or Missing Data for Primary Id"),
    U1029("SCP (J1850) Invalid or Missing Data for Primary Id"),
    U1030("SCP (J1850) Invalid or Missing Data for Experimental #1"),
    U1031("SCP (J1850) Invalid or Missing Data for Experimental #1"),
    U1032("SCP (J1850) Invalid or Missing Data for Primary Id"),
    U1033("SCP (J1850) Invalid or Missing Data for Primary Id"),
    U1034("SCP (J1850) Invalid or Missing Data for Primary Id"),
    U1035("SCP (J1850) Invalid or Missing Data for Primary Id"),
    U1036("SCP (J1850) Invalid or Missing Data for Wheels"),
    U1037("SCP (J1850) Invalid or Missing Data for Wheels"),
    U1038("SCP (J1850) Invalid or Missing Data for Primary Id"),
    U1039("SCP (J1850) Invalid or Missing Data for Primary Id / Vehicle Speed"),
    U1040("ENG COMM CIRCUIT"),
    U1041("STR/GEN C/M"),
    U1042("DC/DC CONVERTER"),
    U1043("DC/DC CONVERTER"),
    U1044("ENG COMM CIRCUIT"),
    U1045("COMMUNICATION ERROR"),
    U1046("COMMUNICATION ERROR"),
    U1047("SCP (J1850) Invalid or Missing Data for Primary Id"),
    U1048("SCP (J1850) Invalid or Missing Data for Primary Id"),
    U1049("SCP (J1850) Invalid or Missing Data for Primary Id"),
    U1050("LIN COMMUNICATION"),
    U1051("LIN COMMUNICATION"),
    U1052("SCP (J1850) Invalid or Missing Data for Steering / Steering Wheel"),
    U1053("SCP (J1850) Invalid or Missing Data for Steering / Steering Wheel"),
        U1054("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1055("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1056("SCP (J1850) Invalid or Missing Data for Vehicle Configuration"),
        U1057("SCP (J1850) Invalid or Missing Data for Vehicle Configuration"),
        U1058("SCP (J1850) Invalid or Missing Data for Transmission / Transaxle / PRNDL"),
        U1059("SCP (J1850) Invalid or Missing Data for Transmission / Transaxle / PRNDL"),
        U1060("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1061("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1062("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1063("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1064("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1065("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1066("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1067("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1068("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1069("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1070("SCP (J1850) Invalid or Missing Data for Engine Sensors"),
        U1071("SCP (J1850) Invalid or Missing Data for Engine Sensors"),
        U1072("SCP (J1850) Invalid or Missing Data for Engine Coolant"),
        U1073("SCP (J1850) Invalid or Missing Data for Engine Coolant"),
        U1074("SCP (J1850) Invalid or Missing Data for Engine Oil"),
        U1075("SCP (J1850) Invalid or Missing Data for Engine Oil Temp"),
        U1076("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1077("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1078("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1079("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1080("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1081("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1082("SCP (J1850) Invalid or Missing Data for Engine Systems Other"),
        U1083("SCP (J1850) Invalid or Missing Data for Engine Systems Other"),
        U1084("SCP (J1850) Invalid or Missing Data for Powertrain Status Request"),
        U1085("SCP (J1850) Invalid or Missing Data for Powertrain Status Request"),
        U1086("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1087("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1088("SCP (J1850) Invalid or Missing Data for Suspension"),
        U1089("SCP (J1850) Invalid or Missing Data for Suspension"),
        U1090("SCP (J1850) Invalid or Missing Data for Non-Legislated Diagnostics"),
        U1091("SCP (J1850) Invalid or Missing Data for Non-Legislated Diagnostics"),
        U1092("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1093("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1094("SCP (J1850) Invalid or Missing Data for Experimental #2"),
        U1095("SCP (J1850) Invalid or Missing Data for Experimental #2"),
        U1096("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1097("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1098("SCP (J1850) Invalid or Missing Data for Vehicle Speed Control"),
        U1099("SCP (J1850) Invalid or Missing Data for Vehicle Speed Control"),
        U1100("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1101("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1102("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1103("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1104("SCP (J1850) Invalid or Missing Data for Chassis Status Request"),
        U1105("SCP (J1850) Invalid or Missing Data for Chassis Status Request"),
        U1106("SCP (J1850) Invalid or Missing Data for Legislated Diagnostics"),
        U1107("SCP (J1850) Invalid or Missing Data for Legislated Diagnostics"),
        U1108("SCP (J1850) Invalid or Missing Data for Electric Traction Drive (Inverter)"),
        U1109("SCP (J1850) Invalid or Missing Data for Electric Traction Drive (Inverter)"),
        U1110("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1111("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1112("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1113("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1114("SCP (J1850) Invalid or Missing Data for Charging System"),
        U1115("SCP (J1850) Invalid or Missing Data for Charging System"),
        U1116("SCP (J1850) Invalid or Missing Data for Electrical Energy Management"),
        U1117("SCP (J1850) Invalid or Missing Data for Electrical Energy Management"),
        U1118("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1119("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1120("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1121("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1122("SCP (J1850) Invalid or Missing Data for Odometer"),
        U1123("SCP (J1850) Invalid or Missing Data for Odometer"),
        U1124("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1125("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1126("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1127("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1128("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1129("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U112C("Lost Communication With Transfer Case Switch Bank Module"),
        U112D("Lost Communication With EVIC Steering Wheel Switches"),
        U1130("SCP (J1850) Invalid or Missing Data for Fuel System"),
        U1131("SCP (J1850) Invalid or Missing Data for Fuel System"),
        U1132("SCP (J1850) Invalid or Missing Data for Vehicle Motion"),
        U1133("SCP (J1850) Invalid or Missing Data for Vehicle Motion"),
        U1134("SCP (J1850) Invalid or Missing Data for Ignition Switch / Starter"),
        U1135("SCP (J1850) Invalid or Missing Data for Ignition Switch / Starter"),
        U1136("SCP (J1850) Invalid or Missing Data for Telltales"),
        U1137("SCP (J1850) Invalid or Missing Data for Telltales"),
        U1138("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1139("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1140("SCP (J1850) Invalid or Missing Data for Gateway"),
        U1141("SCP (J1850) Invalid or Missing Data for Gateway"),
        U1142("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1143("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1144("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1145("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1146("SCP (J1850) Invalid or Missing Data for Vehicle Security"),
        U1147("SCP (J1850) Invalid or Missing Data for Vehicle Security"),
        U1148("SCP (J1850) Invalid or Missing Data for Audio Control"),
        U1149("SCP (J1850) Invalid or Missing Data for Audio Control"),
        U1150("SCP (J1850) Invalid or Missing Data for Audible Warnings"),
        U1151("SCP (J1850) Invalid or Missing Data for Audible Warnings"),
        U1152("SCP (J1850) Invalid or Missing Data for Experimental #3"),
        U1153("SCP (J1850) Invalid or Missing Data for Experimental #3"),
        U1154("SCP (J1850) Invalid or Missing Data for Compact Disc"),
        U1155("SCP (J1850) Invalid or Missing Data for Compact Disc"),
        U1156("SCP (J1850) Invalid or Missing Data for Digital Signal Processing"),
        U1157("SCP (J1850) Invalid or Missing Data for Digital Signal Processing"),
        U1158("SCP (J1850) Invalid or Missing Data for Antenna"),
        U1159("SCP (J1850) Invalid or Missing Data for Antenna"),
        U1160("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1161("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1162("SCP (J1850) Invalid or Missing Data for Digital Audio Tape"),
        U1163("SCP (J1850) Invalid or Missing Data for Digital Audio Tape"),
        U1164("SCP (J1850) Invalid or Missing Data for Tuner / Receiver"),
        U1165("SCP (J1850) Invalid or Missing Data for Tuner / Receiver"),
        U1166("SCP (J1850) Invalid or Missing Data for Cassette Tape"),
        U1167("SCP (J1850) Invalid or Missing Data for Cassette Tape"),
        U1168("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1169("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1170("SCP (J1850) Invalid or Missing Data for Cellular Phone / Paging System"),
        U1171("SCP (J1850) Invalid or Missing Data for Cellular Phone / Paging System"),
        U1172("SCP (J1850) Invalid or Missing Data for Remote Button Control"),
        U1173("SCP (J1850) Invalid or Missing Data for Remote Button Control"),
        U1174("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1175("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1176("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1177("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1178("SCP (J1850) Invalid or Missing Data for Climate Control (HVAC)"),
        U1179("SCP (J1850) Invalid or Missing Data for Climate Control (HVAC)"),
        U1180("SCP (J1850) Invalid or Missing Data for Personalization (Memory) Features"),
        U1181("SCP (J1850) Invalid or Missing Data for Personalization (Memory) Features"),
        U1182("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1183("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1184("SCP (J1850) Invalid or Missing Data for Window Wiper / Washer"),
        U1185("SCP (J1850) Invalid or Missing Data for Window Wiper / Washer"),
        U1186("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1187("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1188("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1189("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1190("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1191("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1192("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1193("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1194("SCP (J1850) Invalid or Missing Data for Mirrors"),
        U1195("SCP (J1850) Invalid or Missing Data for Mirrors"),
        U1196("SCP (J1850) Invalid or Missing Data for Door Locks"),
        U1197("SCP (J1850) Invalid or Missing Data for Door Locks"),
        U1198("SCP (J1850) Invalid or Missing Data for External Access (Doors)"),
        U1199("SCP (J1850) Invalid or Missing Data for External Access (Doors)"),
        U1200("SCP (J1850) Invalid or Missing Data for Seat Motion / Control"),
        U1201("SCP (J1850) Invalid or Missing Data for Seat Motion / Control"),
        U1202("SCP (J1850) Invalid or Missing Data for Windows"),
        U1203("SCP (J1850) Invalid or Missing Data for Windows"),
        U1204("SCP (J1850) Invalid or Missing Data for Steering Column"),
        U1205("SCP (J1850) Invalid or Missing Data for Steering Column"),
        U1206("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1207("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1208("SCP (J1850) Invalid or Missing Data for Seat Switches"),
        U1209("SCP (J1850) Invalid or Missing Data for Seat Switches"),
        U1210("SCP (J1850) Invalid or Missing Data for Restraints"),
        U1211("SCP (J1850) Invalid or Missing Data for Restraints"),
        U1212("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1213("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1214("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1215("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1216("SCP (J1850) Invalid or Missing Data for External Lamp Outage"),
        U1217("SCP (J1850) Invalid or Missing Data for External Lamp Outage"),
        U1218("SCP (J1850) Invalid or Missing Data for External Lamps"),
        U1219("SCP (J1850) Invalid or Missing Data for External Lamps"),
        U1220("SCP (J1850) Invalid or Missing Data for Interior Lamp Outage"),
        U1221("SCP (J1850) Invalid or Missing Data for Interior Lamp Outage"),
        U1222("SCP (J1850) Invalid or Missing Data for Interior Lamps"),
        U1223("SCP (J1850) Invalid or Missing Data for Interior Lamps"),
        U1224("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1225("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1226("SCP (J1850) Invalid or Missing Data for Body Status Request"),
        U1227("SCP (J1850) Invalid or Missing Data for Body Status Request"),
        U1228("SCP (J1850) Invalid or Missing Data for Tires"),
        U1229("SCP (J1850) Invalid or Missing Data for Tires"),
        U1230("SCP (J1850) Invalid or Missing Data for Electric Defrost"),
        U1231("SCP (J1850) Invalid or Missing Data for Electric Defrost"),
        U1232("SCP (J1850) Invalid or Missing Data for Navigation"),
        U1233("SCP (J1850) Invalid or Missing Data for Navigation"),
        U1234("SCP (J1850) Invalid or Missing Data for Displays"),
        U1235("SCP (J1850) Invalid or Missing Data for Displays"),
        U1236("SCP (J1850) Invalid or Missing Data for Memory Storage"),
        U1237("SCP (J1850) Invalid or Missing Data for Memory Storage"),
        U1238("SCP (J1850) Invalid or Missing Data for Experimental #4"),
        U1239("SCP (J1850) Invalid or Missing Data for Experimental #4"),
        U1240("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1241("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1242("SCP (J1850) Invalid or Missing Data for Exterior Environment"),
        U1243("SCP (J1850) Invalid or Missing Data for Exterior Environment"),
        U1244("SCP (J1850) Invalid or Missing Data for Interior Environment"),
        U1245("SCP (J1850) Invalid or Missing Data for Interior Environment"),
        U1246("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1247("SCP (J1850) Invalid or Missing Data for Primary Id"),
        U1248("SCP (J1850) Invalid or Missing Data for Time / Date"),
        U1249("SCP (J1850) Invalid or Missing Data for Time / Date"),
        U1250("SCP (J1850) Invalid or Missing Data for Vehicle Id (VIN)"),
        U1251("SCP (J1850) Invalid or Missing Data for Vehicle Id (VIN)"),
        U1252("SCP (J1850) Invalid or Missing Data for Class A Functions"),
        U1253("SCP (J1850) Invalid or Missing Data for Class A Functions"),
        U1254("SCP (J1850) Invalid or Missing Data for Network Control"),
        U1255("SCP (J1850) Invalid or Missing Data for Network Control"),
        U1260("SCP (J1850) Single Ended (+) Circuit Failure"),
        U1261("SCP (J1850) Single Ended (-) Circuit Failure"),
        U1262("SCP (J1850) Communication Bus Fault"),
        U1308("SCP (J1850) Invalid or Missing Data for Function Read Engine Torque"),
        U1341("SCP (J1850) Invalid or Missing Data for Function Read Vehicle Speed"),
        U1430("SCP (J1850) Invalid or Missing Data for Function Read Fuel System"),
        U1451("SCP (J1850) Invalid or Missing Data for Function Read Audible Warnings /Anti-Theft Module"),
        U1612("SCP (J1850) Lack of Acknowledgment for Primary Id"),
        U1736("SCP (J1850) Lack of Acknowledgment for Telltales"),
        U1750("SCP (J1850) Lack of Acknowledgment for Audible Warnings"),
        U1794("SCP (J1850) Lack of Acknowledgment for Mirrors"),
        U1797("SCP (J1850) Lack of Acknowledgment for Door Locks"),
        U1798("SCP (J1850) Lack of Acknowledgment for External Access (Doors)"),
        U1806("SCP (J1850) Lack of Acknowledgment for Primary Id"),
        U1900("CAN Communication Bus Fault"),
        U1950("UPB Communication Bus Fault"),
        U2000("Audio Rear Control Unit is Not Responding"),
        U2001("Audio Tape Deck Unit is Not Responding"),
        U2002("Audio Bezel is Not Responding"),
        U2003("Audio Compact Disk / Disk Jockey Unit is Not Responding"),
        U2004("Audio Steering Wheel Control Unit is Not Responding"),
        U2005("Audio Rear Integrated Control Panel Unit is Not Responding"),
        U2006("Audio Remote Climate Control Unit is Not Responding"),
        U2007("Audio Navigation Unit is Not Responding"),
        U2008("Audio Phone is Not Responding"),
        U2009("Audio Front Control Module (ACM) is Not Responding"),
        U2010("Module is Not Responding (Non SCP)"),
        U2011("Module Transmitted Invalid Data (Non SCP)"),
        U2012("Communication Bus Error (Non SCP)"),
        U2013("Compass Module is not Responding"),
        U2014("Audio Subwoofer Unit is Not Responding"),
        U2015("Signal Link Fault (Non SCP)"),
        U2016("Signal Link Short to Ground (Non SCP) / From NGV Module"),
        U2017("Driver Side Crash Sensor Communication Fault (Non SCP)"),
        U2018("Passenger Side Crash Sensor Communication Fault (Non SCP)"),
        U2019("Audio Voice Module Not Responding"),
        U2020("Audio Center Amp is not responding"),
        U2021("Invalid /fault data received (Non SCP)"),
        U2150("SCP (J1850) Invalid Data from REM"),
        U2152("SCP (J1850) Invalid Data from GEM"),
        U2160("SCP (J1850) Invalid Data from IC"),
        U2195("SCP (J1850) Invalid Data from SCLM"),
        U2500("(CAN) Lack of Acknowledgement From Engine Management")

}