package com.alpdroid.huGen10.obdUtil

enum class DtcPowertrain (val dtc:String) {

    P0000("No trouble code"),
    P0001("Fuel Volume Regulator Control Circuit / Open"),
    P0002("Fuel Volume Regulator Control Circuit Range/Performance"),
    P0003("Fuel Volume Regulator Control Circuit Low"),
    P0004("Fuel Volume Regulator Control Circuit High"),
    P0005("FUEL SHUTOFF VALVE A"),
    P0006("Fuel Shutoff Valve Control Circuit Low"),
    P0007("Fuel Shutoff Valve Control Circuit High"),
    P0008("Engine Position System Performance - Bank 2"),
    P0009("Engine Position System Performance - Bank 2"),
    P0010("Intake Camshaft Position Actuator Circuit / Open (Bank 2)"),
    P0011("INT/V TIM CONT-B1"),
    P0012("Intake Camshaft Position Timing - Over-Retarded (Bank 2)"),
    P0013("Exhaust Camshaft Position Actuator Circuit / Open (Bank 2)"),
    P0014("EXH/V TIM CONT-B1"),
    P0015("Exhaust Camshaft Position Timing - Over-Retarded (Bank 2)"),
    P0016("Crankshaft Position Camshaft Position Correlation Bank 2 Sensor A"),
    P0017("Crankshaft Position Camshaft Position Correlation Bank 2 Sensor B"),
    P0018("Crankshaft Position Camshaft Position Correlation Bank 2 Sensor A"),
    P0019("Crankshaft Position Camshaft Position Correlation Bank 2 Sensor B"),
    P0020("Intake Camshaft Position Actuator Circuit / Open (Bank 2)"),
    P0021("INT/V TIM CONT-B2"),
    P0022("Intake Camshaft Position Timing - Over-Retarded (Bank 2)"),
    P0023("Exhaust Camshaft Position Actuator Circuit / Open (Bank 2)"),
    P0024("EXH/V TIM CONT-B2"),
    P0025("Exhaust Camshaft Position Timing - Over-Retarded (Bank 2)"),
    P0026("Intake Valve Control Solenoid Circuit Range/Performance (Bank 2)"),
    P0027("Exhaust Valve Control Solenoid Circuit Range/Performance (Bank 2)"),
    P0028("Intake Valve Control Solenoid Circuit Range/Performance (Bank 2)"),
    P0029("Exhaust Valve Control Solenoid Circuit Range/Performance (Bank 2)"),
    P0030("HO2S1 HTR B1"),
    P0031("Heated Oxygen Sensor (HO2S) Heater Circuit Low Voltage Bank 2 Sensor 1"),
    P0032("Heated Oxygen Sensor (HO2S) Heater Circuit High Voltage Bank 2 Sensor 1"),
    P0033("Turbo/Super Charger Bypass Valve Control Circuit / Open"),
    P0034("SCB/V CONT SOL/V"),
    P0035("Turbo/Super Charger Bypass Valve Control Circuit High"),
    P0036("HO2S2 HTR (B1)"),
    P0037("HO2S2 HTR (B1)"),
    P0038("HO2S2 HTR (B1)"),
    P0039("TC/SC BYPASS VALVE"),
    P0040("Oxygen Sensor Signals Swapped Bank 2 Sensor 1 / Bank 2 Sensor 1"),
    P0041("Oxygen Sensor Signals Swapped Bank 2 Sensor 2 / Bank 2 Sensor 2"),
    P0042("HO2S Heater Control Circuit (Bank 2, Sensor 3)"),
    P0043("HO2S3 HTR (B1)"),
    P0044("HO2S3 HTR (B1)"),
    P0045("TC BOOST SOL/V"),
    P0046("Turbocharger/Supercharger Boost Control Circuit Range/Performance"),
    P0047("TC/SC BOOST CONT A"),
    P0048("TC/SC BOOST CONT A"),
    P0049("Turbo/Super Charger Turbine Overspeed"),
    P004A("TC BOOST SOL/CIRC-B2"),
    P004B("Turbocharger/Supercharger Boost Control Circuit Range/Performance"),
    P004C("TC BOOST SOL/CIRC-B2"),
    P004D("TC BOOST SOL/CIRC-B2"),
    P0050("Heated Oxygen Sensor (HO2S) Heater Circuit Bank 2 Sensor 1"),
    P0051("Heated Oxygen Sensor (HO2S) Heater Circuit Low Voltage Bank 2 Sensor 1"),
    P0052("Heated Oxygen Sensor (HO2S) Heater Circuit High Voltage Bank 2 Sensor 1"),
    P0053("HO2S1 HTR B1"),
    P0054("HO2S1 HTR B1"),
    P0055("HO2S Heater Resistance Bank 2 Sensor 3 (PCM)"),
    P0056("Heated Oxygen Sensor (HO2S) Heater Circuit Bank 2 Sensor 2"),
    P0057("HO2S2 HTR (B2)"),
    P0058("HO2S2 HTR (B2)"),
    P0059("HO2S Heater Resistance (Bank 2, Sensor 1)"),
    P0060("HO2S Heater Resistance (Bank 2, Sensor 2)"),
    P0061("HO2S Heater Resistance (Bank 2, Sensor 3)"),
    P0062("HO2S Heater Control Circuit (Bank 2, Sensor 3)"),
    P0063("HO2S3 HTR (B2)"),
    P0064("HO2S3 HTR (B2)"),
    P0065("Air Assisted Injector Control Range/Performance"),
    P0066("Air Assisted Injector Control Circuit or Circuit Low"),
    P0067("Air Assisted Injector Control Circuit or Circuit High"),
    P0068("MAP / MAF - Throttle Position Correlation"),
    P0069("MAP - Barometric Pressure Correlation"),
    P006A("MAP-MAF CORELTION-B1"),
    P0070("Ambient Air Temperature Sensor Circuit"),
    P0071("Ambient Air Temperature Sensor Range/Performance"),
    P0072("Ambient Air Temperature Sensor Circuit Low Input"),
    P0073("Ambient Air Temperature Sensor Circuit High Input"),
    P0074("Ambient Air Temperature Sensor Circuit Intermittent/Erratic"),
    P0075("INT/V TIM V/CIR-B1"),
    P0076("Intake Valve Control Circuit Low (Bank 2)"),
    P0077("Intake Valve Control Circuit High (Bank 2)"),
    P0078("EX V/T ACT/CIRC-B1"),
    P0079("Exhaust Valve Control Circuit Low (Bank 2)"),
    P007A("CHARGE AIR COOLER TEMP SEN B1"),
    P007B("CHARGE AIR COOLER TEMP SEN B1"),
    P007C("CHARGE AIR COOLER TEMP SEN B1"),
    P007D("CHARGE AIR COOLER TEMP SEN B1"),
    P007E("CHARGE AIR COOLER TEMP SEN B1"),
    P0080("Exhaust Valve Control Circuit High (Bank 2)"),
    P0081("INT/V TIM V/CIR-B2"),
    P0082("Intake Valve Control Circuit Low (Bank 2)"),
    P0083("Intake Valve Control Circuit High (Bank 2)"),
    P0084("EX V/T ACT/CIRC-B2"),
    P0085("Exhaust Valve Control Circuit Low (Bank 2)"),
    P0086("Exhaust Valve Control Circuit High (Bank 2)"),
    P0087("LOW FUEL PRES"),
    P0088("HIGH FUEL PRES"),
    P0089("Fuel Pressure Regulator Performance"),
    P008A("LOW FUEL PRES SYS"),
    P008B("LOW FUEL PRES SYS"),
    P0090("FUEL PUMP"),
    P0091("Fuel Pressure Regulator Control Circuit Low"),
    P0092("Fuel Pressure Regulator Control Circuit High"),
    P0093("Fuel System Leak Detected - Large Leak"),
    P0094("Fuel System Leak Detected - Small Leak"),
    P0095("Intake Air Temperature Sensor 2 Circuit"),
    P0096("IAT SENSOR 2 B1"),
    P0097("IAT SENSOR 2 B1"),
    P0098("IAT SENSOR 2 B1"),
    P0099("Intake Air Temperature Sensor 2 Circuit Intermittent/Erratic"),
    P00B3("P00B3"),
    P00B4("P00B4"),
    P0100("MAF SEN/CIRCUIT"),
    P0101("MAF SEN/CIRCUIT-B1"),
    P0102("MAF SEN/CIRCUIT-B1"),
    P0103("MAF SEN/CIRCUIT-B1"),
    P0104("Mass or Volume Air Flow Circuit Intermittent"),
    P0105("ABSL PRES SEN/CIRC"),
    P0106("ABSL PRES SEN/CIRC"),
    P0107("ABSL PRES SEN/CIRC"),
    P0108("ABSL PRES SEN/CIRC"),
    P0109("Manifold Absolute Pressure/Barometric Pressure Circuit Intermittent"),
    P010A("ABSL PRES SEN/CIRC"),
    P010B("MAF SEN/CIRCUIT-B2"),
    P010C("MAF SEN/CIRCUIT-B2"),
    P010D("MAF SEN/CIRCUIT-B2"),
    P0110("AIR TEMP SEN/CIRC"),
    P0111("IAT SENSOR 1 B1"),
    P0112("IAT SEN/CIRCUIT-B1"),
    P0113("IAT SEN/CIRCUIT-B1"),
    P0114("Intake Air Temperature Circuit Intermittent"),
    P0115("ECT SEN/CIRC"),
    P0116("ECT SENSOR"),
    P0117("ECT SEN/CIRC"),
    P0118("ECT SEN/CIRC"),
    P0119("Engine Coolant Temperature Circuit Intermittent"),
    P011C("CAT/IAT CRRLTN B1"),
    P0120("THRTL POS SEN/CIRC"),
    P0121("Throttle Position Sensor/Switch A Circuit Range/Performance Problem"),
    P0122("Throttle Position Sensor/Switch A Circuit Low Input"),
    P0123("Throttle Position Sensor/Switch A Circuit High Input"),
    P0124("Throttle Position Sensor/Switch A Circuit Intermittent"),
    P0125("ECT SENSOR"),
    P0126("ECT Excessive Time to Closed Loop Fuel Control"),
    P0127("IAT SENSOR-B1"),
    P0128("THERMSTAT FNCTN"),
    P0130("Coolant Thermostat Malfunction"),
    P0131("O2 Sensor Circuit Malfunction (Bank 1 Sensor 1)"),
    P0132("O2 Sensor Circuit Low Voltage (Bank 1 Sensor 1)"),
    P0133("O2 Sensor Circuit High Voltage (Bank 1 Sensor 1)"),
    P0134("HO2S1 (B1)"),
    P0135("HO2S1 HTR (B1)"),
    P0136("HO2S2 (B1)"),
    P0137("HO2S2 (B1)"),
    P0138("HO2S2 (B1)"),
    P0139("HO2S2 (B1)"),
    P0140("HO2S2 (B1)"),
    P0141("HO2S2 HTR (B1)"),
    P0142("O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 2)"),
    P0143("HO2S3 (B1)"),
    P0144("HO2S3 (B1)"),
    P0145("HO2S3 (B1)"),
    P0146("HO2S3 (B1)"),
    P0147("HO2S3 HTR (B1)"),
    P014C("A/F SENSOR1 (B1)"),
    P014D("A/F SENSOR1 (B1)"),
    P014E("A/F SENSOR1 (B2)"),
    P014F("A/F SENSOR1 (B2)"),
    P0150("O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 3)"),
    P0151("O2 Sensor Circuit Malfunction (Bank 2 Sensor 1)"),
    P0152("O2 Sensor Circuit Low Voltage (Bank 2 Sensor 1)"),
    P0153("O2 Sensor Circuit High Voltage (Bank 2 Sensor 1)"),
    P0154("HO2S1 (B2)"),
    P0155("HO2S1 HTR (B2)"),
    P0156("HO2S2 (B2)"),
    P0157("HO2S2 (B2)"),
    P0158("HO2S2 (B2)"),
    P0159("HO2S2 (B2)"),
    P015A("A/F SENSOR1 (B1)"),
    P015B("A/F SENSOR1 (B1)"),
    P015C("A/F SENSOR1 (B2)"),
    P015D("A/F SENSOR1 (B2)"),
    P0160("HO2S2 (B2)"),
    P0161("HO2S2 HTR (B2)"),
    P0162("O2 Sensor Heater Circuit Malfunction (Bank 2 Sensor 2)"),
    P0163("HO2S3 (B2)"),
    P0164("HO2S3 (B2)"),
    P0165("HO2S3 (B2)"),
    P0166("HO2S3 (B2)"),
    P0167("O2 Sensor Circuit No Activity Detected (Bank 2 Sensor 3)"),
    P0170("FUEL INJ SYSTEM-B1"),
    P0171("FUEL SYS-LEAN-B1"),
    P0172("FUEL SYS-RICH-B1"),
    P0173("FUEL INJ SYSTEM-B2"),
    P0174("FUEL SYS-LEAN-B2"),
    P0175("FUEL SYS-RICH-B2"),
    P0176("Fuel Trim too Rich (Bank 2)"),
    P0177("Fuel Composition Sensor Circuit Malfunction"),
    P0178("Fuel Composition Sensor Circuit Range/Performance"),
    P0179("Fuel Composition Sensor Circuit Low Input"),
    P0180("FUEL TEMP SEN/CIRC"),
    P0181("FTT SENSOR"),
    P0182("FTT SEN/CIRCUIT"),
    P0183("FTT SEN/CIRCUIT"),
    P0184("Fuel Temperature Sensor A Circuit High Input"),
    P0185("FUEL TEMP SEN B"),
    P0186("Fuel Temperature Sensor B Circuit Malfunction"),
    P0187("FUEL TEMP SEN B"),
    P0188("FUEL TEMP SEN B"),
    P0189("Fuel Temperature Sensor B Circuit High Input"),
    P0190("FUEL PRES SEN/CIRC"),
    P0191("FRP SENSOR A"),
    P0192("FRP SEN/CIRC"),
    P0193("FRP SEN/CIRC"),
    P0194("Fuel Rail Pressure Sensor Circuit High Input"),
    P0195("Fuel Rail Pressure Sensor Circuit Intermittent"),
    P0196("EOT SENSOR"),
    P0197("EOT SEN/CIRK"),
    P0198("EOT SEN/CIRK"),
    P0199("Engine Oil Temperature Sensor High"),
    P0200("INJECTOR CIRC-CYL"),
    P0201("INJECTOR CIRC-CYL1"),
    P0202("INJECTOR CIRC-CYL2"),
    P0203("INJECTOR CIRC-CYL3"),
    P0204("INJECTOR CIRC-CYL4"),
    P0205("INJECTOR CIRC-CYL5"),
    P0206("INJECTOR CIRC-CYL6"),
    P0207("INJECTOR CIRC-CYL7"),
    P0208("INJECTOR CIRC-CYL8"),
    P0209("Injector Circuit Malfunction - Cylinder 8"),
    P0210("Injector Circuit Malfunction - Cylinder 9"),
    P0211("Injector Circuit Malfunction - Cylinder 10"),
    P0212("Injector Circuit Malfunction - Cylinder 11"),
    P0213("Injector Circuit Malfunction - Cylinder 12"),
    P0214("Cold Start Injector 1 Malfunction"),
    P0215("Cold Start Injector 2 Malfunction"),
    P0216("Engine Shutoff Solenoid Malfunction"),
    P0217("ENG OVER TEMP"),
    P0218("TM FLUID OVER TEMP"),
    P0219("Transmission Over Temperature Condition"),
    P0220("Engine Overspeed Condition"),
    P0221("TP SENSOR"),
    P0222("TP SEN 1/CIRC-B1"),
    P0223("TP SEN 1/CIRC-B1"),
    P0224("Throttle/Petal Position Sensor/Switch B Circuit High Input"),
    P0225("Throttle/Petal Position Sensor/Switch B Circuit Intermittent"),
    P0226("APP SENSOR"),
    P0227("Throttle/Petal Position Sensor/Switch C Circuit Range/Performance Problem"),
    P0228("Throttle/Petal Position Sensor/Switch C Circuit Low Input"),
    P0229("Throttle/Petal Position Sensor/Switch C Circuit High Input"),
    P0230("Throttle/Petal Position Sensor/Switch C Circuit Intermittent"),
    P0231("Fuel Pump Primary Circuit Malfunction"),
    P0232("Fuel Pump Secondary Circuit Low"),
    P0233("Fuel Pump Secondary Circuit High"),
    P0234("TC SYSTEM-B1"),
    P0235("TURBO BOOST SENSOR"),
    P0236("TC BOOST SEN/CIRC-B1"),
    P0237("TC BOOST SEN/CIRC-B1"),
    P0238("TC BOOST SEN/CIRC-B1"),
    P0239("TC/SC boost sensor B"),
    P023A("P023A"),
    P023B("P023B"),
    P023C("P023C"),
    P0240("TC BOOST SEN/CIRC-B2"),
    P0241("TC BOOST SEN/CIRC-B2"),
    P0242("TC BOOST SEN/CIRC-B2"),
    P0243("W/G CONT SOL/V-B1"),
    P0244("Turbocharger Wastegate Solenoid A Malfunction"),
    P0245("SCB/V CONT SOL/V"),
    P0246("Turbocharger Wastegate Solenoid A Low"),
    P0247("W/G CONT SOL/V-B2"),
    P0248("Turbocharger Wastegate Solenoid B Malfunction"),
    P0249("Turbocharger Wastegate Solenoid B Range/Performance"),
    P0250("Turbocharger Wastegate Solenoid B Low"),
    P0251("Turbocharger Wastegate Solenoid B High"),
    P0252("Injection Pump Fuel Metering Control \"A\" Malfunction (Cam/Rotor/Injector)"),
    P0253("Injection Pump Fuel Metering Control \"A\" Range/Performance (Cam/Rotor/Injector)"),
    P0254("Injection Pump Fuel Metering Control \"A\" Low (Cam/Rotor/Injector)"),
    P0255("Injection Pump Fuel Metering Control \"A\" High (Cam/Rotor/Injector)"),
    P0256("Injection Pump Fuel Metering Control \"A\" Intermittent (Cam/Rotor/Injector)"),
    P0257("Injection Pump Fuel Metering Control \"B\" Malfunction (Cam/Rotor/Injector)"),
    P0258("Injection Pump Fuel Metering Control \"B\" Range/Performance (Cam/Rotor/Injector)"),
    P0259("Injection Pump Fuel Metering Control \"B\" Low (Cam/Rotor/Injector)"),
    P025A("FUEL PUMP MODULE A"),
    P025B("FUEL PUMP MODULE A"),
    P0260("Injection Pump Fuel Metering Control \"B\" High (Cam/Rotor/Injector)"),
    P0261("CYL1 INJECTOR"),
    P0262("CYL1 INJECTOR"),
    P0263("Cylinder 1 Injector Circuit High"),
    P0264("CYL2 INJECTOR"),
    P0265("CYL2 INJECTOR"),
    P0266("Cylinder 2 Injector Circuit High"),
    P0267("CYL3 INJECTOR"),
    P0268("CYL3 INJECTOR"),
    P0269("Cylinder 3 Injector Circuit High"),
    P0270("CYL4 INJECTOR"),
    P0271("CYL4 INJECTOR"),
    P0272("Cylinder 4 Injector Circuit High"),
    P0273("Cylinder 4 Contribution/Balance Fault"),
    P0274("Cylinder 5 Injector Circuit Low"),
    P0275("Cylinder 5 Injector Circuit High"),
    P0276("Cylinder 5 Contribution/Balance Fault"),
    P0277("Cylinder 6 Injector Circuit Low"),
    P0278("Cylinder 6 Injector Circuit High"),
    P0279("Cylinder 6 Contribution/Balance Fault"),
    P0280("Cylinder 7 Injector Circuit Low"),
    P0281("Cylinder 7 Injector Circuit High"),
    P0282("Cylinder 7 Contribution/Balance Fault"),
    P0283("Cylinder 8 Injector Circuit Low"),
    P0284("Cylinder 8 Injector Circuit High"),
    P0285("Cylinder 8 Contribution/Balance Fault"),
    P0286("Cylinder 9 Injector Circuit Low"),
    P0287("Cylinder 9 Injector Circuit High"),
    P0288("Cylinder 9 Contribution/Balance Fault"),
    P0289("Cylinder 10 Injector Circuit Low"),
    P0290("Cylinder 10 Injector Circuit High"),
    P0291("Cylinder 10 Contribution/Balance Fault"),
    P0292("Cylinder 11 Injector Circuit Low"),
    P0293("Cylinder 11 Injector Circuit High"),
    P0294("Cylinder 11 Contribution/Balance Fault"),
    P0295("Cylinder 12 Injector Circuit Low"),
    P0296("Cylinder 12 Injector Circuit High"),
    P0299("SC FUNCTION"),
    P0300("MULTI CYL MISFIRE"),
    P0301("CYL 1 MISFIRE"),
    P0302("CYL 2 MISFIRE"),
    P0303("CYL 3 MISFIRE"),
    P0304("CYL 4 MISFIRE"),
    P0305("CYL 5 MISFIRE"),
    P0306("CYL 6 MISFIRE"),
    P0307("CYL 7 MISFIRE"),
    P0308("CYL 8 MISFIRE"),
    P0309("Cylinder 8 Misfire Detected"),
    P0310("Cylinder 9 Misfire Detected"),
    P0311("Cylinder 10 Misfire Detected"),
    P0312("Cylinder 11 Misfire Detected"),
    P0320("Cylinder 12 Misfire Detected"),
    P0321("Ignition/Distributor Engine Speed Input Circuit Malfunction"),
    P0322("Ignition/Distributor Engine Speed Input Circuit Range/Performance"),
    P0323("Ignition/Distributor Engine Speed Input Circuit No Signal"),
    P0325("KNOCK SEN/CIRC-B1"),
    P0326("KNOCK SENSOR 1 B1"),
    P0327("KNOCK SEN/CIRC-B1"),
    P0328("KNOCK SEN/CIRC-B1"),
    P0329("Knock Sensor 1 Circuit High Input (Bank 1 or Single Sensor)"),
    P0330("KNOCK SEN/CIRC-B2"),
    P0331("P0331"),
    P0332("KNOCK SEN/CIRC-B2"),
    P0333("KNOCK SEN/CIRC-B2"),
    P0334("Knock Sensor 2 Circuit High Input (Bank 2)"),
    P0335("CKP SEN/CIRCUIT"),
    P0336("Crankshaft Position Sensor A Circuit Malfunction"),
    P0337("Crankshaft Position Sensor A Circuit Range/Performance"),
    P0338("Crankshaft Position Sensor A Circuit Low Input"),
    P0339("Crankshaft Position Sensor A Circuit High Input"),
    P0340("CMP SEN/CIRC-B1"),
    P0341("Camshaft Position Sensor Circuit Malfunction"),
    P0342("Camshaft Position Sensor Circuit Range/Performance"),
    P0343("Camshaft Position Sensor Circuit Low Input"),
    P0344("Camshaft Position Sensor Circuit High Input"),
    P0345("CMP SEN/CIRC-B2"),
    P0350("IGN SIGNAL-PRIMARY"),
    P0351("IGNITION COIL A"),
    P0352("IGNITION COIL B"),
    P0353("IGNITION COIL C"),
    P0354("IGNITION COIL D"),
    P0355("Ignition Coil D Primary/Secondary Circuit Malfunction"),
    P0356("Ignition Coil E Primary/Secondary Circuit Malfunction"),
    P0357("Ignition Coil F Primary/Secondary Circuit Malfunction"),
    P0358("Ignition Coil G Primary/Secondary Circuit Malfunction"),
    P0359("Ignition Coil H Primary/Secondary Circuit Malfunction"),
    P0360("Ignition Coil I Primary/Secondary Circuit Malfunction"),
    P0361("Ignition Coil J Primary/Secondary Circuit Malfunction"),
    P0362("Ignition Coil K Primary/Secondary Circuit Malfunction"),
    P0365("CAMSHAFT POSITION SENSOR B B1"),
    P0370("Ignition Coil L Primary/Secondary Circuit Malfunction"),
    P0371("Timing Reference High Resolution Signal A Malfunction"),
    P0372("Timing Reference High Resolution Signal A Too Many Pulses"),
    P0373("Timing Reference High Resolution Signal A Too Few Pulses"),
    P0374("Timing Reference High Resolution Signal A Intermittent/Erratic Pulses"),
    P0375("Timing Reference High Resolution Signal A No Pulses"),
    P0376("Timing Reference High Resolution Signal B Malfunction"),
    P0377("Timing Reference High Resolution Signal B Too Many Pulses"),
    P0378("Timing Reference High Resolution Signal B Too Few Pulses"),
    P0379("Timing Reference High Resolution Signal B Intermittent/Erratic Pulses"),
    P0380("Timing Reference High Resolution Signal B No Pulses"),
    P0381("Glow Plug/Heater Circuit \"A\" Malfunction"),
    P0382("Glow Plug/Heater Indicator Circuit Malfunction"),
    P0385("CKP SENSOR B"),
    P0386("CKP SENSOR B"),
    P0387("Crankshaft Position Sensor B Circuit Range/Performance"),
    P0388("Crankshaft Position Sensor B Circuit Low Input"),
    P0389("Crankshaft Position Sensor B Circuit High Input"),
    P0390("Camshaft Position Sensor &quot;B&quot; Circuit"),
    P0400("EGR SYSTEM"),
    P0401("EGR SYSTEM"),
    P0402("EGRC-BPT VALVE"),
    P0403("EGR VOL CON/V CIR"),
    P0404("Exhaust Gas Recirculation Control Circuit Range/Performance"),
    P0405("EGR TEMP SEN/CIRC"),
    P0406("EGR TEMP SEN/CIRC"),
    P0407("P0407"),
    P0408("Exhaust Gas Recirculation Sensor B Circuit Low"),
    P040B("EGR TEMPERATURE SENSOR A"),
    P040C("EGR TEMPERATURE SENSOR A"),
    P040D("EGR TEMPERATURE SENSOR A"),
    P0410("AIR PUMP CONTROL"),
    P0411("SCNDRY AIR SYSEM"),
    P0412("PAIRC-S/V(PUMP)"),
    P0413("Secondary Air Injection System Switching Valve A Circuit Malfunction"),
    P0414("Secondary Air Injection System Switching Valve A Circuit Open"),
    P0415("Secondary Air Injection System Switching Valve A Circuit Shorted"),
    P0416("Secondary Air Injection System Switching Valve B Circuit Malfunction"),
    P0417("Secondary Air Injection System Switching Valve B Circuit Open"),
    P0418("Secondary Air Injection System Switching Valve B Circuit Shorted"),
    P0419("Secondary Air Injection System Relay \"A\" Circuit Malfunction"),
    P0420("TW CATALYST SYS-B1"),
    P0421("Catalyst System Efficiency Below Threshold (Bank 1)"),
    P0422("Warm Up Catalyst Efficiency Below Threshold (Bank 1)"),
    P0423("Main Catalyst Efficiency Below Threshold (Bank 1)"),
    P0424("Heated Catalyst Efficiency Below Threshold (Bank 1)"),
    P0426("Heated Catalyst Temperature Below Threshold (Bank 1)"),
    P0427("Catalyst Temperature Sensor Range/Performance (Bank 1)"),
    P0428("Catalyst Temperature Sensor Low Input (Bank 1)"),
    P0430("TW CATALYST SYS-B2"),
    P0431("Catalyst System Efficiency Below Threshold (Bank 2)"),
    P0432("Warm Up Catalyst Efficiency Below Threshold (Bank 2)"),
    P0433("Main Catalyst Efficiency Below Threshold (Bank 2)"),
    P0434("Heated Catalyst Efficiency Below Threshold (Bank 2)"),
    P0436("Heated Catalyst Temperature Below Threshold (Bank 2)"),
    P0437("Catalyst Temperature Sensor Range/Performance (Bank 2)"),
    P0438("Catalyst Temperature Sensor Low Input (Bank 2)"),
    P0440("EVAP SMALL LEAK"),
    P0441("EVAP PURG FLOW/MON"),
    P0442("EVAP SMALL LEAK"),
    P0443("PURG VOLUME CONT/V"),
    P0444("PURG VOLUME CONT/V"),
    P0445("PURG VOLUME CONT/V"),
    P0446("VENT CONTROL VALVE"),
    P0447("VENT CONTROL VALVE"),
    P0448("VENT CONTROL VALVE"),
    P044A("Exhaust Gas Recirculation Sensor &quot;C&quot; Circuit"),
    P044B("Exhaust Gas Recirculation Sensor &quot;C&quot; Circuit Range/Performance"),
    P044C("Exhaust Gas Recirculation Sensor &quot;C&quot; Circuit Low"),
    P044D("Exhaust Gas Recirculation Sensor &quot;C&quot; Circuit High"),
    P044E("Exhaust Gas Recirculation Sensor &quot;C&quot; Circuit Intermittent/Erratic"),
    P0450("EVAPO SYS PRES SEN"),
    P0451("EVAP SYS PRES SEN"),
    P0452("EVAP SYS PRES SEN"),
    P0453("EVAP SYS PRES SEN"),
    P0454("Evaporative Emission Control System Pressure Sensor High Input"),
    P0455("EVAP GROSS LEAK"),
    P0456("EVAP VERY SML LEAK"),
    P0460("FUEL LEV SEN SLOSH"),
    P0461("FUEL LEVEL SENSOR"),
    P0462("FUEL LEVL SEN/CIRC"),
    P0463("FUEL LEVL SEN/CIRC"),
    P0464("FUEL LEVL SEN/CIRC"),
    P0465("Fuel Level Sensor Circuit Intermittent"),
    P0466("Purge Flow Sensor Circuit Malfunction"),
    P0467("Purge Flow Sensor Circuit Range/Performance"),
    P0468("Purge Flow Sensor Circuit Low Input"),
    P0469("Purge Flow Sensor Circuit High Input"),
    P046E("P046E"),
    P046F("P046F"),
    P0470("Purge Flow Sensor Circuit Intermittent"),
    P0471("Exhaust Pressure Sensor Malfunction"),
    P0472("Exhaust Pressure Sensor Range/Performance"),
    P0473("Exhaust Pressure Sensor Low"),
    P0474("Exhaust Pressure Sensor High"),
    P0475("Exhaust Pressure Sensor Intermittent"),
    P0476("Exhaust Pressure Control Valve Malfunction"),
    P0477("Exhaust Pressure Control Valve Range/Performance"),
    P0478("Exhaust Pressure Control Valve Low"),
    P0479("Exhaust Pressure Control Valve High"),
    P0480("Exhaust Pressure Control Valve Intermittent"),
    P0481("Cooling Fan 1 Control Circuit Malfunction"),
    P0482("Cooling Fan 2 Control Circuit Malfunction"),
    P0483("Cooling Fan 3 Control Circuit Malfunction"),
    P0484("Cooling Fan Rationality Check Malfunction"),
    P0485("Cooling Fan Circuit Over Current"),
    P0486("P0486"),
    P0491("SCNDY AIR SYS-B1"),
    P0492("SCNDY AIR SYS-B2"),
    P0495("Fan speed"),
    P0500("VEHICLE SPEED SEN A"),
    P0501("VEHICLE SPEED SEN A"),
    P0502("Vehicle Speed Sensor Range/Performance"),
    P0503("Vehicle Speed Sensor Low Input"),
    P0504("BRAKE SW/CIRCUIT"),
    P0505("Vehicle Speed Sensor Intermittent/Erratic/High"),
    P0506("ISC SYSTEM"),
    P0507("ISC SYSTEM"),
    P050A("COLD START CONTROL"),
    P050B("COLD START CONTROL"),
    P050E("COLD START CONTROL"),
    P0510("CLOSED TP SW/CIRC"),
    P0520("EOP SENSOR/SWITCH"),
    P0521("Engine Oil Pressure Sensor/Switch Circuit Malfunction"),
    P0522("Engine Oil Pressure Sensor/Switch Circuit Range/Performance"),
    P0523("Engine Oil Pressure Sensor/Switch Circuit Low Voltage"),
    P0524("ENGINE OIL PRESSURE"),
    P0525("P0525"),
    P0527("COOLING FAN SPD SEN"),
    P052A("CAMSHAFT POSITION TIMING B1"),
    P052B("CAMSHAFT POSITION TIMING B1"),
    P052C("CAMSHAFT POSITION TIMING B2"),
    P052D("CAMSHAFT POSITION TIMING B2"),
    P0530("P0530"),
    P0531("A/C Refrigerant Pressure Sensor Circuit Malfunction"),
    P0532("P0532"),
    P0533("P0533"),
    P0534("A/C Refrigerant Pressure Sensor Circuit High Input"),
    P0544("EXHAUST GAS TEMP SENSOR 1 B1"),
    P0545("EXHAUST GAS TEMP SENSOR 1 B1"),
    P0546("EXHAUST GAS TEMP SENSOR 1 B1"),
    P0547("EXHAUST GAS TEMP SENSOR 1 B2"),
    P0548("EXHAUST GAS TEMP SENSOR 1 B2"),
    P0549("EXHAUST GAS TEMP SENSOR 1 B2"),
    P0550("PW ST P SEN/CIRC"),
    P0551("Power Steering Pressure Sensor Circuit Malfunction"),
    P0552("Power Steering Pressure Sensor Circuit Range/Performance"),
    P0553("Power Steering Pressure Sensor Circuit Low Input"),
    P0554("Power Steering Pressure Sensor Circuit High Input"),
    P0555("BRAKE BSTR PRES SEN/CIRC"),
    P0560("Power Steering Pressure Sensor Circuit Intermittent"),
    P0561("System Voltage Malfunction"),
    P0562("System Voltage Unstable"),
    P0563("SYSTEM VOLTAGE"),
    P0564("P0564"),
    P0565("System Voltage High"),
    P0566("Cruise Control On Signal Malfunction"),
    P0567("Cruise Control Off Signal Malfunction"),
    P0568("Cruise Control Resume Signal Malfunction"),
    P0569("Cruise Control Set Signal Malfunction"),
    P0570("Cruise Control Coast Signal Malfunction"),
    P0571("BRAKE SW"),
    P0572("Cruise Control/Brake Switch A Circuit Malfunction"),
    P0573("Cruise Control/Brake Switch A Circuit Low"),
    P0574("Cruise Control/Brake Switch A Circuit High"),
    P0575("Cruise Control Related Malfunction"),
    P0576("Cruise Control Related Malfunction"),
    P0578("Cruise Control Related Malfunction"),
    P0579("Cruise Control Related Malfunction"),
    P0580("Cruise Control Related Malfunction"),
    P059F("ACTIVE GRILLE AIR SHUTTER A"),
    P0600("A/T COMM LINE"),
    P0601("Serial Communication Link Malfunction"),
    P0602("Control Module Read Only Memory(ROM)"),
    P0603("ECM BACK UP/CIRCUIT"),
    P0604("ECM"),
    P0605("ECM"),
    P0606("CONTROL MODULE"),
    P0607("ECM"),
    P0608("PCM Processor Fault"),
    P0609("Control Module VSS Output \"A\" Malfunction"),
    P060A("CONTROL MODULE"),
    P060B("CONTROL MODULE"),
    P0611("FIC MODULE"),
    P0620("GENERATOR"),
    P0621("Generator Control Circuit Malfunction"),
    P0622("Generator Lamp \"L\" Control Circuit Malfunction"),
    P0627("SUB FUEL PUMP CIRC"),
    P0629("SUB FUEL PUMP CIRC"),
    P062A("SUB FUEL PUMP CIRC"),
    P062B("ECM"),
    P062F("CONTROL MODULE"),
    P0643("SENSOR POWER/CIRC"),
    P0650("MIL/CIRC"),
    P0654("Malfunction Indicator Lamp (MIL) Control Circuit Malfunction"),
    P0655("Engine RPM Output Circuit Malfunction"),
    P0656("Engine Hot Lamp Output Control Circuit Malfucntion"),
    P065B("GENERATOR"),
    P06DA("P06DA"),
    P06DB("P06DB"),
    P0700("TRANSMISSION CONT"),
    P0701("Transmission Control System Malfunction"),
    P0702("Transmission Control System Range/Performance"),
    P0703("Transmission Control System Electrical"),
    P0704("Torque Converter/Brake Switch B Circuit Malfunction"),
    P0705("T/M RANGE SENSOR A"),
    P0706("Transmission Range Sensor Circuit malfunction (PRNDL Input)"),
    P0707("Transmission Range Sensor Circuit Range/Performance"),
    P0708("Transmission Range Sensor Circuit Low Input"),
    P0709("Transmission Range Sensor Circuit High Input"),
    P0710("FLUID TEMP SENSOR A"),
    P0711("FLUID TEMP SENSOR A"),
    P0712("Transmission Fluid Temperature Sensor Circuit Range/Performance"),
    P0713("Transmission Fluid Temperature Sensor Circuit Low Input"),
    P0714("Transmission Fluid Temperature Sensor Circuit High Input"),
    P0715("INPUT SPEED SENSOR A"),
    P0716("Input/Turbine Speed Sensor Circuit Malfunction"),
    P0717("INPUT SPEED SENSOR A"),
    P0718("Input/Turbine Speed Sensor Circuit No Signal"),
    P0719("Input/Turbine Speed Sensor Circuit Intermittent"),
    P0720("OUTPUT SPEED SENSOR"),
    P0721("Output Speed Sensor Circuit Malfunction"),
    P0722("OUTPUT SPEED SENSOR"),
    P0723("Output Speed Sensor No Signal"),
    P0724("Output Speed Sensor Intermittent"),
    P0725("ENGINE SPEED"),
    P0726("ENGINE SPEED"),
    P0727("Engine Speed Input Circuit Range/Performance"),
    P0728("Engine Speed Input Circuit No Signal"),
    P0729("6GR INCORRECT RATIO"),
    P0730("INCORRECT GR RATIO"),
    P0731("1GR INCORRECT RATIO"),
    P0732("2GR INCORRECT RATIO"),
    P0733("3GR INCORRECT RATIO"),
    P0734("4GR INCORRECT RATIO"),
    P0735("5GR INCORRECT RATIO"),
    P0736("A/T REV GR FNCTN"),
    P0740("TORQUE CONVERTER"),
    P0741("Torque Converter Clutch Circuit Malfuction"),
    P0742("Torque Converter Clutch Circuit Performance or Stuck Off"),
    P0743("Torque Converter Clutch Circuit Stuck On"),
    P0744("TORQUE CONVERTER"),
    P0745("PC SOLENOID A"),
    P0746("PC SOLENOID A"),
    P0747("Pressure Control Solenoid Performance or Stuck Off"),
    P0748("Pressure Control Solenoid Stuck On"),
    P0749("Pressure Control Solenoid Electrical"),
    P0750("SHIFT SOLENOID A"),
    P0751("Shift Solenoid A Malfunction"),
    P0752("Shift Solenoid A Performance or Stuck Off/"),
    P0753("1-2 Shift Solenoid Valve Performance"),
    P0754("Shift Solenoid A Stuck On"),
    P0755("SHIFT SOLENOID B"),
    P0756("1-2 Shift Solenoid Circuit Electrical"),
    P0757("Shift Solenoid A Intermittent"),
    P0758("Shift Solenoid B Malfunction"),
    P0759("Shift Solenoid B Performance or Stuck Off/"),
    P0760("SHIFT SOLENOID C"),
    P0761("Shift Solenoid B Stuck On"),
    P0762("SHIFT SOLENOID C"),
    P0763("Shift Solenoid B Intermittent"),
    P0764("Shift Solenoid C Malfunction"),
    P0765("SHIFT SOLENOID D"),
    P0766("Shift Solenoid C Stuck On"),
    P0767("Shift Solenoid C Electrical"),
    P0768("Shift Solenoid C Intermittent"),
    P0769("Shift Solenoid D Malfunction"),
    P0770("SHIFT SOLENOID E"),
    P0771("Shift Solenoid D Stuck On"),
    P0772("Shift Solenoid D Electrical"),
    P0773("Shift Solenoid D Intermittent"),
    P0774("Shift Solenoid E Malfunction"),
    P0775("PC SOLENOID B"),
    P0776("PC SOLENOID B"),
    P0777("Shift Solenoid E Electrical"),
    P0778("PC SOLENOID B"),
    P0779("Pressure Control Solenoid B Malfunction"),
    P0780("SHIFT"),
    P0781("Pressure Control Solenoid B Stuck On"),
    P0782("Pressure Control Solenoid B Electrical"),
    P0783("Pressure Control Solenoid B Intermittent"),
    P0784("Shift Malfunction"),
    P0785("1-2 Shift Malfunction"),
    P0786("2-3 Shift Malfunction"),
    P0787("3-4 Shift Malfunction"),
    P0788("4-5 Shift Malfunction"),
    P0789("Shift/Timing Solenoid Malfunction/ 3-2 Shift Solenoid Circuit Electrical"),
    P0790("Shift/Timing Solenoid Range/Performance"),
    P0795("PC SOLENOID C"),
    P0797("PC SOLENOID C"),
    P0801("Shift/Timing Solenoid Low"),
    P0803("Shift/Timing Solenoid High"),
    P0804("Shift/Timing Solenoid Intermittent"),
    P0820("GR LVR X-Y POS SEN"),
    P0830("CLUTCH INTLCK SW/CIRC"),
    P0833("CLUTCH P/P SW/CIRC"),
    P0840("FLUID PRESS SEN/SW A"),
    P0841("FLUID PRESS SEN/SW A"),
    P0845("FLUID PRESS SEN/SW B"),
    P0850("P-N POS SW/CIRCUIT"),
    P0882("TCM POWER INPUT SIG"),
    P0A1E("STR/GEN C/M"),
    P0A8F("14V PWR MDL SYS"),
    P0AC4("HV ECU MIL REQUEST"),
    P1005("FUEL SHUTOFF/V B"),
    P1006("FUEL SHUTOFF/V C"),
    P100A("VVEL SYSTEM-B1"),
    P100B("VVEL SYSTEM-B2"),
    P100C("V/T OFFSET DATA NOT WRITTEN"),
    P1031("A/F SEN1 HTR (B1)"),
    P1032("A/F SEN1 HTR (B1)"),
    P1033("B/V POS SEN 1-2 CORRELATION"),
    P1034("BYPASS VALVE POSITION SENSOR"),
    P1035("BYPASS VALVE POSITION SENSOR"),
    P1040("BRAKE PRESSURE SEN"),
    P1044("BYPASS VALVE POSITION SENSOR 2"),
    P1045("BYPASS VALVE POSITION SENSOR 2"),
    P1048("P1048"),
    P1049("P1049"),
    P1051("A/F SEN1 HTR (B2)"),
    P1052("A/F SEN1 HTR (B2)"),
    P1065("ECM BACK UP/CIRCUIT"),
    P1075("VVL S/V"),
    P1078("EXH TIM SEN/CIR-B1"),
    P1080("EXH/V TIM CONT-B1"),
    P1084("EXH TIM SEN/CIR-B2"),
    P1086("EXH/V TIM CONT-B2"),
    P1087("VVEL SYSTEM-B1"),
    P1088("VVEL SYSTEM-B2"),
    P1089("VVEL POS SEN/CIRC-B1"),
    P1090("VVEL ACTR MOT-B1"),
    P1091("VVEL ACTR MOT PWR"),
    P1092("VVEL POS SEN/CIRC-B2"),
    P1093("VVEL ACTR MOT-B2"),
    P10FF("SC MAGNETIC CLUTCH"),
    P1100("Normal/Performance Switch Circuit Malfunction"),
    P1101("Reverse Inhibit Control Circuit Malfunction"),
    P1102("MAF SEN/CIRCUIT"),
    P1103("MAP SENSOR"),
    P1104("MAP SENSOR"),
    P1105("MAP/BAR SW SOL/CIR"),
    P1106("BARO PRES SEN/CIRC"),
    P1107("MAF Sensor In Range But Lower Than Expected"),
    P1108("MAP SENSOR"),
    P1109("MAP/BAR SW SOL/CIR"),
    P1110("INT/V TIM CONT-B1"),
    P1111("INT/V TIM V/CIR-B1"),
    P1112("Dual Alternator Lower Circuit Malfunction/ Manifold Absolute Pressure (MAP) Sensor Circuit Intermittent Low Voltage"),
    P1113("Dual Alternator Battery Lamp Circuit Malfunction"),
    P1114("IAT - B Sensor Intermittent"),
    P1115("IAT Sensor (D/C) Open/Short"),
    P1116("Intake Air Temperature (IAT) Sensor Circuit Intermittent High Voltage"),
    P1117("Intake Air Temperature (IAT) Sensor Circuit Intermittent Low Voltage"),
    P1118("IAT Sensor Open/Short"),
    P1119("RADI TEMP SEN/CIRC"),
    P1120("ETC FUNCTION/CIRC"),
    P1121("ETC ACTR"),
    P1122("ETC FUNCTION/CIRC"),
    P1123("ETC MOT RLY/CIRC"),
    P1124("ETC MOT PWR"),
    P1125("MOT THRT SEN/CT"),
    P1126("P1126"),
    P1127("ETC MOT"),
    P1128("ETC MOT"),
    P1129("ETC MOT GND"),
    P1130("SWIRL CONT SOL/V"),
    P1131("SWIRL CONT SOL/V"),
    P1132("VARI SWL CON/SV-B1"),
    P1133("VARI SWL CON/SV-B2"),
    P1134("HO2S1 (B1)"),
    P1135("INT/V TIM CONT-B2"),
    P1136("INT/V TIM V/CIR-B2"),
    P1137("SWL CON/V POSI SEN"),
    P1138("SWIRL CONT VALVE"),
    P1139("HO2S Transition Time Ratio Sensor 1"),
    P1140("INTK TIM S/CIRC-B1"),
    P1141("Fan Control Circuit Malfunction"),
    P1142("Lack Of HO2S Switch - Sensor Indicates Lean"),
    P1143("HO2S1 (B1)"),
    P1144("HO2S1 (B1)"),
    P1145("INTK TIM S/CIRC-B2"),
    P1146("HO2S2 (B1)"),
    P1147("HO2S2 (B1)"),
    P1148("CLOSED LOOP-B1"),
    P1150("Water In Fuel Condition"),
    P1151("Fuel Restriction Indicator Circuit Malfunction"),
    P1152("Fuel Restriction Condition"),
    P1153("Air Assist Control Valve Range/Performance"),
    P1154("HO2S1 (B2)"),
    P1155("Lack Of HO2S21 Switch - Adaptive Fuel At Limit"),
    P1156("Lack Of HO2S21 Switch - Sensor Indicates Lean"),
    P1157("Lack Of HO2S21 Switch - Sensor Indicates Rich"),
    P1158("Bank 2 Fuel Control Shifted Lean"),
    P1159("Bank 2 Fuel Control Shifted Rich"),
    P1163("HO2S1 (B2)"),
    P1164("HO2S1 (B2)"),
    P1165("SWL CON VC SW/CIRC"),
    P1166("HO2S2 (B2)"),
    P1167("HO2S2 (B2)"),
    P1168("CLOSED LOOP-B2"),
    P1169("HO2S3 (B1)"),
    P1170("HO2S3 (B1)"),
    P1171("INTAKE ERROR"),
    P1172("Invalid Test"),
    P1173("Fuel Rail Sensor In-Range Low Failure"),
    P1174("Fuel Rail Sensor In-Range High Failure"),
    P1175("ESO - Engine Shut Off Solenoid Fault"),
    P1176("Rotor Sensor Fault"),
    P1177("Rotor Control Fault"),
    P1178("Rotor Calibration Fault"),
    P117A("AIR FUEL RATIO B1"),
    P117B("AIR FUEL RATIO B2"),
    P1180("Cam Sensor Fault"),
    P1181("CYL TEMP SEN"),
    P1182("Cam Calibration Fault"),
    P1183("Synchronization Fault"),
    P1184("GAS TEMP SEN/CYL"),
    P1185("Fuel Delivery System Malfunction - Low"),
    P1186("Fuel Delivery System Malfunction - High"),
    P1187("Fuel Shut Off Solenoid Malfunction"),
    P1188("Engine Oil Temperature Circuit Malfunction"),
    P1189("GAS TEMP SEN/ENG"),
    P1190("GAS PRES SEN/ENG"),
    P1191("GAS LINE PRESS"),
    P1192("FUEL PRES SEN B"),
    P1193("FUEL PRES SEN B"),
    P1194("GAS PRES SEN/CYL"),
    P1195("ENGINE NOT START"),
    P1196("POOR ENGINE POWER"),
    P1197("FUEL_RUN_OUT"),
    P1198("EGR Drive Overcurrent"),
    P1199("ECU A/D Converter"),
    P119A("P119A"),
    P119B("P119B"),
    P119C("P119C"),
    P1200("FUEL PUMP"),
    P1201("Key Off Voltage High"),
    P1202("Key Off Voltage Low"),
    P1203("Pump Rotor Control Underfueling"),
    P1204("Fuel Level Input Circuit Low"),
    P1205("Injector Control Circuit"),
    P1206("Injector Circuit Open / Shorted - Cylinder #1"),
    P1209("Injector Circuit Open / Shorted - Cylinder #2"),
    P120A("FP RELAY 2"),
    P120B("FP RELAY 3"),
    P1210("TACM SW SIGNALS"),
    P1211("TCS C/U FUNCTN"),
    P1212("TCS/CIRC"),
    P1213("INJECTOR D/U"),
    P1214("INJECTOR D/U"),
    P1215("FUEL CUT/V(ENG)"),
    P1216("INJECTOR D/U"),
    P1217("OVER HEAT"),
    P1218("Start Injector Circuit Malfunction"),
    P1219("Pedal Position Sensor B Circuit Intermittent"),
    P1220("FPCM/CIRCUIT"),
    P1221("FUEL CUT VALVE/CYL"),
    P1222("FUEL CUT VALVE/CYL"),
    P1223("TP SEN 2/CIRC"),
    P1224("TP SEN 2/CIRC"),
    P1225("CTP LEARNING-B1"),
    P1226("CTP LEARNING-B1"),
    P1227("APP SEN 2/CIRC"),
    P1228("APP SEN 2/CIRC"),
    P1229("SENSOR POWER/CIRC"),
    P1230("PRESS REG/CONT S/V"),
    P1231("Control Sleeve Sensor Malfunction"),
    P1232("PRESS REGURATOR"),
    P1233("P1233"),
    P1234("CTP LEARNING-B2"),
    P1235("CTP LEARNING-B2"),
    P1236("ETC MOT-B2"),
    P1237("ETC FNCTN/CIRC-B2"),
    P1238("ETC ACTR-B2"),
    P1239("TP SENSOR-B2"),
    P1240("Fuel Pump Control Out Of Range"),
    P1241("Fuel Pump Control Out Of Range"),
    P1242("Fuel Pump Secondary Circuit Malfunction"),
    P1243("Fuel Pump Secondary Circuit Malfunction"),
    P1244("Speed Fuel Pump Positive Feed Fault"),
    P1245("Sensor Power Supply Malfunction"),
    P1246("Sensor Power Supply Low Input"),
    P1247("Sensor Power Supply High Input"),
    P1248("Second Fuel Pump Faulty or Ground Fault"),
    P1249("Alternator Load Input Failed High"),
    P1250("Alternator Load Input Failed Low"),
    P1251("Alternator Load Input Failed"),
    P1252("Turbo Boost Pressure Low"),
    P1253("Turbo Boost Pressure Not Detected"),
    P1254("Wastegate Control Valve Performance"),
    P1255("PRC Solenoid Circuit Malfunction"),
    P1256("Air Mixture Solenoid Circuit Malfunction"),
    P1257("Pedal Correlation PDS1 and LPDS High"),
    P1258("Pedal Correlation PDS1 and LPDS Low"),
    P1259("Pedal Correlation PDS2 and LPDS High"),
    P1260("Pedal Correlation PDS2 and LPDS Low"),
    P1261("MAIN FUEL INJ"),
    P1262("Pedal Correlation PDS2 and HPDS"),
    P1263("TC SYSTEM-B2"),
    P1264("Immobilizer to PCM Signal Error"),
    P1265("THEFT Detected"),
    P1266("Cylinder #1 High To Low Side Short"),
    P1267("Cylinder #2 High To Low Side Short"),
    P1268("Cylinder #3 High To Low Side Short"),
    P1269("Cylinder #4 High To Low Side Short"),
    P1270("Cylinder #5 High To Low Side Short"),
    P1271("A/F SENSOR1 (B1)"),
    P1272("A/F SENSOR1 (B1)"),
    P1273("A/F SENSOR1 (B1)"),
    P1274("A/F SENSOR1 (B1)"),
    P1275("A/F SENSOR1 (B1)"),
    P1276("A/F SENSOR1 (B1)"),
    P1277("A/F SEN1 HTR (B1)"),
    P1278("A/F SENSOR1 (B1)"),
    P1279("A/F SENSOR1 (B1)"),
    P1280("Cylinder #4 High To Low Side Open"),
    P1281("A/F SENSOR1 (B2)"),
    P1282("A/F SENSOR1 (B2)"),
    P1283("A/F SENSOR1 (B2)"),
    P1284("A/F SENSOR1 (B2)"),
    P1285("A/F SENSOR1 (B2)"),
    P1286("A/F SENSOR1 (B2)"),
    P1287("A/F SEN1 HTR (B2)"),
    P1288("A/F SENSOR1 (B2)"),
    P1289("A/F SENSOR1 (B2)"),
    P1290("ETC MOT PWR-B2"),
    P1291("ETC MOT PWR-B2"),
    P1292("Fuel Pulse In Range But Higher Than Expected"),
    P1293("Cylinder Head Temp Sensor Out Of Self Test Range"),
    P1294("Cylinder Head Temp Sensor High Input"),
    P1295("Cylinder Head Temp Sensor Low Input"),
    P1296("Injector High Side Short To GND Or VBATT - Bank 1"),
    P1297("Injector High Side Short To GND Or VBATT - Bank 2"),
    P1298("Injector High Side Open - Bank 1"),
    P1299("CTP LEARNING"),
    P1300("Multi-faults - Bank 1 - With Low Side Shorts"),
    P1301("Multi-faults - Bank 2 - With Low Side Shorts"),
    P1302("Injector High Sides Shorted Together"),
    P1303("IDM Failure"),
    P1304("Cylinder Head Overtemperature Protection Active"),
    P1305("Boost Calibration Fault"),
    P1306("Boost Calibration High"),
    P1307("Boost Calibration Low"),
    P1308("EGR Calibration Fault"),
    P1309("EGR Calibration High"),
    P1313("EGR Calibration Low"),
    P1314("Kickdown Relay Pull - In Circuit Fault"),
    P1315("Kickdown Relay Hold Circuit Fault"),
    P1316("A/C Clutch Circuit Fault"),
    P1317("Misfire Monitor AICE Chip Fault"),
    P1320("IGN SIGNAL-PRIMARY"),
    P1334("TC SYSTEM-B2"),
    P1335("CKP SEN(REF)/CIRC"),
    P1336("CKP SENSOR(COG)"),
    P1340("Misfire Rate Catalyst Damage Fault - Bank 2"),
    P1341("Persistent Misfire"),
    P1345("Injector Circuit / IDM Codes Detected"),
    P1346("Injector Circuit / IDM Codes Not Updated"),
    P1347("Crank / Cam Sensor Range / Performance"),
    P1348("Camshaft Position Sensor B Circuit Malfunction"),
    P1349("Camshaft Position Sensor B Range / Performance"),
    P1350("SGC (Cam Position) Sensor Circuit Malfunction/ Crankshaft Position - Camshaft Position Correlation"),
    P1351("Fuel Level Sensor B Circuit Malfunction"),
    P1352("Fuel Level Sensor B Range / Performance"),
    P1353("Fuel Level Sensor B Circuit Low"),
    P1354("Fuel Level Sensor B Circuit High"),
    P1355("Fuel Level Sensor B Intermittent/Bypass Line Monitor"),
    P1360("IDM Input Circuit Malfunction/ Ignition Coil Control Circuit High Voltage"),
    P1361("Ignition Coil A Primary Circuit Malfunction"),
    P1362("Ignition Coil B Primary Circuit Malfunction"),
    P1363("Ignition Coil C Primary Circuit Malfunction"),
    P1364("Ignition Coil D Primary Circuit Malfunction"),
    P1365("Ignition Coil A Secondary Circuit Malfunction"),
    P1366("Ignition Control (IC) Circuit Low Voltage"),
    P1367("Ignition Coil C Secondary Circuit Malfunction"),
    P1368("Ignition Coil D Secondary Circuit Malfunction"),
    P1369("Ignition Coil Primary Circuit Failure"),
    P1370("Ignition Coil Secondary Circuit Failure"),
    P1371("Ignition Spare"),
    P1372("Ignition Spare"),
    P1373("Ignition Spare"),
    P1374("Engine Temperature Light Monitor Failure"),
    P1375("Insufficient RMP Increase During Spark Test"),
    P1376("Ignition Coil - Cylinder 1 - Early Activation Fault"),
    P1380("Ignition Coil - Cylinder 2 - Early Activation Fault"),
    P1381("Ignition Coil - Cylinder 3 - Early Activation Fault"),
    P1382("Crankshaft Position (CKP)/Ignition Coil - Cylinder 4 - Early Activation Fault"),
    P1383("Ignition Coil - Cylinder 5 - Early Activation Fault"),
    P1384("Ignition Coil - Cylinder 6 - Early Activation Fault"),
    P1385("Misfire Detected - Rough Road Data Not Available"),
    P1386("Variable Cam Timing Overadvanced (Bank #1)/ Misfire Detected - No Communication with BCM"),
    P1387("Variable Cam Timing Solenoid #1 Circuit Malfunction"),
    P1388("Variable Cam Timing Overretarded (Bank #1)"),
    P1389("VVT Solenoid A Malfunction"),
    P1390("Variable Cam Timing Solenoid B Malfunction"),
    P1391("Variable Cam Timing Overadvanced (Bank #2)"),
    P1392("Variable Cam Timing Solenoid #2 Circuit Malfunction"),
    P1393("Variable Cam Timing Overretarded (Bank #2)"),
    P1394("Glow Plug Circuit High Side Low Input"),
    P1395("Octane Adjust Pin Out Of Self Test Range"),
    P1396("Glow Plug Circuit Low Input (Bank #1)"),
    P1397("Glow Plug Circuit High Input (Bank #1)"),
    P1398("Glow Plug Circuit Low Input (Bank #2)"),
    P1399("Glow Plug Circuit High Input (Bank #2)"),
    P1400("EGRC SOLENOID/V"),
    P1401("EGR TEMP SEN/CIRC"),
    P1402("EGR SYSTEM"),
    P1403("VVT Solenoid B Circuit High Input"),
    P1404("Glow Plug Circuit High Side"),
    P1405("DPFE Circuit Low Input"),
    P1406("DPFE Circuit High Input"),
    P1407("EGR Metering Orifice Restricted"),
    P1408("DPFE Sensor Hoses Reversed"),
    P1409("IAT - B Circuit Malfunction/ Exhaust Gas Recirculation Closed Position Performance"),
    P1411("DPFE Sensor Upstream Hose Off Or Plugged"),
    P1412("2ND AIR/V CIRC"),
    P1413("Exhaust Gas Recirculation (EGR) Position Sensor Performance"),
    P1414("EGR No Flow Detected"),
    P1415("EGR Flow Out Of Self Test Range"),
    P1416("EVR Control Circuit Malfunction"),
    P1417("SAI System Incorrect Downstream Flow Detected"),
    P1418("SAI System Monitor Circuit Low Input"),
    P1419("SAI System Monitor Circuit High Input"),
    P1420("Air Pump Circuit Malfunction/ (AIR) System Bank 1"),
    P1421("COLD START CONTROL"),
    P1422("COLD START CONTROL"),
    P1423("COLD START CONTROL"),
    P1424("COLD START CONTROL"),
    P1425("COLD START CONTROL"),
    P1426("Catalyst Damage"),
    P1427("EGI Temperature Sensor Failure"),
    P1428("EGI Functionality Test Failed"),
    P1429("EGI Glow Plug Primary Failure"),
    P1430("EGI Glow Plug Secondary Failure"),
    P1433("EGI Mini - MAF Failed Out Of Range"),
    P1434("EGI Mini - MAF Failed Short Circuit"),
    P1435("EGI Mini - MAF Failed Open Circuit"),
    P1436("Electric Air Pump Primary Failure"),
    P1437("Electric Air Pump Secondary Failure"),
    P1438("A/C Refrigerant Temperature Circuit Low"),
    P1439("A/C Refrigerant Temperature Circuit High"),
    P1440("EVAP SMALL LEAK"),
    P1441("EVAP VERY SML LEAK"),
    P1442("EVAP SMALL LEAK"),
    P1443("CAN CONT VC CHK SW"),
    P1444("PURG VOLUME CONT/V"),
    P1445("Evaporative Emission (EVAP) System Flow During Non-Purge Chevrolet Only"),
    P1446("VENT CONTROL VALVE"),
    P1447("EVAP PURG FLOW/MON"),
    P1448("VENT CONTROL VALVE"),
    P1449("Purge Flow Sensor Circuit Low Input"),
    P1450("Purge Flow Sensor Circuit High Input"),
    P1451("TC/SC PR/S-EVAP PR/S"),
    P1452("ELC System Closure Valve Flow Fault"),
    P1453("ELC System 2 Fault"),
    P1454("Evaporative Check Solenoid Circuit Malfunction"),
    P1455("Unable To Bleed Up Fuel Tank Vacuum"),
    P1456("EVAP VERY SML LEAK"),
    P1457("Unable To Bleed - Up Vacuum in Tank"),
    P1460("Fuel Tank Pressure Relief Valve Malfunction"),
    P1461("Evaporative System Vacuum Test Malfunction"),
    P1462("Evap Emission Control Sys Leak Detected (Gross Leak/No Flow)"),
    P1463("Fuel Tank Temperature Sensor Circuit Malfunction"),
    P1464("FUEL LEVL SEN/CIRC"),
    P1465("Wide open throttle A/C cutoff relay circuit"),
    P1466("A/C pressure sensor circuit voltage low"),
    P1467("A/C pressure sensor circuit voltage high"),
    P1468("A/C Pressure Sensor Insufficient Pressure Change"),
    P1469("A/C Demand Out of Self Test Range"),
    P1470("A/C Relay Circuit Malfunction"),
    P1471("A/C Refrigerant Temperature Sensor/Circuit Malfunction"),
    P1472("A/C Compressor Temperature Sensor Malfunction"),
    P1473("SSPOD Open Circuit or Closed Circuit Fault"),
    P1474("Low A/C Cycling Period"),
    P1475("A/C Cycling Period Too Short"),
    P1476("Electrodrive Fan 1 Operational Failure (Driver Side)"),
    P1477("Electrodrive Fan 2 Operational Failure (Passenger Side)"),
    P1478("Fan Secondary High With Fan(s) Off"),
    P1479("Low Fan Control Primary Circuit Malfunction"),
    P1480("FAN CONT S/V CIRC"),
    P1481("Fan Relay (High) Circuit Malfunction"),
    P1482("Additional Fan Relay Circuit Malfunction"),
    P1483("Cooling Fan Driver Fault"),
    P1484("High Fan Control Primary Circuit Malfunction"),
    P1485("Fan Secondary Low with Low Fan On"),
    P1486("Fan Secondary Low With High Fan On"),
    P1487("SCP"),
    P1490("VC/V BYPASS/V"),
    P1491("VC CUT/V BYPASS/V"),
    P1492("PURG CONT S/V"),
    P1493("PURG CONT/V &amp; S/V"),
    P1494("EGRCHK Solenoid Circuit Malfunction"),
    P1495("IDLE PURG S/V CIRC"),
    P1497("GAUG ORIF S/V CIRC"),
    P1500("Secondary Switch Solenoid Circuit Malfunction"),
    P1501("APLSOL Solenoid Circuit Malfunction"),
    P1502("RCNT Solenoid Circuit Malfunction"),
    P1503("SPCUT Solenoid Circuit Malfunction"),
    P1504("TCSPL Solenoid Circuit Malfunction"),
    P1505("ISC SYSTEM/FNCTN"),
    P1506("Vehicle Speed Sensor Out Of Self Test Range"),
    P1507("INTAKE ERROR"),
    P1508("Auxillary Speed Sensor Fault"),
    P1509("Idle Air Control Circuit Malfunction"),
    P1510("Idle Air Control System At Adaptive Clip"),
    P1511("Idle Air Control Overspeed Error"),
    P1512("STARTER"),
    P1513("S/STR &amp; GENERTR OPER COUNTR"),
    P1514("Idle Control System Circuit Shorted"),
    P1515("Idle Signal Circuit Malfunction"),
    P1516("Idle Switch (Electric Control Throttle) Circuit Malfunction"),
    P1517("Intake Manifold Runner Control (Bank 1) Stuck Closed"),
    P1518("Intake Manifold Runner Control (Bank 2) Stuck Closed"),
    P1519("High Load Neutral/Drive Fault"),
    P1520("Electric Current Circuit Malfunction"),
    P1521("IMRC Input Error (Bank 1)"),
    P1522("IMRC Input Error (Bank 2)"),
    P1523("Intake Manifold Runner Control (Stuck Open)"),
    P1524("Intake Manifold Runner Control (Stuck Closed)"),
    P1525("Intake Manifold Runner Control Circuit Malfunction"),
    P1526("Variable Intake Solenoid #1 Circuit Malfunction"),
    P1527("Variable Intake Solenoid #2 Circuit Malfunction"),
    P1528("IVC Solenoid Circuit Malfunction"),
    P1529("Variable Intake Solenoid System"),
    P1530("Air Bypass Valve System"),
    P1531("A/C COMPRESSOR"),
    P1532("A/C COMP MAG CLTCH"),
    P1533("Subsidiary Throttle Valve Solenoid Circuit Malfunction"),
    P1534("SCAIR Solenoid Circuit Malfunction"),
    P1535("A/C Clutch Circuit Malfunction"),
    P1536("Invalid Test - Accelerator Pedal Movement"),
    P1537("IMCC Circuit Malfunction"),
    P1538("AAI Circuit Malfunction"),
    P1539("Inertia Switch Activated"),
    P1540("BATTERY CURRENT SENSOR B"),
    P1541("BATTERY CURRENT SENSOR B"),
    P1542("BATTERY CURRENT SENSOR B"),
    P1543("BATTERY CURRENT SENSOR B"),
    P1544("BATTERY CURRENT SENSOR B"),
    P1546("BATTERY TEMPERATURE SENSOR B"),
    P1547("BATTERY TEMPERATURE SENSOR B"),
    P1549("Parking Brake Switch Circuit Failure"),
    P1550("BAT CURRENT SENSOR"),
    P1551("BAT CURRENT SENSOR"),
    P1552("BAT CURRENT SENSOR"),
    P1553("BAT CURRENT SENSOR"),
    P1554("BAT CURRENT SENSOR"),
    P1555("ALT CHRG CONT/SYS"),
    P1556("BATTMPSEN/CIRC"),
    P1557("BATTMPSEN/CIRC"),
    P155D("GENERATOR"),
    P155E("GENERATOR VOLTAGE"),
    P155F("GENERATOR VOLTAGE"),
    P1564("ASCD SW"),
    P1565("Intake Manifold Runner Control (Bank 2) Stuck Open"),
    P1566("Power To A/C Clutch Circuit Overcurrent"),
    P1567("Air Bypass Valve Circuit Malfunction"),
    P1568("ICC COMMAND VALUE"),
    P1571("PSPS Out Of Self Test Range"),
    P1572("ASCD BRAKE SW"),
    P1573("Speed Control Command Switch Out of Range Low"),
    P1574("ASCD VHL SPD SEN"),
    P1575("BRAKE SW"),
    P1576("ASCD BRAKE SW"),
    P1577("ASCD BRAKE SW"),
    P1578("Throttle Position Not Available"),
    P1579("Throttle Position Sensor Disagreement btwn Sensors"),
    P1580("Pedal Position Out of Self Test Range"),
    P1581("Pedal Position Not Available"),
    P1582("Pedal Position Sensor Disagreement btwn Sensors"),
    P1583("ETC Power Less Than Demand"),
    P1584("ETC In Power Limiting Mode"),
    P1585("Electronic Throttle Monitor PCM Override"),
    P1586("Electronic Throttle Monitor Malfunction"),
    P1587("Electronic Throttle Monitor Data Available"),
    P1588("Electronic Throttle Monitor Cruise Disable"),
    P1589("TCU Detected IPE Circuit Malfunction"),
    P158A("G SENSOR"),
    P159A("G sensor"),
    P159B("G sensor"),
    P159C("G sensor"),
    P159D("G sensor"),
    P159F("P159F"),
    P1600("Throttle Control Unit Malfunction"),
    P1601("Throttle Control Unit Throttle Position Malfunction"),
    P1602("Throttle Control Unit Modulated Command Malfunction"),
    P1603("Throttle Control Unit Detected Loss of Return Spring"),
    P1604("TCU Unable To Control Desired Throttle Angle"),
    P1605("TP SENSOR"),
    P1606("VVEL CONTROL MODULE"),
    P1607("VVEL CONTROL MODULE"),
    P1608("VVEL SENSOR POWER/CIRC"),
    P1609("Code Word Unregestered"),
    P1610("LOCK MODE"),
    P1611("ID DISCORD,IMMU-ECM"),
    P1612("CHAIN OF ECM-IMMU"),
    P1613("ECM INT CIRC-IMMU"),
    P1614("CHAIN OF IMMU-KEY"),
    P1615("DIFFERENCE OF KEY"),
    P1616("ECM"),
    P1617("IMMU"),
    P1618("LPG SYSTEM DIAGNOSIS"),
    P1619("SBDS Interactive Codes"),
    P161B("P161B"),
    P161D("IMMOBILIZER"),
    P161E("IMMOBILIZER"),
    P161F("IMMOBILIZER"),
    P1620("SBDS Interactive Codes"),
    P1621("SBDS Interactive Codes"),
    P1622("SBDS Interactive Codes"),
    P1623("SBDS Interactive Codes"),
    P1624("SBDS Interactive Codes"),
    P1625("SBDS Interactive Codes"),
    P1626("Control Module Long Term Memory Performance/ Immobilizer Code Words Do Not Match"),
    P1627("Immobilizer ID Does Not Match"),
    P1628("Immobilizer Code Word/ID Number Write Failure"),
    P1629("Anti Theft System"),
    P162B("P162B"),
    P162C("P162C"),
    P162D("P162D"),
    P1630("B+ Supply To VCRM Fan Circuit Malfunction"),
    P1631("Theft Deterrent Fuel Enable Signal Not Received/ B+ Supply To VCRM A/C Circuit Malfunction"),
    P1632("Module Supply Voltage Out Of Range"),
    P1633("Module Ignition Supply Input Malfunction"),
    P1634("Internal Voltage Regulator Malfunction"),
    P1635("Internal Vref Malfunction"),
    P1636("Theft Deterrent Start Enable Signal Not Correct/ Main Relay Malfunction (Power Hold)"),
    P1637("Smart Alternator Faults Sensor/Circuit Malfunction"),
    P1638("KAM Voltage Too Low"),
    P1639("Data Output Link Circuit Failure"),
    P1640("Tire / Axle Ratio Out of Acceptable Range"),
    P1641("Inductive Signature Chip Communication Error"),
    P1642("Can Link ECM/ABSCM Circuit / Network Malfunction"),
    P1643("Can Link ECM/INSTM Circuit / Network Malfunction"),
    P1644("Vehicle ID Block Corrupted or Not Programmed"),
    P1645("Powertrain DTCs Available in Another Module"),
    P1650("STR MTR RELAY 2"),
    P1651("STR MTR RELAY"),
    P1652("STR MTR SYS COMM"),
    P1653("Fuel Pump Speed Control Circuit Malfunction"),
    P1654("Fuel Pump Resistor Switch Circuit Malfunction"),
    P1655("ENGINE RESTART BYPASS RELAY"),
    P1656("ENGINE RESTART BYPASS RELAY"),
    P1660("PSP Switch Input Malfunction"),
    P1661("IAC Monitor Disabled by PSP Switch Failed On"),
    P1662("Power Steering Output Circuit Malfunction"),
    P1663("Recirculation Override Circuit Malfunction"),
    P1667("Starter Disable Circuit Malfunction"),
    P1668("Output Circuit Check Signal High"),
    P1670("Output Circuit Check Signal Low"),
    P1680("IDM_EN Circuit Failure"),
    P1681("Fuel Demand Command Signal Circuit Malfunction"),
    P1682("CI Circuit Malfunction"),
    P1683("PCM - IDM Communications Error"),
    P1684("Electronic Feedback Signal Not Detected"),
    P1685("Metering Oil Pump Malfunction"),
    P1686("Metering Oil Pump Malfunction"),
    P1687("Metering Oil Pump Malfunction"),
    P1688("Metering Oil Pump Temperature Sensor Circuit Malfunction"),
    P1689("Metering Oil Pump Position Sensor Circuit Malfunction"),
    P1690("Metering Oil Pump Stepping Motor Circuit Malfunction"),
    P1691("Metering Oil Pump Stepping Motor Circuit Malfunction"),
    P1692("Metering Oil Pump Stepping Motor Circuit Malfunction"),
    P1693("Metering Oil Pump Stepping Motor Circuit Malfunction"),
    P1694("Oil Pressure Control Solenoid Circuit Malfunction"),
    P1700("CVT C/U FUNCT"),
    P1701("Turbo Pressure Control Solenoid Circuit Malfunction"),
    P1702("Turbo Control Solenoid Circuit Malfunction"),
    P1703("Turbo Charge Control Circuit Malfunction"),
    P1704("Turbo Charge Relief Circuit Malfunction"),
    P1705("TP SENSOR"),
    P1706("P-N POS SW/CIRCUIT"),
    P1707("TRS Circuit Intermittent Malfunction"),
    P1708("Brake Switch Out Of Self Test Range"),
    P1709("Digital TRS Failed to Transition States in KOEO / KOER"),
    P1711("Not in P or N During KOEO / KOER"),
    P1712("High Vehicle Speed Observed in Park"),
    P1713("Transfer Case Neutral Indicator Hard Fault Present"),
    P1714("Clutch Switch Circuit Malfunction"),
    P1715("IN PULY SPEED"),
    P1716("TURBINE REV S/CIRC"),
    P1717("Trans Torque Reduction Request Signal Malfunction"),
    P1718("TFT Sensor In Range Failure Low Value"),
    P1720("V/SP SEN(A/T OUT)"),
    P1721("SSB Inductive Signature Malfunction"),
    P1722("SSC Inductive Signature Malfunction"),
    P1723("SSD Inductive Signature Malfunction"),
    P1724("TFT Sensor In Range Failure High"),
    P1725("Vehicle Speed (Meter) Circuit Malfunction"),
    P1726("Gear 1 Incorrect Ratio"),
    P1727("Gear 2 Incorrect Ratio"),
    P1728("Gear 3 incorrect Ratio"),
    P1729("Gear 4 Incorrect Ratio"),
    P1730("INTERLOCK"),
    P1731("Insufficient Engine Speed Decrease During Self Test"),
    P1732("Coast Clutch Solenoid Inductive Signature Malfunction"),
    P1733("Transmission Slip Error"),
    P1734("7GR INCORRECT RATIO"),
    P1735("Gear Control Malfunction 2"),
    P1736("1-2 Shift Malfunction"),
    P1737("2-3 Shift Malfunction"),
    P1738("3-4 Shift Malfunction"),
    P1739("Gear Control Malfunction"),
    P1740("SLCT SOLENOID"),
    P1741("Second Gear Switch Circuit Malfunction"),
    P1742("Lockup Solenoid System"),
    P1743("Shift Time Error"),
    P1744("Slip Solenoid System"),
    P1745("Torque Converter Clutch Inductive Signature Malfunction"),
    P1746("Torque Converter Clutch Control Error"),
    P1747("Torque Converter Clutch Solenoid Failed On"),
    P1748("Torque Converter Clutch Solenoid Failied On"),
    P1749("Torque Converter Clutch System Performance"),
    P1751("SHIFT CONT/FNCTN"),
    P1752("INPUT CLUTCH SOL"),
    P1753("SHIFT CONT SOL"),
    P1754("INPUT CLUTCH SOL"),
    P1755("Pressure Control Solenoid \"A\" Short Circuit"),
    P1756("L/PRESS CONT/FNCTN"),
    P1757("FR BRAKE SOLENOID"),
    P1758("LINE PRES SOL"),
    P1759("FR/B SOLENOID FNCT"),
    P1760("OVER CLUTCH SOLENOID"),
    P1761("Shift Solenoid A Performance"),
    P1762("DRCT CLUTCH SOL"),
    P1763("CLUTH PRES SOL"),
    P1764("D/C SOLENOID FNCTN"),
    P1765("Intermediate Speed Sensor (ISS) Malfunction"),
    P1766("TCC CONT/FNCTN"),
    P1767("HLR CLUTCH SOLENOID"),
    P1768("CLUTH SW SOL"),
    P1769("HLR/C SOL FNCTN"),
    P1770("Overdrive Band Failed Off"),
    P1772("L C BRAKE SOLENOID"),
    P1774("L C BRAKE SOLENOID"),
    P1775("TOR CONV CLTCH S/V"),
    P1776("TOR CONV CLTCH S/V"),
    P1777("STEP MOTOR"),
    P1778("STEP MOTOR"),
    P1779("Clutch Solenoid Circuit Malfunction"),
    P1780("SHIFT SIG FNCTN"),
    P1781("Ignition Retard Request Duration Fault"),
    P1782("Ignition Retard Request Circuit Fault"),
    P1783("Transmission Reverse I/P Circuit Malfunction"),
    P1784("TCIL Circuit Malfunction"),
    P1785("Trans Control Switch (O/D Cancel) Out of Self Test Range"),
    P1786("4X4 Switch Out of Self Test Range"),
    P1787("P/ES Circuit Out Of Self Test Range"),
    P1788("Transmission Overtemperature Condition"),
    P1789("Transmission Mechanical Failure - First And Reverse"),
    P1790("Transmission Mechanical Failure - First And Second"),
    P1791("LINE PRESSURE"),
    P1792("2-1 Downshift Error"),
    P1793("Pressure Control Solenoid \"B\" Open Circuit"),
    P1794("Pressure Control Solenoid \"B\" Short Circuit"),
    P1795("TP (Mechanical) Circuit Malfunction"),
    P1796("TP (Electric) Circuit Malfunction"),
    P1797("Barometer Pressure Circuit Malfunction"),
    P1798("Intake Air Volume Circuit Malfunction"),
    P1799("Battery Voltage Circuit Malfunction"),
    P1800("VIAS S/V CIRC-B1"),
    P1801("VIAS S/V CIRC-B2"),
    P1802("Neutral Switch Circuit Malfunction"),
    P1803("Coolant Temperature Circuit Malfunction"),
    P1804("Hold Switch Circuit Malfunction"),
    P1805("BRAKE SW/CIRCUIT"),
    P1806("BRAKE VACUUM SEN"),
    P1807("Transmission Clutch Interlock Safety Switch Short Circuit To Battery"),
    P1808("Transmission Clutch Interlock Safety Switch Short Circuit To Ground"),
    P1809("Transmission 4-Wheel Drive High Indicator Circuit Failure"),
    P1810("Transmission 4-Wheel Drive High Indicator Open Circuit"),
    P1811("Transmission 4-Wheel Drive High Indicator Short Circuit To Battery"),
    P1812("Transmission 4-Wheel Drive High Indicator Short Circuit To Ground"),
    P1813("Transmission 4-Wheel Drive Low Indicator Circuit Failure"),
    P1814("Transmission 4-Wheel Drive Low Indicator Open Circuit"),
    P1815("TFP Valve Position Switch Circuit/ Transmission 4-Wheel Drive Low Indicator Short Circuit To Battery"),
    P1816("Transmission 4-Wheel Drive Low Indicator Short Circuit To Ground"),
    P1817("Transmission 4-Wheel Drive Mode Select Circuit Failure"),
    P1818("Transmission 4-Wheel Drive Mode Select Open Circuit"),
    P1819("Transmission 4-Wheel Drive Mode Select Short Circuit To Battery"),
    P1820("Transmission 4-Wheel Drive Mode Select Short Circuit To Ground"),
    P1821("Transmission Neutral Safety Switch Circuit Failure"),
    P1822("Transmission Neutral Safety Switch Open Circuit"),
    P1823("Transmission Neutral Safety Switch Short Circuit To Battery"),
    P1824("Transmission Neutral Safety Switch Short Circuit To Ground"),
    P1825("Transmission Transfer Case Clockwise Shift Relay Coil Circuit Failure"),
    P1826("Transmission Transfer Case Clockwise Shift Relay Coil Open Circuit"),
    P1827("Transmission Transfer Case Clockwise Shift Relay Coil Short Circuit To Battery"),
    P1828("Transmission Transfer Case Clockwise Shift Relay Coil Short Circuit To Ground"),
    P1829("Transmission 4-Wheel Drive Clutch Relay Circuit Failure"),
    P1830("Transmission 4-Wheel Drive Clutch Relay Open Circuit"),
    P1831("Transmission 4-Wheel Drive Low Clutch Relay Circuit To Battery"),
    P1832("Transmission 4-Wheel Drive Low Clutch Relay Circuit To Ground"),
    P1833("Transmission Transfer Case Counter Clockwise Shift Relay Coil Circuit Failure"),
    P1834("Transmission Transfer Case Counter Clockwise Shift Relay Coil Open Circuit"),
    P1835("Transmission Transfer Case Counter Clockwise Shift Relay Coil Short Circuit To Battery"),
    P1836("Transmission Transfer Case Counter Clockwise Shift Relay Coil Short Circuit To Ground"),
    P1837("Transmission Transfer Case Differential Lock-Up Solenoid Circuit Failure"),
    P1838("Transmission Transfer Case Differential Lock-Up Solenoid Open Circuit"),
    P1839("Transmission Transfer Case Differential Lock-Up Solenoid Short Circuit To Battery"),
    P1840("Transmission Transfer Case Differential Lock-Up Solenoid Short Circuit To Ground"),
    P1841("Transmission Transfer Case Front Shaft Speed Sensor Circuit Failure"),
    P1842("Transmission Transfer Case Rear Shaft Speed Sensor Circuit Failure"),
    P1843("Transmission Transfer Case Shift Motor Circuit Failure"),
    P1844("Transmission Transfer Case Shift Motor Open Circuit"),
    P1845("Transmission Transfer Case Shift Motor Short Circuit To Battery"),
    P1846("Transmission Transfer Case Shift Motor Short Circuit To Ground"),
    P1847("Transmission Transfer Case Differential Lock-Up Feedback Switch Circuit Failure"),
    P1848("Transmission Transfer Case Differential Lock-Up Feedback Switch Open Circuit"),
    P1849("Transmission Transfer Case Differential Lock-Up Feedback Switch Short Circuit To Battery"),
    P1850("SOL CURRENT"),
    P1851("IND SIG"),
    P1853("D-LOCK SIG"),
    P1867("Transmission Transfer Case Contact Plate Power Circuit Failure"),
    P1868("Transmission Transfer Case Contact Plate Power Open Circuit"),
    P1869("Transmission Transfer Case Contact Plate Power Short To Battery"),
    P1870("Transmission Transfer Case Contact Plate Power Short To Ground"),
    P1871("Transmission Transfer Case System Concern - Servicing Required"),
    P1872("Transmission Transfer Case Contact Plate General Circuit Failure"),
    P1873("Transmission Automatic 4-Wheel Drive Indicator (Lamp) Circuit Failure"),
    P1874("Transmission Automatic 4-Wheel Drive Indicator (Lamp) Circuit Short To Battery"),
    P1875("Transmission Component Slipping/ Transmission Mechanical Transfer Case 4x4 Switch Circuit Failure"),
    P1876("Transmission Mechanical Transfer Case 4x4 Switch Circuit Short To Battery"),
    P1877("Transmission Mechanical 4-Wheel Drive Axle Lock Lamp Circuit Failure"),
    P1878("Transmission Mechanical 4-Wheel Drive Axle Lock Lamp Circuit Short To Battery"),
    P1879("Transmission Automatic Hall Effect Sensor Power Circuit Failure"),
    P1880("Transmission Automatic Hall Effect Sensor Power Circuit Short To Battery / 4WD Low Switch Circuit Electrical"),
    P1881("Transmission Transfer Case 2-Wheel Drive Solenoid Circuit Failure"),
    P1882("Transmission Transfer Case 2-Wheel Drive Solenoid Circuit Short To Battery"),
    P1883("Transmission Transfer Case Disengaged Solenoid Circuit Failure"),
    P1884("Transmission Transfer Case Disengaged Solenoid Open Circuit"),
    P1885("Transmission Transfer Case Disengaged Solenoid Short to Battery"),
    P1886("Engine Coolant Level Switch Circuit Failure"),
    P1890("Engine Coolant Level Switch Circuit Short to Ground"),
    P1891("Engine Coolant Level Switch Circuit Failure"),
    P1900("Engine Coolant Level Lamp Circuit Short to Ground"),
    P1901("Transmission Transfer Case Disengaged Solenoid Short to Ground"),
    P1902("4X4 Initialization Failure"),
    P1903("Transmission 4WD Mode Select Return Input Circuit Failure"),
    P1904("Transmission Transfer Case Contact Plate Ground Return Open Circuit"),
    P1905("OSS Circuit Intermittent Malfunction"),
    P1906("TSS Circuit Intermittent Malfunction"),
    P1907("Pressure Control Solenoid \"B\" Intermittent Short"),
    P1908("Pressure Control Solenoid \"C\" Short Circuit"),
    P1909("Pressure Control Solenoid \"C\" Open Circuit"),
    P1910("Pressure Control Solenoid \"C\" Intermittent Short"),
    P1911("Kickdown Pull Relay Open or Short Circuit to Ground"),
    P1912("Kickdown Hold Relay Open or Short Circuit to Ground"),
    P1913("Transmission Pressure Circuit Solenoid Open or Short to Ground"),
    P1914("Trans Temp Sensor Circuit Open or Shorted to Pwr or Gnd"),
    P1915("VFS A Pressure Output Failed Low"),
    P1916("VFS B Pressure Output Failed Low"),
    P1917("VFS C Pressure Output Failed Low"),
    P1918("Pressure Switch A Circuit Malfunction"),
    P1FFF("ENGINE STALL"),
    P2004("P2004"),
    P2008("P2008"),
    P2011("SWIRL CONT/V (B2)"),
    P2014("P2014"),
    P2016("IN/MANIFOLD RUNNER POS SEN B1"),
    P2017("IN/MANIFOLD RUNNER POS SEN B1"),
    P2018("IN/MANIFOLD RUNNER POS SEN B1"),
    P2080("EXHAUST GAS TEMP SENSOR 1 B1"),
    P2081("EXHAUST GAS TEMP SENSOR 1 B1"),
    P2082("EXHAUST GAS TEMP SENSOR 1 B2"),
    P2083("EXHAUST GAS TEMP SENSOR 1 B2"),
    P2096("POST CATALYST FUEL TRIM SYS B1"),
    P2097("POST CATALYST FUEL TRIM SYS B1"),
    P2098("POST CATALYST FUEL TRIM SYS B2"),
    P2099("POST CATALYST FUEL TRIM SYS B2"),
    P2100("ETC MOT PWR-B1"),
    P2101("ETC FNCTN/CIRC-B1"),
    P2103("ETC MOT PWR-B1"),
    P2109("CTP LEARNING"),
    P2118("ETC MOT-B1"),
    P2119("ETC ACTR-B1"),
    P2122("APP SEN 1/CIRC"),
    P2123("APP SEN 1/CIRC"),
    P2127("APP SEN 2/CIRC"),
    P2128("APP SEN 2/CIRC"),
    P2132("TP SEN 1/CIRC-B2"),
    P2133("TP SEN 1/CIRC-B2"),
    P2135("TP SENSOR-B1"),
    P2138("APP SENSOR"),
    P2159("VEHICLE SPEED SEN B"),
    P2162("VEHICLE SPEED SEN A-B"),
    P2183("P2183"),
    P2184("P2184"),
    P2185("P2185"),
    P219A("AIR FUEL RATIO IMBALANCE B1"),
    P219B("AIR FUEL RATIO IMBALANCE B2"),
    P2261("TC/SC BYPASS VALVE"),
    P2263("TC SYSTEM-B1"),
    P2299("P2299"),
    P2413("P2413"),
    P2423("HC ADS CATALYST-B1"),
    P2424("HC ADS CATALYST-B2"),
    P2432("SNDRY MAS A/F SE"),
    P2433("SNDRY MAS A/F SE"),
    P2440("AIR CUT S/V-B1"),
    P2442("AIR CUT S/V-B2"),
    P2444("AIR PUMP"),
    P2445("AIR PUMP"),
    P2448("SCNDRY AIR SYSEM"),
    P2457("EGR COOLER EFFICIENCY"),
    P2502("P2502"),
    P2527("P2527"),
    P2539("LOW FUEL PRES SEN"),
    P2540("LOW FUEL PRES SEN"),
    P2541("LOW FUEL PRES SEN"),
    P2542("LOW FUEL PRES SEN"),
    P2562("Turbocharger Boost Control Position Sensor Circuit"),
    P2563("Turbocharger Boost Control Position Sensor Circuit Range/Performance"),
    P2564("Turbocharger Boost Control Position Sensor Circuit Low"),
    P2565("Turbocharger Boost Control Position Sensor Circuit High"),
    P2566("Turbocharger Boost Control Position Sensor Circuit Intermittent"),
    P2586("Turbocharger Boost Control Position Sensor Circuit"),
    P2587("Turbocharger Boost Control Position Sensor Circuit Range/Performance"),
    P2588("Turbocharger Boost Control Position Sensor Circuit Low"),
    P2589("Turbocharger Boost Control Position Sensor Circuit High"),
    P2590("Turbocharger Boost Control Position Sensor Circuit Intermittent/Erratic"),
    P2610("ECM/PCM INTERNAL ENG OFF TIMER"),
    P261B("P261B"),
    P261C("P261C"),
    P261D("P261D"),
    P2635("LOW PRES FUEL PUMP"),
    P2681("P2681"),
    P26A3("P26A3"),
    P26A5("P26A5"),
    P26A6("P26A6"),
    P26A7("P26A7"),
    P26AB("P26AB"),
    P2713("PC SOLENOID D"),
    P2714("PC SOLENOID D"),
    P2722("PC SOLENOID E"),
    P2731("PC SOLENOID F"),
    P2765("INPUT SPEED SENSOR B"),
    P2807("PC SOLENOID G"),
    P2A00("A/F SENSOR1 (B1)"),
    P2A03("A/F SENSOR1 (B2)"),
    P3021("SUB FUEL CONT SOL/V"),
    P3022("SUB FUEL CONT SOL/V"),
    P3023("SUB FUEL CONT SOL/V"),
    P3075("SUB FUEL PUMP RELAY"),
    P3077("SUB FUEL PUMP RELAY"),
    P3078("SUB FUEL PUMP RELAY"),
    P31A5("COMMUNICATION ERROR")
}